- README.md
> Update README with more descriptive link text

- cloud/openstack/machineactuator.go
Adds error checking for calls to `StatusUpdate` and `DeleteKeyPair` in `Create()`
> Check for errors on StatusUpdate and DeleteKeyPair

- OWNERS_ALIASES
Raising my hand to help with reviews and discussions on the cluster-api-provider-openstack. I'm currently focused on testing, developing, and stabilizing this project. I'd like to help with reviews and maintenance as well.
> Adding flaper87 as a cluster-api-openstack-maintainer

- pkg/apis/openstackproviderconfig/v1alpha1/register.go
Uses the correct Group to register the provider config
N/A
N/A
```release-note
NONE
```
> Fix openstackprovierconfig registration

- pkg/cloud/openstack/deployer.go
Fixes #
```release-note
NONE
```
> Use NewDeploymentClient() to get DeploymentClient

- OWNERS_ALIASES
Adds @chaosaffe (me) as a mainainer for `cluster-api-provider-openstack`
None
This will give @chaosaffe (me) rights to approve and merge PR's in this repository
```release-note
NONE
```
> Add chaosaffe to cluster-api-openstack-maintainers

- cmd/clusterctl/examples/openstack/generate-yaml.sh
Fixes issues with Darwin/Linux `sed` differences
None
None
```release-note
NONE
```
> Add sed Darwin/Linux switch to generate-yaml.sh

- vendor/sigs.k8s.io/cluster-api/Gopkg.lock
- vendor/sigs.k8s.io/cluster-api/Makefile
- vendor/sigs.k8s.io/cluster-api/OWNERS_ALIASES
- vendor/sigs.k8s.io/cluster-api/README.md
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/README.md
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/minikube/minikube.go
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/create_cluster.go
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/delete_cluster.go
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
- vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args.golden
- vendor/sigs.k8s.io/cluster-api/config/crds/cluster_v1alpha1_machinedeployment.yaml
- vendor/sigs.k8s.io/cluster-api/scripts/ci-is-vendor-in-sync.sh
Update the vendored version of cluster-api to include the support for the `minikube` flag
> Update cluster-api version

- pkg/cloud/openstack/clusteractuator.go
- pkg/controller/add_cluster.go
Not implemented cluster actuator yet, but we need cluster controller anyway.
> add cluster controller

- README.md
> Updated to include clouds.yaml instructions

- README.md
- cmd/clusterctl/examples/openstack/generate-yaml.sh
- config/manager/manager_template.yaml
updates docs to explain how to set OS_CLOUD and choose your cloud.
#71
> Generate-yaml sets OS_CLOUD in provider manager to the OS_CLOUD in its working env

- README.md
- cmd/clusterctl/examples/openstack/README.md
Required option --provider-os was added to generate-yaml.sh in #90.
This patch fixes README.md.
> Fix README.md

- Gopkg.lock
- Gopkg.toml
- pkg/apis/openstackproviderconfig/v1alpha1/register.go
- pkg/cloud/openstack/machine/machinesetup/config_types.go
- vendor/sigs.k8s.io/yaml/.gitignore
- vendor/sigs.k8s.io/yaml/.travis.yml
- vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
- vendor/sigs.k8s.io/yaml/LICENSE
- vendor/sigs.k8s.io/yaml/OWNERS
- vendor/sigs.k8s.io/yaml/README.md
- vendor/sigs.k8s.io/yaml/RELEASE.md
- vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
- vendor/sigs.k8s.io/yaml/code-of-conduct.md
- vendor/sigs.k8s.io/yaml/fields.go
- vendor/sigs.k8s.io/yaml/yaml.go
- vendor/sigs.k8s.io/yaml/yaml_go110.go
Switch yaml package from ghodss repo to sigs.k8s.io fork
Fixes #110 
```release-note
```
> Switch yaml to sigs.k8s.io/yaml

- README.md
- cmd/clusterctl/examples/openstack/centos/machines.yaml.template
- cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template
- cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
- cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
Mitigation of CVE-2018-1002105
See https://github.com/kubernetes/kubernetes/issues/71411 for more details
https://github.com/kubernetes/kubernetes/issues/71411
```release-note
NONE
```
> Update examples to use 1.12.3

- pkg/cloud/openstack/clients/machineservice.go
**What this PR does / why we need it**: Fixes minor bugs and some unclear syntax
**Special notes for your reviewer**: :)
> Fixes some minor bugs and unclear syntax

- cmd/clusterctl/examples/openstack/generate-yaml.sh
This patch changes the following:
* Use the syntax of mikefarah's yq.
* Check if the installed yq is a python script and error out if it is.
Fixes #134
> Move to https://github.com/mikefarah/yq

- cmd/clusterctl/examples/openstack/generate-yaml.sh
Just re-applied the usage of yq from #135, because they were overridden
by #141.
Fixes #134
```release-note
```
> Re-apply of new yq usage

- pkg/cloud/openstack/machine/machineScript.go
This PR adds `MachineConfig` (`OpenstackProviderConfig` object) of machine to the context of startup script template. This is useful if we need to adjust startup script for some specific cases. In my case, I need to know floating IP of the master node in startup script for it (to work around an issue with networking).
```release-note
NONE
```
> Pass machine config into VM startup script template

- Gopkg.lock
- pkg/cloud/openstack/clients/networkservice.go
- pkg/cloud/openstack/cluster/actuator.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/urls.go
Tagged resouces networks, subnet and router with
`cluster-api-provider-openstack` and the cluster name in form of
`<namespace>/<name>`.
Fixes #171
```release-note
```
> Tagging of created network resources

- cmd/clusterctl/examples/openstack/README.md
`generate-yaml.sh` script is required yq. 
I add description for yq to readme.
I also imporve markdown layout.
> Improve generator readme

- OWNERS_ALIASES
Adds @chrigl  (me) as a mainainer for cluster-api-provider-openstack
None
This will give @chrigl (me) rights to approve and merge PR's in this repository
```release-note
```
> Add chrigl to cluster-api-openstack-maintainers

- pkg/cloud/openstack/machine/actuator.go
This patch adds the check (and wait) process what the old VM has been deleted before creating a new VM.  It solves the problem that creating a new VM is skipped with "Skipped creating a VM that already exists" message.
fixes #190
```release-note
NONE
```
> Check that the old VM has been deleted before creating a new VM

- README.md
This patch adds deleting the kubeconfig file step in the Cluster Deletion section.
> Update README.md to add deleting the kubeconfig file step in the Cluster Deletion section

- README.md
Because we have our own channel now \o/
Fixes #
```release-note
```
> Updated slack link to our own channel

- Gopkg.lock
- cmd/clusterctl/examples/openstack/ubuntu/machines.yaml.template
- pkg/apis/openstackproviderconfig/v1alpha1/types.go
- pkg/cloud/openstack/clients/machineservice.go
- pkg/cloud/openstack/machine/actuator.go
- vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/urls.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/delegate.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/urls.go
Problem was cluster-api-provider-openstack vendor was wrongly added
> Trunk revert

- docs/config.md
- pkg/apis/openstackproviderconfig/v1alpha1/types.go
- pkg/cloud/openstack/clients/machineservice.go
**What this PR does / why we need it**: Allows users to specify a specific subnet to use for their machine
> Subnet Support

- pkg/cloud/openstack/machine/actuator.go
We're currently trying to render userData whether it comes from our
scripts or someone else's. Rendering userData is not always necessary.
Some tools - `openshift-installer`, for example - provide  an already
rendered user data that just needs to be passed down to the machine.
This commit adds a new key to the `userDataSecret` to allow for disabling the rendering
step for the userData.
> Allow for passing already-rendered userData

- pkg/cloud/openstack/machine/actuator.go
Signed-off-by: Alex Yang <yangyang1@zte.com.cn>
As the title
> Delete useless const CloudConfigPath

- pkg/cloud/openstack/clients/networkservice.go
Due to no external network given, a error will be reported but
that's acceptable since we might not want to create router at all
in some scenario.
Fixes #
```release-note
```
> Fix a log about no external network

- docs/config.md
use template instead of hard code in the doc
otherwise we have to keep sync between template and doc
Fixes #
```release-note
```
> use template instead of hard code in the doc

- pkg/cloud/openstack/machine/actuator.go
have following in log:
E0308 08:36:06.485556       1 actuator.go:233] master inplace update failed: <nil>
Fixes #
```release-note
```
> Adjust log for update action

- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
**Which issue(s) this PR fixes** 
Fixes #244
> Change calico version to v3.5

- pkg/cloud/openstack/cluster/actuator.go
Fix the cluster name.
Fixes #
```release-note
None
```
> Fix the cluster name

- config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
- pkg/apis/openstackproviderconfig/v1alpha1/types.go
- pkg/cloud/openstack/clients/machineservice.go
you can choose either use config drive or metadata through this param
Fixes #
```release-note
```
> Add config drive support

- cmd/clusterctl/examples/openstack/generate-yaml.sh
some folder not workable through relative path
Fixes #
```release-note
```
> make generate-yaml.sh work from anywhere

- README.md
Fixes #
```release-note
NONE
```
> Added kind example for openstack provider.

- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
the permission by default maybe -rw--r--r and this file /etc/kubernetes/cloud.conf actually
contains the clouds password...
Fixes #
```release-note
```
> Fix permission of cloud.conf

- config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
- docs/config.md
- pkg/apis/openstackproviderconfig/v1alpha1/types.go
the param with _ will not able to auto generate
Fixes #
```release-note
```
> fix spec generatation

- OWNERS
- OWNERS_ALIASES
Change-Id: I5f84f77c80a10c947444219580fe2f99dda75255
Fixes #
```release-note
NONE
```
> Add more reviewers for the repository

- config/manager/manager.yaml
The old labels are removed.
added `node.kubernetes.io/not-ready` and
`node.kubernetes.io/unreachable`
See https://github.com/kubernetes/kubernetes/pull/73001
Fixes #
```release-note
```
> Added "new" node taints to tolerations

- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Unfortunately I tested on an existing cluster, which had exactly this
hardcoded token /o\
Fixes #
```release-note
```
> Fixed usage of bootstrap token

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Fixes #
```release-note
NONE
```
/cc @jichenjc @dims
> Added template for issue and features.

- README.md
Fixes #251
```release-note
```
>  Added compatibility information to README.md

- pkg/cloud/openstack/clients/clouds.yaml
Fixes #
```release-note
NONE
```
> Delete project_name from clouds.yaml.

- README.md
Fixes #
```release-note
Adding steps for how to use existing cluster as bootstrap cluster.
```
> Adding steps for how to use existing cluster as bootstrap cluster.

- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Fixes #
```release-note
Enabled debug log for kubeadm post install.
```
> Enabled kubeadm debug log for better troubleshooting.

- Gopkg.lock
- cmd/clusterctl/examples/openstack/cluster.yaml
- cmd/clusterctl/examples/openstack/machines.yaml.template
- config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml
- config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml
- docs/config.md
- pkg/apis/openstackproviderconfig/v1alpha1/types.go
- pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
- pkg/cloud/openstack/clients/machineservice.go
- pkg/cloud/openstack/cluster/actuator.go
- pkg/cloud/openstack/machine/actuator.go
- vendor/github.com/gophercloud/gophercloud/internal/pkg.go
- vendor/github.com/gophercloud/gophercloud/internal/util.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/doc.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/types.go
- vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/urls.go
1. Fix tagging bug introduced by egarcia
2. Allow cluster scoped, or machine specific tagging of resources
Fixes #280
**Special notes for your reviewer**: None
**Release note**: 
```release-note
NONE
```
> Clearer tagging UI and Bugfix

- OWNERS_ALIASES
Fixes #
```release-note
NONE
```
Both myself and @jichenjc has been working for OpenStack and Kubernetes for years, and also contributed to Cluster API and OpenStack Cloud Provider for some PRs and some active reviews, we want to be volunteers for this repo to help make OpenStack Cloud Provider become mature together with Cluster API.
/cc @dims @jichenjc
> Adding gyliu513 and jichenjc as approvers.

- README.md
> Add Kubeadm and Kubelet versions info in README.md

- README.md
Fixes #
```release-note
NONE
```
> Added coreos to openstack provider.

- Makefile
- pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
This PR adds ConfigDrive zz_generated.deepcopy.go by executing go
generate under pkg/apis.
Fixes #308 
```release-note
```
> Add ConfigDrive in zz_generated.deepcopy.go

- README.md
add description for clouds.yaml and cloud param.
Fixes #
```release-note
```
> Add doc for generate generate-yaml.sh

- README.md
- docs/trouble_shooting.md
time to time we have some questions on how to debug issue, add this for some debug tip
Fixes #
```release-note
```
> Add tips for trouble shooting

- CONTRIBUTING.md
- README.md
- cmd/clusterctl/examples/openstack/README.md
- code-of-conduct.md
- docs/config.md
- docs/trouble_shooting.md
Fixes #
```release-note
NONE
```
/cc @jichenjc @chrigl
> Added toc to md for better readability.

- cmd/clusterctl/examples/openstack/generate-yaml.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/common.yaml
the cloud.conf contains password and important info..
Also, fixed a typo
Fixes #
```release-note
```
> Fix permission of cloud.conf (644->600)

- config/manager/deployment.yaml
v1 is already ready now.
Fixes #
```release-note
```
> v1beta1 -> v1 for Deployment template

- README.md
Keystone port number 35357 is for admin user, cluster api user should use 5000.
Fixes #
```release-note
```
> Update keystone port number in README.md

- Makefile
- README.md
- cmd/clusterctl/examples/openstack/README.md
- cmd/clusterctl/examples/openstack/generate-yaml.sh
Add test in Makefile (test) to include a test for generate-yaml.sh in order to avoid 
further change break the functions of yaml generation.
Fixes #323 
```release-note
```
> Add generate yaml test

- config/manager/deployment.yaml
- overlays-config/coreos/manager/deployment.yaml
- overlays-config/generic/manager/deployment.yaml
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/325
```release-note
```
> Deployment V1 Spec required the selector

- cmd/clusterctl/examples/openstack/machines.yaml.template
fix the issue https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/325
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/325
```release-note
```
> change to use v1alpha1.SecurityGroupParam

- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
the `master-user-data.sh` did not specify the version of `kubectl`, it's better to make `kubectl`, `kubelet` and `kubeadm` use the same version.
Fixes #
```release-note
```
> use the same version of kubectl with kubelet

- pkg/cloud/openstack/clients/clouds.yaml
Fixes #
This is a follow up PR for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/224 , we need to update `clouds.yaml` by adding the `cacert` field.
```release-note
NONE
```
/cc @hidekazuna @jichenjc @hchenxa
> Adding cacert to clouds.yaml.

- Makefile
- cmd/clusterctl/Dockerfile
- cmd/manager/Dockerfile
build the api-controller with multi stage.
Fixes #
```release-note
```
> build controller with multi stage

- Makefile
Fixes #
```release-note
NONE
```
/cc @jichenjc @chrigl
> images do not need manifests in makefile.

- cmd/manager/main.go
- pkg/cloud/openstack/machine/actuator.go
- pkg/record/record.go
instance create and delete can be have some events so we can record
them and for audit purpose.
Fixes #350 
```release-note
```
> Add Record of instance action

- config/rbac/rbac_role.yaml
This patch fixes event creation.
Fixes #368 
```release-note
```
> Fix event creation

- README.md
This patch adds OpenStack Stein support. Cluster creation was succeeded on the following environment.
- cluster-api-provider-openstack
commit 6a108a0ba133d24faf52cc29f9fc3c874e2bfdd6 with #369 
- kind
version v0.3.0
- OS
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- OpenStack packages
```bash
$ dpkg -l |grep -e nova -e neutron -e cinder -e keystone -e glance
ii  cinder-api …
```
> Support OpenStack Stein

- README.md
- docs/development.md
This PR adds Development Guide. To test your code work for clusterctl create/delete manually, we need to build and upload openstack-cluster-api-controller image to the Docker registry. After that we have to specify the images explicitly in the yaml file. It is not clear for new contributor so that we need some guidance.
Fixes #
```release-note
```
> Add Development Guide

- Makefile
- README.md
- cmd/clusterctl/examples/openstack/README.md
- cmd/clusterctl/examples/openstack/generate-yaml.sh
- cmd/clusterctl/examples/openstack/provider-component/clouds-secrets/kustomization.yaml
- cmd/clusterctl/examples/openstack/provider-component/cluster-api/kustomization.yaml
- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/kustomization.yaml
- cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/kustomization.yaml
- cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/kustomization.yaml
commands is removed and replaced with files and literals
so update template accordingly
https://github.com/kubernetes-sigs/kustomize/commit/2fa4a3458924de6c3a1613fb0c69b2f658e6b3c7 has more info
Fixes #356 
```release-note
```
> update kustomize template to fit for latest kustomize

- docs/config.md
It is related to #378 . 
I am a new contributor and faced these issues while setting up my development environment.
Wanted feedback regarding command `openstack security group rule create --egress` . I feel we must add `protocol` tag in this command.
> Improvements in config.md file

- config/kustomization.yaml
- config/manager/statefulset.yaml
- overlays-config/coreos/manager/deployment.yaml
- overlays-config/generic/manager/deployment.yaml
per discussion , deployment has sideeffect such as potential
race condition, so need switch to statefulset.
Fixes #364 
```release-note
```
> move from deployment to statefulset

- cmd/clusterctl/examples/openstack/provider-component/user-data/centos/kustomization.yaml
centos generate has some issue, missed  commands=>files changes
Fixes #
```release-note
```
> Fix centos create generate issue

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/klog/klog.go
- vendor/k8s.io/klog/klog_file.go
upgrade klog from 0.1 to 0.3 to avoid no log issue
Fixes #
```release-note
```
> Fix klog issue

- OWNERS_ALIASES
Stefan works currently on cleaning up stuff as well as the multi master
implementation. I want him to be able to review PRs.
```release-note
```
> Added Stefan Büringer (sbueringer) to be a reviewer

- README.md
- cmd/clusterctl/examples/openstack/machine-deployment.yaml.template
- cmd/clusterctl/examples/openstack/machines.yaml.template
> Update kubeadm to 1.15

- README.md
This PR adds documentation on how to use custom CAs.
> add documentation on how to use custom CAs

- docs/config.md
- docs/development.md
1) add machinset  usage doc
2) updated the format of development.md
Fixes #
```release-note
```
> modify doc to add machineset

- README.md
> Add notes for using custom pod network CIDR

- pkg/cloud/openstack/services/networking/loadbalancer.go
> Add a log indicating lb member creation

- pkg/cloud/openstack/services/networking/service.go
cloud provider and others might create this kind of resource
as well, we might consider to make it clusterapi specific
Fixes #
```release-note
```
> Rename network prefix

- README.md
This PR fixes clouds.yaml link and add some notes about cacert in README.md.
Fixes #
```release-note
```
> Fix clouds.yaml link and add some notes in README.md

- cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
- cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/worker.yaml
I diffed the CoreOS userdata in the repo against the one I'm using to test in my air-gaped environment and found a small issue :)
> fixed quotes in coreos userdata

- cmd/clusterctl/examples/openstack/generate-yaml.sh
- cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml
- hack/update-gofmt.sh
- hack/verify-golint.sh
bash is not always in /bin, particularly on non-Linux systems. For example the OpenBSD system, it's in /usr/local/bin. so prefer to use #!/usr/bin/env bash.
refer https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash
Fixes #
```release-note
```
> use env for bash

- examples/generate.sh
after #465 the indentation of `cacert` looks something like this:
```
content: |
-----BEGIN CERTIFICATE-----
MIIFdDCCA1ygAwIBAgIQAThj+/U5lmI7829nD5I++zANBgkqhkiG9w0BAQsFADBU
...
```
this PR fixes it
Fixes #
```release-note
```
> fix certificate indentation

- examples/generate.sh
> Remove duplicate create

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Fixes #471 
```release-note
```
> Adopt PR icons

- clusterctl-settings.json
per https://master.cluster-api.sigs.k8s.io/clusterctl/developers.html
Each provider must have a clusterctl-settings.json
file describing how to build the provider assets.
currently using v0.2.0 and follow on we might need moidfy the value
Fixes #
```release-note
```
> Add clusterctl-settings.json

- README.md
The user must be linked to the main CAPI book for installation.
Fixes #
```release-note
```
>  📖 Update installation link

- templates/env.rc
> avoid basename usage to avoid source action failure

- README.md
This PR adds Stein to v1alpha3 tested version. Actually I am testing both templates on OpenStack Stein and working successfully(for cluster-templates.yaml, need #534)
Fixes #
```release-note
```
> 🏃 Add Stein to v1alpha3 tested version

- README.md
I manually updated the kubeadm to 1.18 in my env and it works fine..
Fixes #
```release-note
```
> Add 1.18 support into list

- OWNERS_ALIASES
As requested here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/548#pullrequestreview-397920686
> reviewers: remove flaper87

- controllers/openstackcluster_controller.go
Using `managedAPIServerLoadBalancer: true` in the `OpenStackCluster` configuration suggest that a load balancer will be created. However, when specifying an existing Openstack network instead of using `nodeCidr`, a load balancer is *not* created.
This PR make sure that:
- the load balancer is created;
- the controller do not try to remove the existing network.
**Which issue(s) this PR fixes** *
fixes #547 
- I had to refactor `reconcileNormal` as the linter was complaing about a cyclomatic complexity above 30 after my change.
```release-note
```
> 🐛 enable managedAPIServerLoadBalancer w/ existing network

- api/v1alpha3/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
follow up of sec group update (removal of ssh and add Calico CNI) to update the comment
Fixes #
```release-note
```
> update doc about ssh security group

- api/v1alpha3/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Fix to show ENDPOINT by kubectl get openstackcluster -o wide
Fixes #565 
```release-note
🐛 Fix to show ENDPOINT by kubectl get openstackcluster -o wide
```
> 🐛 Show openstackcluster ENDPOINT

- Makefile
Fixes #568 
```release-note
```
> 🐛 Invoke KUSTOMIZE in release-manifests

- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/router.go
- pkg/cloud/services/networking/securitygroups.go
- pkg/utils/errors/errors.go
Fixes #557 
```release-note
```
> ignore router get return 404  error

- README.md
OpenStack Stein should have been added to the v1alpha3 tested version by #535 , but actually not added. This PR fixes it.
Fixes #
```release-note
```
>  🐛 Fix README.md

- docs/troubleshooting.md
part of #572 
```release-note
```
> Add doc tip for floating ip

- pkg/cloud/services/compute/instance.go
Fixes #582 
```release-note
```
> report error if security group not exist

- pkg/cloud/services/networking/securitygroups.go
Fixes #591 
```release-note
```
> Add event for seucrity group

- pkg/cloud/services/networking/securitygroups.go
> nit: Add default egress rule description

- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/router.go
- pkg/cloud/services/networking/securitygroups.go
> Add more logs for debug purpose

- docs/external-cloud-provider.md
- templates/cluster-template-external-cloud-provider.yaml
- templates/create_cloud_conf.sh
This PR provides template, tool, and document for using external cloud provider.
Fixes #489 
```release-note
Use external cloud provider.
```
> ✨ Use external cloud provider

- OWNERS_ALIASES
This PR adds @hidekazuna to reviewer. @hidekazuna actively develops some features and tests CAPO using Octavia such as  #426,#534,#555,#563,#576.
Fixes #
```release-note
```
> 🏃 Add hidekazuna to reviewer

- README.md
This commit adds reference to the external cloud provider documentation in
README.md.
This PR adds the reference to the external cloud provider documentation in README.md, since we [added the documentation](#595).
Fixes #
```release-note
```
>  📖 Add reference to the external cloud provider doc

- templates/create_cloud_conf.sh
- templates/env.rc
fix this kind of error: 
`./env.rc: line 41: return: can only `return' from a function or sourced script`
Fixes #
```release-note
```
> nit: replace return with exit

- templates/cluster-template-external-cloud-provider.yaml
This PR updates template for the external cloud provider, since #573 missed updating the template.
Fixes #
This PR follows up #573 
```release-note
```
> 🏃 Update template for the external cloud provider

- .zuul/playbooks/run.yaml
> switch to no-admin for CI test

- docs/configuration.md
- templates/create_cloud_conf.sh
- templates/env.rc
Fixes #578
```release-note
```
> Add application cred usage

- api/v1alpha3/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- docs/configuration.md
- pkg/cloud/services/compute/instance.go
- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/router.go
- templates/cluster-template-without-lb.yaml
- templates/cluster-template.yaml
Fixes #543
```release-note
```
> Remove Tag creation for ports and add description for it

- pkg/cloud/services/networking/network.go
This PR renames `capierrors` to `capoerrors`.
Fixes #
```release-note
```
> Rename to capoerrors

- api/v1alpha3/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
This PR fixes get openstackcluster to show ENDPOINT value, degraded by #573 .
Fixes #
```release-note
```
> 🐛 Fix get openstackcluster to show ENDPOINT value

- .github/ISSUE_TEMPLATE/bug_report.md
Since we released some versions, we should know CAPO version from bug report.
This PR proposes to add CAPO version to github issue bug template.
Fixes #
```release-note
```
> 🏃 Add CAPO version to github issue template

- api/v1alpha3/openstackmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
nit: the providerID and InstanceState is accurate than existing one
Fixes #
```release-note
```
> nit: update name of `get` output for openstackmachine

- api/v1alpha3/openstackcluster_types.go
- api/v1alpha3/zz_generated.deepcopy.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
those might be used in v1alpha1 ,not used now
Fixes #
```release-note
```
> cleanup keys params

- main.go
- version/version.go
add versions of git into manager's log
Fixes #
```release-note
```
> Add version into log

- Dockerfile
This PR bumps go from 1.13.8 to 1.13.15.
Fixes #
```release-note
Bump Go to 1.13.15
```
> 🏃 Bump Go to 1.13.15

- docs/external-cloud-provider.md
This PR updated external cloud provider URL since Cloud Provider OpenStack has been moved to kubernetes organization.
Fixes #
```release-note
```
> 📖 Update external cloud provider URL

- controllers/openstackcluster_controller.go
- controllers/openstackmachine_controller.go
- pkg/cloud/services/loadbalancer/loadbalancer.go
This PR adds events deleting resources.
Fixes #643 
```release-note
Add events deleting resources.
```
> ✨ Add events deleting resources

- pkg/cloud/services/networking/network.go
Removed unnecessary colon from info message.
Fixes #
```release-note
```
> Remove unnecessary colon

- pkg/cloud/services/loadbalancer/loadbalancer.go
Fixed event message about port ID with associate Floating IP.
Fixes #
```release-note
```
>  🐛 Fix event message about port ID with associate Floating IP

- .zuul.yaml
Bump cluster-api-provider-openstack-conformance-pr job Go version to v1.13.15
Fixes #
```release-note
```
> 🏃 Bump Go to v1.13.15 in conformance pr job

- .zuul/playbooks/run.yaml
This PR removed USE_PYTHON3: True bacause USE_PYTHON3 is True by default since Ussuri release.
Fixes #
```release-note
```
> Remove USE_PYTHON3

- pkg/cloud/services/compute/instance.go
Fixes #
The root volume param is omitted and we should take into consideration 
```release-note
```
> Add root volume support (put root volume into instance create param)

- docs/configuration.md
> Add doc update for boot from volume case

- pkg/cloud/services/compute/instance.go
> nit: remove duplicate blanks

- controllers/openstackcluster_controller.go
Fixes #670
```release-note
```
> set openstack cluster status for Bastion

- .zuul/playbooks/run.yaml
> Switch CI from U to V release

- RELEASE.md
> Add cluster-template-external-cloud-provider.yaml into release doc

- Makefile
Fixes #687
```release-note
```
> update Make method to avoid mismatch

- .github/ISSUE_TEMPLATE/bug_report.md
OpenStack version information helps us to understand bug.
Fixes #
```release-note
```
>  🏃 Add OpenStack version to bug report template

- controllers/openstackcluster_controller.go
**What this PR does / why we need it**: When the network element does not exist (when trying to delete a failed cluster creation), the controller dies with the nil pointer exception. This PR fixes that.
Fixes #
```release-note
```
> Fix nil pointer error for Network

- OWNERS
- OWNERS_ALIASES
Move ncdc to emeritus status
Fixes #
```release-note
NONE
```
> 🏃 Move ncdc to emeritus status

- pkg/cloud/services/compute/bastion.go
- pkg/cloud/services/compute/instance.go
createInstance and deleteInstance should not be exposed.
Fixes #
```release-note
```
> 🏃Refactor create, delete instance

- pkg/cloud/services/loadbalancer/loadbalancer.go
- pkg/cloud/services/loadbalancer/service.go
- pkg/cloud/services/networking/floatingip.go
This PR removes floating IP related function and uses networking service instead in loadbalancer package.
Fixes #
```release-note
```
> 🏃 Refactor loadbalancer package

- pkg/cloud/services/networking/router.go
Fixes #718
```release-note
```
> 🐛Ignore not found error when remove router interface

- controllers/openstackmachine_controller.go
- docs/mover.md
Fixes #726
```release-note
```
> update openstack provider format from // to ///

- config/manager/manager.yaml
This PR updates manager.yaml to match capi's manager.yaml. It is better to understand.
Fixes #
```release-note
```
> 🏃Remove unnecessary field in manager.yaml

- templates/cluster-template-external-cloud-provider.yaml
- templates/cluster-template-without-lb.yaml
- templates/cluster-template.yaml
Fixes #735 
```release-note
```
> 🐛 Add NAMESPACE variable in cluster templates.

- docs/configuration.md
Fix typo. Add line continuation character to fix command in docs.
```release-note
```
> Fix clusterctl config command

- RELEASE.md
Just incrementally improving the RELEASE.md
> 📖 improve RELEASE.md

- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/router.go
refactory code to move general functions to network.go
Fixes #
```release-note
```
> Refactory network functions (router.go==>network.go)

- docs/configuration.md
FIx a typo
Fixes #
```release-note
```
/hold
> Fix a doc typo

- templates/create_cloud_conf.sh
- templates/env.rc
YAML processor yq have released V4 which is quite different from previous versions. We'd like to update the code of create_cloud_conf.sh and env.rc to support both new and old versions of yq.
Fixes #769
```release-note
NONE
```
/hold
> 🏃 update yq commands to support yq V4

- OWNERS
- OWNERS_ALIASES
Move ncdc to emeritus status
Fixes #
```release-note
NONE
```
> 🏃 [0.2] Move ncdc to emeritus status

- go.mod
- go.sum
- hack/tools/go.mod
- hack/tools/go.sum
Recently saw https://github.com/onsi/ginkgo/issues/780, where ginkgo v1.15.0 caused `--skip=""` to skip all tests. It might be a good idea to bump it's version to v1.15.2 which fix this issue.
Fixes #
**TODOs**:
```release-note
```
/hold
> 🏃 Bump ginkgo version

- README.md
Currently, the link is directed to a blank issue. And it would be better to redirect the new user to the issue with correct template. 
Fixes #
**TODOs**:
```release-note
```
/hold
> 📖 Update links for filing new issue

- docs/configuration.md
Fixed yaml example using bastion.
Fixes #
**TODOs**:
/hold
> 🐛 Fix configuration.md about bastion

- controllers/openstackcluster_controller.go
- controllers/openstackmachine_controller.go
- pkg/cloud/services/compute/bastion.go
- pkg/cloud/services/networking/floatingip.go
- pkg/cloud/services/networking/securitygroups.go
> 🐛 Delete bastion if basion.enabled=false

- hack/ci/devstack-cloud-init.yaml.tpl
- test/e2e/data/ci-artifacts-platform-kustomization.yaml
- test/e2e/shared/common.go
- test/e2e/shared/exec.go
- test/e2e/shared/exec_test.go
- test/e2e/shared/openstack.go
This verifies if our OpenStack keypair feature works (until now we just used pw login to retrieve logs during the e2e tests).
There are also some improvements in the way we get the logs, mainly better resiliency and logs.
Related to #784
/hold
> 🏃  Test openstack key in our e2e tests

- README.md
Currently, the supported versions are shown until v1.18. As pointed by @sbueringer in the chat linked below, [compatibility of v1Alpha3 CAPI](https://cluster-api.sigs.k8s.io/reference/versions.html?highlight=kubernetes#release-components) must apply in CAPO as well.
Xref: https://kubernetes.slack.com/archives/CFKJB65G9/p1617006848045700
Fixes #
**TODOs**:
/hold
> 📖 Update supported version of k8s in Readme

- README.md
Now that our CI tests against all templates, we can remove note about CI limitation.
Now that our CI tests against all templates, we can remove note about CI limitation.
Fixes #
**TODOs**:
/hold
> 📖 Remove note about CI

- pkg/cloud/services/loadbalancer/loadbalancer.go
- pkg/cloud/services/loadbalancer/service.go
Currently loadBalancerName is created in each function. It is better to aggregate by creating function.
Fixes #
**TODOs**:
/hold
> 🏃 Refactor: Make getLoadBalancerName function

- Makefile
- cloudbuild-nightly.yaml
- config/default/manager_image_patch.yaml
- test/e2e/data/e2e_conf.yaml
- tilt-provider.json
Details in the linked issue
Fixes #814
**TODOs**:
/hold
> 🏃 publish nightly artifacts

- Makefile
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/826#discussion_r606081071
/hold
> 🐛 fix conversion-gen

- README.md
Adds documentation about our postsubmit and nightly publish jobs.
Fixes #824
**TODOs**:
- [] adds unit tests
/hold
> 📖 add documentation about postsubmit and nightly images/manifests

- controllers/openstackmachine_controller.go
- pkg/cloud/services/compute/bastion.go
- pkg/cloud/services/compute/instance.go
remove a TODO (wait for instance delete complete in reconcile logic)
Fixes #
**TODOs**:
/hold
> Wait for instance delete

- docs/book/src/clusteropenstack/configuration.md
This PR follows up #860 
Fixes #
**TODOs**:
/hold
> 📖 Add doc related to log level

- pkg/cloud/services/loadbalancer/loadbalancer.go
helpful for me to debug some LB issues...
Fixes #
**TODOs**:
/hold
> Add more logs for LB creation

- OWNERS_ALIASES
I think  @chrischdi would be a great addition to our team of reviewers. 
This is highlighted through previous contributions and PR reviews.
Thank you for all you work until now!
I would propose a lazy consensus period until Friday 28th Mai and would merge if there are no objections until then.
/hold
> Add chrischdi as reviewer

- OWNERS_ALIASES
I think  @seanschneeweiss would be a great addition to our team of reviewers. 
This is highlighted through previous contributions and PR reviews.
Thank you for all you work until now!
I would propose a lazy consensus period until Friday 28th Mai and would merge if there are no objections until then.
/hold
> Add seanschneeweiss as reviewer

- pkg/cloud/services/compute/instance.go
> honor server group ID parm

- pkg/cloud/services/loadbalancer/loadbalancer.go
Add create listener, pool, and monitor events.
Fixes #
This PR would be rebased after #863 merged. 
**TODOs**:
/hold
> Add some events related to load balancer

- pkg/cloud/services/networking/floatingip.go
Currently SuccessfulAssociateFloatingIP and SuccessfulDissociateFloatingIP events are recorded even if waiting for status failed.
This PR fixes it.
Fixes #
**TODOs**:
/hold
> 🐛 Fix event of associate/disassociate floating IP

- controllers/openstackcluster_controller.go
This PR implements https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210203-externally-managed-cluster-infrastructure.md for the OpenStack provider.
Fixes #859
> :sparkles: add predicates.ResourceIsNotExternallyManaged to cluster controller

- test/e2e/shared/openstack.go
- test/e2e/suites/e2e/e2e_test.go
Adds an e2e test for creating servers with custom port options
Fixes #907
- [ X ] adds e2e tests
> 🏃 Add test for custom port options feature

- pkg/cloud/services/compute/service.go
- pkg/cloud/services/networking/service.go
Fixes #
This change is trivial. It does $SUBJECT.
**TODOs**:
- [] squashed commits
/hold
> 🐛 Don't log nil error when AuthInfo is not set

- RELEASE.md
Needed for https://github.com/kubernetes/k8s.io/issues/1597
Needed for https://github.com/kubernetes/k8s.io/issues/1597
> Rename master to main

- controllers/openstackmachine_controller.go
> reassociate Floating IP if first associate fails

- README.md
- docs/book/src/clusteropenstack/configuration.md
- test/e2e/data/e2e_conf.yaml
Fixes #943
Bumped Kubernetes version in the e2e tests to v1.21.2.
Further, adapted the tables format according to [the CAPI supported version in the CAPI books](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/reference/versions.md) 
**TODOs**:
/hold
> 📖 Adjust README.md to fit v0.4.0 and bump k8s to v1.21.3

- RELEASE.md
Just a minor fix to the release doc.
Fixes #
**TODOs**:
/hold
> 📖  improve release documentation

- pkg/cloud/services/networking/floatingip.go
Fixes #949
A nice side effect is that we save a OpenStack API call.
**TODOs**:
/hold
> ✨ Do not update fip if its already mapped correct

- .gitignore
- netlify.toml
Part of #783 
**TODOs**:
/hold
> 📖 Add netlify.toml to publish our book

- test/e2e/suites/e2e/e2e_test.go
we need put without LB info into without LB bucket
Fixes #
**TODOs**:
/hold
> Update flavor usage of e2e test

- README.md
Now CAPO book has been published, let's add the link to README.
Fixes #
**TODOs**:
/hold
> 📖 Add book link to README

- api/v1alpha4/openstackcluster_webhook.go
- config/webhook/manifests.yaml
> ✨Add webhook of openstackcluster, no update allowed for now

- docs/book/src/clusteropenstack/configuration.md
`filters` should be `filter` in manifest.
Fixes #
**TODOs**:
/hold
> 📖 Fix yaml example

- RELEASE.md
In image promotion process, the PR must be proposed and approved. This PR adds the fact.
Fixes #
/hold
> 📖 Update RELEASE document

- README.md
Add OpenStack Provider v1beta1 to version support and update format.
Fixes #
**TODOs**:
/hold
> 📖 Update version support

- Makefile
This PR fixes conversion-gen in Makefile.
Fixes #
When proposing #1047 ,  `api/v1alpha3/zz_generated.conversion.go` and `api/v1alpha4/zz_generated.conversion.go` are generated manually. Do not worry for the PR 😄 
/hold
> 🏃 Fix conversion-gen in Makefile

- api/v1alpha3/types.go
- api/v1alpha4/types.go
- api/v1beta1/types.go
- controllers/openstackmachine_controller.go
Fixes #889 
Fixes #1037 
Fixes #1038 
**TODOs**:
/hold
> 🐛update logic to support more instance state

- docs/book/src/clusteropenstack/configuration.md
Update API version in the examples and fix some nits.
Fixes #
/hold
> 📖 Update configuration document

- cloudbuild-nightly.yaml
- cloudbuild.yaml
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1523
> images: use k8s-staging-test-infra/gcb-docker-gcloud

- api/v1alpha4/openstackcluster_webhook.go
- api/v1alpha4/openstackcluster_webhook_test.go
- api/v1alpha4/openstackclustertemplate_webhook.go
- api/v1alpha4/openstackmachinetemplate_webhook.go
- docs/book/src/clusteropenstack/configuration.md
Part of #1054
cherry-picks #1076 (as part of #1070)
**TODOs**:
/hold
> ✨ [v0.4.0] Allow webhook changes to OpenStackCluster.Spec.Bastion

- api/v1alpha4/openstackcluster_webhook.go
- api/v1alpha4/openstackcluster_webhook_test.go
- api/v1alpha4/openstackclustertemplate_webhook.go
- api/v1alpha4/openstackmachinetemplate_webhook.go
- docs/book/src/clusteropenstack/configuration.md
Part of #1054
cherry-picks #1070
**TODOs**:
/hold
> ✨ [v0.5.0] Allow webhook changes to OpenStackCluster.Spec.Bastion

- SECURITY_CONTACTS
The issue creating a SECURITY_CONTACTS file raised by bot in spite of the file exists. The content is not equal to the template[1] so this PR update.
[1] https://github.com/kubernetes/kubernetes-template-project/blob/master/SECURITY_CONTACTS
Fixes #1079
> 🏃 Fix SECURITY_CONTACTS

- OWNERS_ALIASES
Add to maintainers:
- chrischdi
- mdbooth
- seanschneeweiss
- tobiasgiese
Add to reviewers:
- iamemilio
- macaptain
Fixes #1078
/hold
> 🏃Add new maintainers and reviewers

- pkg/cloud/services/loadbalancer/loadbalancer.go
Fixes the metric exposed when listing load balancer members.
Fixes #
**TODOs**:
/hold
<sub> Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> 🐛 loadbalancer service: fix metric name for member list

- pkg/cloud/services/loadbalancer/loadbalancer.go
> 🐛update log to make it clear (LB member  instead of LB)

- docs/book/src/clusteropenstack/configuration.md
at first read (use the doc) make me a little bit confuse where to add the stuff..
Fixes #
**TODOs**:
/hold
> 📖nit: update doc to include spec

- pkg/cloud/services/compute/instance.go
- pkg/cloud/services/compute/instance_test.go
part of #1085 
Fixes #
**TODOs**:
/hold
> Delete trunk on failure

- OWNERS
- OWNERS_ALIASES
Hi all, it has been a pleasure working with all of you. I am moving on to a new job, and will no longer be able to be a reviewer here.  Best of luck to you all!
> iamemilio resigns as a reviewer

- test/e2e/shared/openstack.go
- test/e2e/suites/e2e/e2e_test.go
Add test for trunk feature
Requires: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1125
> Add test for trunk feature

- config/manager/manager.yaml
Fixes #1140
**TODOs**:
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> manager.yaml: enable metrics endpoint

- OWNERS
- OWNERS_ALIASES
> Make hidekazuna emeritus

- hack/ci/aws-project.sh
- hack/ci/create_devstack.sh
- hack/ci/gce-project.sh
- hack/ci/openstack.sh
This allows use of a private key stored on a hardware token.
/hold
> 🏃 devstack: Allow empty private SSH key

- pkg/cloud/services/compute/instance_test.go
- pkg/cloud/services/networking/port.go
Fixes #
1) remove one FIXME as it's expected
2) remove another FIXME as we don't need get port first then delete it, we already have handle for 404 error
**TODOs**:
/hold
> ✨Remove FIXME (adjust the comment and code both)

- api/v1beta1/openstackmachine_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
Fixes #1149
**TODOs**:
/hold
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
> 🐛 api/v1beta1/openstackmachine_types.go: change errorReason/errorMessage to failureReason/failureMessage

- OWNERS
- OWNERS_ALIASES
Syncs the OWNERS and OWNERS_ALIASES files to the same state as on master so the same who could approve to main are able to approve to the still in-use release branch.
Fixes #
**TODOs**:
- [x ] squashed commits
/hold
<sub> Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>
> 🏃 sync OWNERS and OWNERS_ALIASES for v0.5 release branch

- controllers/openstackcluster_controller.go
- docs/book/src/clusteropenstack/configuration.md
> Remove `internal` AZ special handling

- pkg/cloud/services/networking/service.go
> Fix flaky UT on gate

- api/v1alpha3/types.go
- api/v1alpha4/types.go
- controllers/openstackmachine_controller.go
Cherry pick of #909 onto release-0.5 as discussed in #1166
I had to remove the changes to `v1beta1` type, as that does not exist in release-0.5
> 🐛 update logic to support more instance state

- README.md
> 📖update doc to talk about microversion

- pkg/cloud/services/networking/trunk_test.go
> Add unit test for trunk

- api/v1alpha3/openstackcluster_types.go
- api/v1alpha4/openstackcluster_types.go
- api/v1beta1/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
Some people miss the warning about this in the docs, I hope that having this info in the CRD makes it easier to discover.
Fixes #1180 
> 🏃 Explain mutability of bastion configuration in CRD

- go.mod
- go.sum
> address CVE-2022-27191

- OWNERS_ALIASES
Add myself (@apricote) as a reviewer in the `OWNER_ALIASES` file. This was discussed in today's office hours.
The other files linked here only include maintainers, so I think there is no more work to be done after this PR.
> 🏃 Add apricote as a reviewer

- OWNERS_ALIASES
@prankul88, if you're planning to stay around I'm very happy to leave you in! If not, this should stop spam from reviews being automatically assigned to you.
/hold
> 🏃Remove prankul88 as a reviewer

- pkg/cloud/services/loadbalancer/loadbalancer.go
- pkg/cloud/services/loadbalancer/loadbalancer_test.go
Previously we only waited for the loadbalancer to become active in case we created a new loadbalancer. Through this change, we will also wait for the loadbalancer to become active in case it already existed prior to the current reconcile.
Fixes #1197
/cherry-pick release-0.5
> 🐛 always wait for active Loadbalancer after getOrCreate

- metadata.yaml
> 🌱 Add release 0.6.x to metadata.yaml

- OWNERS
- OWNERS_ALIASES
Stepping down as maintainer due to job changes.
Please also see other PRs:
- https://github.com/kubernetes/k8s.io/pull/3701
- https://github.com/kubernetes/test-infra/pull/26187
- https://github.com/kubernetes/org/pull/3401
/hold
> move chrischdi to emeritus_approvers

- pkg/cloud/services/compute/instance_test.go
**What this PR does / why we need it**
reuse existing code branch for simple 
Fixes #
**TODOs**:
/hold
> refactory test code (reuse existing function)

- README.md
- docs/book/src/clusteropenstack/configuration.md
- test/e2e/data/e2e_conf.yaml
replace 1.23.5 with 1.24.2 in our doc/test
Fixes #
**TODOs**:
/hold
> use 1.24 as test env

- Makefile
- cloudbuild-nightly.yaml
- cloudbuild.yaml
- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
- bump cloudbuild image as described [in the CAPI version migration](https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html)
Part of #1282
**TODOs**:
/hold
<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>
> 🌱 Bump CAPI to v1.2.0

- test/e2e/shared/openstack.go
add more dumps so we can find more clue for debug
Fixes #
**TODOs**:
/hold
> e2e test: add more dump output

- hack/ci/gce-project.sh
Signed-off-by: Tobias Giese <tobias.giese@mercedes-benz.com>
Currently we're facing several "The zone [...] does  not have
enough resources available to fulfill the request" issues.
To hopefully avoid this we have to loop over all zones to create our instance.
Fixes #1317
**TODOs**:
/hold
/test pull-cluster-api-provider-openstack-conformance-test
<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal …
> 🌱 gce-project.sh: loop over all GCP zones during instance creation

- README.md
yoga was added ,so update the doc
Fixes #
**TODOs**:
/hold
> 📖 update README to include Yoga

- docs/book/src/clusteropenstack/configuration.md
> update doc to make it more clear

- docs/book/src/topics/external-cloud-provider.md
original URL not found anymore
Fixes #
**TODOs**:
/hold
> doc: update calico location

- Makefile
- go.mod
- go.sum
- test/e2e/data/e2e_conf.yaml
Bumps CAPI to v1.2.4.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: -
**TODOs**:
/hold
> 🌱 Bump CAPI to v1.2.4

- hack/ci/create_devstack.sh
- hack/ci/openstack.sh
The hack/ci/openstack.sh script creates servers that boot from volumes. These volumes were not cleaned up before. With this commit the volumes are created explicitly with the same name as the servers and then deleted together with them.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: -
**TODOs**:
/hold
> 🌱 CI: Clean openstack volumes

- pkg/cloud/services/compute/instance_types.go
> switch version from float to int

- metadata.yaml
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/shared/v1beta1_provider/metadata.yaml
Mechanical changes required on the creation of the 0.7 release branch.
/hold
> 🌱Release 0.7 patches

- docs/book/src/clusteropenstack/configuration.md
- docs/book/src/development/ci.md
- docs/book/src/topics/mover.md
Just some minor spelling mistakes I came across while reading the docs.
Fixes #
**TODOs**:
/hold
> :book: Fix spelling errors on docs

- OWNERS_ALIASES
Add @lentzi90 to reviewers
/hold
> ✨Add lentzi90 to reviewers

- pkg/cloud/services/loadbalancer/loadbalancer.go
>  🌱Add log to provide more info in case error happen

- controllers/openstackcluster_controller.go
- controllers/openstackmachine_controller.go
- main.go
- pkg/cloud/services/provider/provider.go
> ✨ Add ca-cert flag to supply a default ca certificate for each requests

- docs/book/src/clusteropenstack/configuration.md
Fix documentation, for tagging and serverMetadata in OpenstackMachineTemplates
Fixes #1453
**TODOs**:
/hold
>  📖 fix path for taggin and serverMetadata in OpenstackMachineTemplates

- docs/book/src/development/development.md
This adds additional information on how to create a test environment similar to the one used during continuous integration.
> 📖 Add documentation for creating local test environments

- docs/book/src/clusteropenstack/configuration.md
**What this PR does / why we need it**: With #1444 merged, we need some documentation around to help users starting using it.
**Special notes for your reviewer**: Maybe we can freeze this PR until the next release (otherwise the flavor won't be yet available).
/hold
> :book: docs/configuration: add Flatcar to OS section

- OWNERS_ALIASES
> Add lentzi90 to cluster-api-openstack-maintainers

- OWNERS_ALIASES
main: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1537
> [release-0.7] Add lentzi90 to cluster-api-openstack-maintainers

- hack/ensure-kubectl.sh
https://github.com/kubernetes/k8s.io/issues/2396
Fixes #
**TODOs**:
/hold
> Use dl.k8s.io instead of kubernetes-release bucket

- api/v1alpha7/openstackcluster_webhook.go
- api/v1alpha7/openstackcluster_webhook_test.go
Use-case described in #1589.
Fixes #1589.
**TODOs**:
/hold
> ✨ Allowing update of OpenstackCluster API server fixed IP

- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/router.go
Updates logger messages to conform to structured logging guidelines here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
/hold
> 🌱 Migrate pkg/cloud/services/networking/network.go and router.go to structured logging

- pkg/cloud/services/networking/port.go
> 🐛 fix port cleanup when using CAPO-created cluster network

- test/e2e/suites/e2e/clusterctl_upgrade_test.go
> 🐛Fix failing clusterctl upgrade test

- pkg/cloud/services/networking/port.go
> 🐛 Don't fail when deleting non-existing port

- controllers/suite_test.go
This just adds a simple test for the `getOrCreate`. I wrote it while trying to figure out what was happening in #1582 and thought I might as well push it.
Fixes #
**TODOs**:
/hold
> 🌱 Add test for getOrCreate

- Makefile
- hack/tools/Makefile
> 🌱 Remove defaulter-gen

- Makefile
The primary purpose of this change is to enable running the envtests in environments where neither $XDG_DATA_HOME nor $HOME are set.
Additionally, by executing setup-envtest explicitly in the `test` rule rather than in a global variable definition, we:
* Only run it when it's required
* Log its execution and output
> 🌱 Allow custom KUBEBUILDER_ASSETS_DIR in tests

- api/v1alpha5/zz_generated.conversion.go
- api/v1alpha6/conversion.go
- api/v1alpha6/zz_generated.conversion.go
- api/v1alpha7/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
- pkg/cloud/services/networking/network.go
- pkg/cloud/services/networking/network_test.go
> ✨ Add option to customize private network MTU

- test/e2e/shared/openstack.go
This PR will help CI to collect the Cinder volumes that were created during the run.
> 🌱 e2e: dump cinder volumes

- api/v1alpha7/openstackcluster_webhook.go
- api/v1alpha7/openstackcluster_webhook_test.go
- pkg/cloud/services/loadbalancer/loadbalancer.go
> 🐛 Don't remove BYO api server loadbalancer floating IP

- controllers/openstackcluster_controller.go
- controllers/openstackmachine_controller.go
- docs/book/src/clusteropenstack/configuration.md
- pkg/cloud/services/compute/instance.go
- pkg/cloud/services/compute/instance_test.go
> ✨remove flavor check to relief restrictions to CPU

- controllers/openstackmachine_controller.go
Fixed log syntax errors
Fixes #
**TODOs**:
/hold
> 🌱 Fix log message typo

- OWNERS
- OWNERS_ALIASES
Sean and I are unable to continue maintaining the project due to time constraints 😞
We will be stepping down from our maintainer status and passing the torch to the next capable hands.
> Remove Tobias and Sean as maintainer

- api/v1alpha8/groupversion_info.go
- api/v1alpha8/openstackcluster_types.go
- api/v1alpha8/openstackclustertemplate_types.go
- api/v1alpha8/openstackmachine_types.go
- api/v1alpha8/openstackmachinetemplate_types.go
Ref: https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6#suggested-changes-for-providers 
Fixes #
**TODOs**:
/hold
> 🌱 change how we register scheme as per capi 1.6

- controllers/openstackcluster_controller.go
- controllers/openstackcluster_controller_test.go
Like we do for the OpenStackMachine Status, put the Image ID in OpenStack Cluster Bastion ReferencedResources if bastion is enabled.
Fixes #1835
> 🐛 Fill up OpenStack cluster ReferencedResources with Image ID

- docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
> fix: fix the block device type name in doc

- api/v1alpha8/openstackcluster_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
> 🌱 Fix doc references to NodeCIDR in v1alpha8

- test/e2e/data/e2e_conf.yaml
- test/e2e/suites/e2e/clusterctl_upgrade_test.go
We should test upgrades from the latest release (v0.9) to main to ensure that we don't break the upgrade path.
Fixes #
**TODOs**:
> 🌱 E2E: Add clusterctl upgrade test for v0.9 -> main

- test/e2e/data/e2e_conf.yaml
- test/e2e/data/kustomize/common-patches/externalNetworkByName/kustomization.yaml
- test/e2e/data/kustomize/default/kustomization.yaml
- test/e2e/data/kustomize/flatcar-sysext/kustomization.yaml
- test/e2e/data/kustomize/flatcar/kustomization.yaml
- test/e2e/data/kustomize/v1alpha6/kustomization.yaml
- test/e2e/data/kustomize/v1alpha7/kustomization.yaml
- test/e2e/data/kustomize/without-lb/kustomization.yaml
> 🐛 CI: Specify external network by name

- docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md
- docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
This removes outdated warnings which say v1beta1 and v1alpha7 are not released yet.
Fixes #
**TODOs**:
/hold
> 📖  remove outdated warnings

- pkg/cloud/services/networking/port.go
Fixes# https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2063 
/hold
> Fix nil pointer issue while creating port

- .golangci.yml
- pkg/cloud/services/networking/floatingip.go
- pkg/scope/mock.go
- pkg/scope/provider.go
- pkg/scope/scope.go
Like it's done for other versions.
> 🌱 lint: import v1alpha1 with alias

- Makefile
- hack/tools/Makefile
Run `make test` with gotestsum so we can have both raw logs and junit output.
> 🌱 Add junit formatting for unit tests

- OWNERS_ALIASES
> 🌱Add EmilienM as a maintainer

- api/v1beta1/types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
- docs/book/src/api/v1beta1/api.md
> 📖 Document that OVSHWOffload is no longer required

- README.md
- docs/book/book.toml
Also I created a doc per year and moved content.
> 📖 Update agenda links w/ shared drive

- test/e2e/shared/openstack.go
- test/e2e/suites/e2e/e2e_test.go
We were trying to delete the security group in a DeferCleanup() called
from the test itself. This will execute before the cluster is deleted,
so it can't work as the cluster machines are still using the security
group. We need to delete the security group after the cluster has been
deleted.
In making this change, we also add a context argument to
postClusterCleanup and propagate that to the other users of this
mechanism.
/hold
> 🐛 e2e: Fix deletion of test security group

- metadata.yaml
- test/e2e/data/e2e_conf.yaml
- test/e2e/data/shared/v1beta1_provider/metadata.yaml
> ✨ Bump version artifacts for release-0.11

- CONTRIBUTING.md
> 📖 Add section on support and guarantees

- docs/book/src/clusteropenstack/configuration.md
Document https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1567
Fixes #
**TODOs**:
> 📖 Add docs about microversions

- .gitignore
- Makefile
- test/e2e/data/e2e_conf.yaml
- test/e2e/suites/conformance/conformance_test.go
The conformance suite was using deprecated ginkgo v1 functionality. This commit migrates it to v2, which makes the tests run again.
Fixes #1800
**TODOs**:
> 🌱 Fix conformance suite

- Dockerfile
- test/e2e/data/kubetest/conformance-fast.yaml
- test/e2e/data/kubetest/conformance.yaml
- test/e2e/suites/conformance/conformance_suite_test.go
- Fix case mismatch in Dockerfile
- Fix ginkgo deprecated flags
- Fix controller runtime SetLogger never called
Fixes #
**TODOs**:
/hold
> 🌱 Conformance: Fix warnings

- pkg/clients/compute.go
- pkg/clients/mock/compute.go
- test/e2e/shared/common.go
- test/e2e/shared/openstack.go
We already try to collect logs by ssh'ing to the machines. However, that relies on having an IP and bastion/security groups that allow it. Getting the console log should be able to give us more logs in more situations.
Fixes #
**TODOs**:
/hold
> 🌱 E2E: Collect console log from machines

- hack/tools/Makefile
Support for go1.24 was added in v1.64.2 but I am bumping to latest.
Fixes #2447 (I hope)
**TODOs**:
/hold
> 🌱 Bump golangci-lint to support go1.24

- scripts/ci-e2e.sh
> Fix logging when e2e prerequisites build fails

- RELEASE.md
The docs were still describing the manual way for generating release notes and artifacts. This is no longer necessary since we have a workflow that does it automatically.
Fixes #
**TODOs**:
> 📖 Update release docs with the automated release workflow

- Makefile
- netlify.toml
Bumps go to the latest patch release.
Fixes #
**TODOs**:
/hold
> 🌱 Bump go to 1.23.8

- api/v1beta1/types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml
fix issue: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2421
ref issue: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2421
**TODOs**:
/hold
> fix: enum typo error.

- docs/book/src/development/development.md
Fixes a broken link to cluster API docs
Fixes #
**TODOs**:
/hold
> 📖 Fix broken link to cluster API docs

- test/e2e/data/ccm/cloud-controller-manager.yaml
Update the manifest files in e2e tests
Fixes #2567 
**TODOs**:
/hold
> 🌱 E2E: Update openstack cloud provider manifests

- config/crd/kustomization.yaml
- metadata.yaml
Part of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2653
Fixes #
**TODOs**:
> 🌱 Add metadata for v0.13 and v1beta2 contract

- hack/tools/Makefile
> 🌱 Fix URL for downloading gotestsum based on OS

- .github/workflows/pr-verifer.yml
CAPO was missing PR title verify and this will be helpful in release automation.
> 🌱Add PR title verify workflow for CAPO

- hack/tools/Makefile
- pkg/cloud/services/compute/instance.go
- pkg/utils/filterconvert/convert.go
Update golanci-lint and fix linting issues found.
Fixes #
**TODOs**:
> 🌱 Update golangci lint v2.5.0

- Dockerfile
- Makefile
> 🐛 Uplift go to address CVEs
