cmd/machine-controller/Dockerfile
Resolves #10
Changes the base image for machine-controller from Alpine to the
Kubernetes debian-base images and installs the ca-certificates package
using the clean-install tool
=> Switch from alpine to debian-base

cloud/openstack/machineactuator.go
`err` is not set, but returned in the error message, resulting in the message:
```
create ssh key pair err: <nil>
```
=> Persist CreateKeyPair error for err return

README.md
Current version of the minikube (0.28.2) won't work. There is an opened issue
upstream (kubernetes-sigs/cluster-api#475).
See also:
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/commit/e854ca60b92cc251a30042dab16e9f27b6669664
=> Be explicit that minikube <= 0.28.0 is required.

cloud/openstack/machineactuator.go
Currently if a `FloatingIP` is assigned to a machine we return an error in all cases, instead of only if an error has been returned by `AssociateFloatingIP()`. This also has the side effect of preventing the machine's annotation being updated with the `FloatingIP`.
=> return AssociateFloatingIP error only if != nil

cloud/openstack/machineactuator.go
There is a bug in the `getIPFromInstance` logic that will return the `Addr` of the first interface instead of iterating over all interfaces and returning a `floating` `Addr` if assigned to the instance.
This patch changes the logic to iterate over all instance networks and interfaces to check for a `floating` `Addr` and returns the first `Addr` only if no `floating` `Addr`'s are found
=> iterate over all instance interfaces

clusterctl/examples/openstack/machines.yaml.template
The current indentation for the example places `floatingIP` under the `networks` block, leading the `floatingIP` to be discarded and therefore not assigned to the machine. This patch fixes the example.
=> Fix indentation for floatingIP in example machines.yaml

cmd/machine-controller/main.go
Prevents glog from complaining about logging before parsing flags
See https://github.com/kubernetes/kubernetes/issues/17162 for more info
```release-note
NONE
```
=> Call Parse() to avoid noisy logs

Makefile
Change-Id: I498589845e36300b05dc4c155cce6660cfa297d2
Fixes issue during build in CI job:
```
go get -u github.com/golang/lint/golint
package github.com/golang/lint/golint: code in directory /home/prow/go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Makefile:82: recipe for target 'lint' failed
```
Fixes #
```release-note
NONE
```
=> golint has moved!

cmd/clusterctl/examples/openstack/machines.yaml.template, config/crd/openstackproviderconfig_v1alpha1.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go
Reference: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/44
Changes: The security_group and availability_zone keys are now lowerCamelCase
=> Make providerConfig keys consistent

README.md, cmd/clusterctl/examples/openstack/machines.yaml.template, cmd/clusterctl/examples/openstack/provider-components.yaml.template
Deployments using v1.10.0 are broken unless `--feature-gates=CustomResourceSubresources=true` is passed to the cluster creation and `.spec.subresources.status` is added to the CRD definition.
Rather than doing that and forcing the use of an older version of k8s, let's take this opportunity to update the minimum required version to the latest available.
More about this here: https://github.com/kubernetes-sigs/cluster-api/issues/533#issuecomment-430127733
/cc @Lion-Wei @chaosaffe
=>  Recommend using v1.12.1

cmd/clusterctl/examples/openstack/provider-components.yaml.template, pkg/cloud/openstack/machineScript.go
Instead of hard-coding bash at the top of the startupScript, we should use the startUpScript as the base template. This will allow us to accept other formats, other than bash, as startUpScripts.
Closes #62
=> Use the startUp script as template

cmd/clusterctl/examples/openstack/machines.yaml.template, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/deployer.go, pkg/cloud/openstack/machineactuator.go
Allow for passing the machine username in the providerConfig. This is
mostly needed by the `clusterctl` command and we should probably find a
better way to get the kubeconfig data. Until then, let's not hardcode
the username in the implementation.
Closes #66
=> Remove hardcoded machine username

config/manager/manager.yaml, pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/machineservice_test.go, pkg/cloud/openstack/machineactuator.go
We were creating our own copy of AuthOptions rather than relying on the
utilities provided by clientconfig. Our copy didn't have all the info
required by gophercloud to authenticate.
Closes #69
=> Let clientconfig create the AuthOptions instance

pkg/cloud/openstack/machineactuator.go
Depending on the arguments passed to kubeadm, it may or may not output
more data to stdout. Since we're shelling out and depending on the
kubeadm cli to generate the token, this commit fixes the token parsing
by splitting the output into lines and getting the very last one.
This is far from ideal, as in we should not be depending on kubeadm to
generate the token. Until that is fixed, this patch seems to be a good
compromise.
Closes #74
=> Get only the last line of the kubeadm token cmd

cmd/clusterctl/examples/openstack/provider-components.yaml.template
Use 443 as the apiserver port until cluster-api allows us to set a
different port instead of hard-coding it:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/64
https://github.com/kubernetes-sigs/cluster-api/issues/559
=> Use 443 until cluster-api is fixed

cmd/clusterctl/examples/openstack/generate-yaml.sh
This patch updates shebang from /bin/sh to /bin/bash of generate-yaml.sh
Fixes #81
=> Fix shabang of generate-yaml.sh

cmd/clusterctl/examples/openstack/generate-yaml.sh
The generate-yaml.sh script breaks when the path to the repository
contains spaces. This commit adds quotes to path variables in the right
spaces to fix it.
This fixes the breakage of spaces being in the path to generate-yaml.sh
Fixes #86 
No
```release-note
NONE
```
=> Support paths with spaces.

cmd/clusterctl/examples/openstack/generate-yaml.sh
Enables users to select which provider os they want to use in the generate-yaml.sh script
Referencing: #88
Special Notes:
:)
=> Let users select provider OS

config/rbac/secrets_role.yaml, config/rbac/secrets_role_binding.yaml
When CAP-OS is deployed to the resulted cluster, it runs in the
namespace openstack-provider-system, and gets the default ServiceAccount
mounted in. Because of #78, CAP-OS needs to create secrets (bootstrap
tokens essentially are secrets) in namespace kube-system.
Created a Role and RoleBinding to allow this.
Using yaml files in config/rbac in favor of kubebuilder auto generation,
because this only works for ClusterRoles so far.
See https://github.com/kubernetes-sigs/kubebuilder/issues/401
Fixes #93
How to test:
```
generate-yaml.sh -c ... -p ubuntu
configure …
```
=> Added Role to kube-system to allow CAP-OS to create secrets

pkg/cloud/openstack/cluster/actuator.go
We should not update the cluster status until the clustergetter is
properly implemented.
=> Don't update the cluster status

pkg/cloud/openstack/machine/instancestatus.go
Fixing a bug that prevents machine Updates from progressing past the machine status decode
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #104 
```release-note
NONE
```
=> Decoding machine status fails during machine Update calls

cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
This PR upgrades the docker version on nodes and makes it same as the master node. We need it because without this change if we generate provider-components.yaml using the current template the docker version on the node is 1.12 vs 18.06.1-ce on master. 
With older docker version there node is not able to come up properly. I tried with ubuntu 18.04 hosts.
```
Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/sys/fs/cgroup" to rootfs "/var/lib/docker/aufs/mnt/" caused "no subsystem for mount"
```
ubuntu 18.04
As kubelet is not able to start calico and kube-proxy pods. 
```
root@openstack-master-bzzf6:/home/ubuntu# kubectl get nodes
NAME                     STATUS     ROLES    AGE    VERSION
openstack-master-bzzf6   Ready …
```
=> Upgrade docker version on node

cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template, cmd/clusterctl/examples/openstack/generate-yaml.sh, cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
This patch adds rudimentary cloud provider support. It reuses the credentials given to generate-yaml.sh.
This changes the following:
* This uses yq to parse clouds.yaml, either the supplied one or the generated one.
* It changes region to region_name in the generated clouds.yaml.
* It embeds the cloud.conf in the provider-components, base64 encoded so that there will be no indentation problems.
* It adds the cloud-provider and cloud-config arguments.
Fixes #65 
```
Add support for cloud.conf. We will now generate and enable a cloud provider for the new cluster.
```
=> Add rudimentary cloud.conf support.

pkg/cloud/openstack/clients/machineservice.go
Ensure the uuids are returned when there is no error finding the
requested networks.
=> Return uuids at getNetworkIDsByFilter

cmd/clusterctl/examples/openstack/generate-yaml.sh
Enforces `OS_CLOUD` being set to ensure the correct cloud.conf is extracted
N/A
N/A
```release-note
NONE
```
=> Explicitly require OS_CLOUD to be set

cmd/clusterctl/.gitignore
Ignores `clusterctl` binary and files created by `clusterctl`
N/A
N/A
```release-note
NONE
```
=> Add clusterctl created files to .gitignore

Makefile
This prevents make from erroring if some part of `$(GOPATH)/src` is a symlink and `$(PWD)` might already be canonical.
```release-note
NONE
```
=> Use realpath for path comparison in Makefile

Gopkg.lock, Gopkg.toml, cmd/clusterctl/examples/openstack/generate-yaml.sh, vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/bug_report.md, vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/feature_request.md, vendor/sigs.k8s.io/cluster-api/Gopkg.lock, vendor/sigs.k8s.io/cluster-api/Gopkg.toml, vendor/sigs.k8s.io/cluster-api/Makefile, vendor/sigs.k8s.io/cluster-api/README.md, vendor/sigs.k8s.io/cluster-api/WORKSPACE, vendor/sigs.k8s.io/cluster-api/config/BUILD.bazel, vendor/sigs.k8s.io/cluster-api/config/default/kustomization.yaml, vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml, vendor/sigs.k8s.io/cluster-api/hack/update-bazel.sh, vendor/sigs.k8s.io/cluster-api/hack/verify-bazel.sh, vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel, vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go, vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go, vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go, vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go, vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Updates [cluster-api](https://github.com/kubernetes-sigs/cluster-api) dependencies to v0.0.0-alpha.4
Fixes #121
This PR changes us from tracking branch `master` on cluster-api to tracking tag `0.0.0-alpha.4`
This has the side effect of changing the image tag we use for the cluster-api controller-manager from `latest` to `0.0.0-alpha.4`
See https://github.com/kubernetes-sigs/cluster-api/pull/635 for more information
```release-note
NONE
```
=> Update cluster api

pkg/cloud/openstack/clients/machineservice.go
Currently after token expires, all further requests to OpenStack API fail because of auth error. With this flag gophercloud will try to recreate token on receiving 401 error from API.
Fixes #132
```release-note
NONE
```
=> Turn on automatic reauth for OpenStack client

Gopkg.lock, config/rbac/rbac_role.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/cluster/actuator.go, pkg/cloud/openstack/machine/actuator.go, pkg/cloud/openstack/types.go, pkg/controller/add_cluster.go, pkg/controller/add_machine.go, pkg/controller/controller.go
Allow for the actuator to gather its configs from a secret.
The config parsing logic is as follows:
- Check if the machine has `CloudsSecret` set. If yes, get the secret, load the cloud from it using the value of `CloudName` (default is "openstack"), and use the credentials of this cloud.
- If `CloudSecret` is not set, check for `clouds.yaml` files in the container and proceed using the standard flow.
Some things to note:
- As of now, if the `OS_CLOUD` env variable is set, and there's a `clouds.yaml` file in the container with a cloud corresponding to `OS_CLOUD`, it'll overwrite the one loaded from the secret.
- The current implementation requires setting `CloudsSecret` on every machine definition. Future patches PRs will allow for setting `CloudsSecret` in the cluster spec too.
Fixes …
=> Conf from secret

cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template
**What this PR does / why we need it**:  Disable ufw on ubuntu 
We don't have access from inside the pod because ufw block the traffic. 
We need to allow external clients such as kubectl and kubelet to access the Kubernets API, so we should disable the firewall or create new iptables rules. 
Fixes #149
=> Disable ufw on ubuntu #149

cmd/clusterctl/examples/openstack/generate-yaml.sh
fix incorrect path description, in future it may corrupt scripting arch.
Fixes #166
=> Fix incorrect debug info after generate-yaml

cmd/clusterctl/examples/openstack/centos/provider-components.yaml.template, cmd/clusterctl/examples/openstack/ubuntu/provider-components.yaml.template, pkg/cloud/openstack/machine/machineScript.go, pkg/cloud/openstack/machine/machineScript_test.go
Some startup scripts do not require the endpoint to be available (because they've got other means of bootstrapping for example) and calling it right now would fail unconditionally.
Instead, this introduces a `GetMasterEndpoint` function that can be called from the template via `"{{ call .GetMasterEndpoint }}` to query the endpoint. Scripts that don't need it will not call this function.
Fixes #163
```release-note
The node startup script will now need to `{{ call .GetMasterEndpoint }}` in the template
to get the value, rather than querying it with `{{ .MasterEndpoint }}`. This lets the scripts
that don't need it be robust against it failing.
```
=> Remove MasterEndpoint string in favour of a function

config/rbac/rbac_role.yaml
Currently when provider tries to update cluster status, it gets error:
```
User "system:serviceaccount:openstack-provider-system:default" cannot update resource clusters/status" in API group "cluster.k8s.io" in the namespace "default"
```
This happens because "status" is separate subresource and access to it must be granted separately.
```release-note
NONE
```
=> Grant provider access to status subresource in clusters

pkg/cloud/openstack/clients/machineservice.go
We ought to use the same yaml package used by clientconfig in order to
marshall/unmarshall Auth structs to/from yaml correctly. Using any other
yaml library will fail to load the auth data from secrets.
=> Use gopkg.in/yaml.v2 for clientconfig objects

pkg/cloud/openstack/machine/actuator.go
Not all the scenarios supported by CAPO require the manager to pull the kubeconfig configs from the nodes. Rather than failing due to missing ssh keys, we should just log the inability to pull the config file and continue with the execution.
This is an interim solution until #174 is resolved. Once #174 is fixed, we'll be able to stop using sshkeys for this entirely.
Related to #175
```release-note
Missing sshkeys won't prevent the actuator's manager from starting
```
=> Don't fail on missing sshkeys

cmd/clusterctl/examples/openstack/centos/worker-user-data.sh
The `CONTROL_PLANE_VERSION` variable is used as package version in current `centos/worker-user-data.sh`.
However, the Machine resource template doesn't have `spec.versions.controlPlane`.
Therefore, generated worker-user-data has incorrect yum install command because the version is an empty string.
This patch fixes this problem by using `KUBELET_VERSION` as with the worker-user-data for Ubuntu.
```release-note
```
=> Fix worker-user-data template for CentOS

pkg/cloud/openstack/machine/actuator.go
In an isolated scenario where only the actuator is being used (no clusterctl or any of the CAPO scripts) the kubelet version may not be required. Pre-built images may come with a pre-installed kubelet or versions could be provided through different means.
This PR removes the check in favor of letting the templates manage/verify they have all the data they need.
=> Don't require kubelet version to be set

config/crd/openstackproviderconfig_v1alpha1.yaml
We support filtering networks by tags and other attributes but we're missing the filter object for networks in the actuator's CRD. This commit fixes that.
=> Add the filter key to the network's CRD entry

cmd/clusterctl/examples/openstack/centos/master-user-data.sh, cmd/clusterctl/examples/openstack/centos/worker-user-data.sh, config/manager/manager.yaml
docker disabled iptables and ip-masq.
only deploy calico.
used hostname -s to avoid .novalocal confusion.
removed ssl cert host mount into manager container, because the manager
container already includes a sane set of certs. And on centos
/etc/ssl/certs only contains a symlink which was not mounted in. So TLS
to openstack api was broken with the host mount.
Fixes #185 
```release-note
```
=> Fixed bootstrapping of CentOS machine

pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
complete the deepcopy functions
Signed-off-by: Alex Yang <yangyang1@zte.com.cn>
Run the following commands in pkg/apis/openstackproviderconfig/v1alpha1 directory:
```bash
$ go run ../../../../vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go -O zz_generated.deepcopy -i ./... -h ../../../../hack/boilerplate.go.txt
$ git diff
diff --git a/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go b/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
index a95e10d..f9cb99f 100644
--- a/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
+++ b/pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
@@ -21,6 +21,7 @@ limitations under the License.
package v1alpha1
import (
+       v1 …
```
=> add UserDataSecret into deepcopy file

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
For the sake of consistency, let's use `corev1.SecretReference` for `CloudsSecrets` too
=> Use corev1.SecretReference for CloudsSecrets too

docs/config.md
Equal signs are unnecessary for header in config.md.
=> Remove unnecessary equal signs

README.md
using --vm-dirver lead to error and
--bootstrap-flags vm-driver=kvm2 works
doc change 
Fixes #
```release-note
None
```
=> Fix --bootstrap-flags vm-driver=kvm2 flag

Makefile, config/rbac/rbac_role_binding.yaml, pkg/cloud/openstack/cluster/actuator.go
Because currently, controller-tools only support this for controllers
that in in namespace "system", I disabled the auto generation in order
to get the controller back into a running state.
Maybe we need to discuss this further, but in a different ticket!?
Fixes #213 
```release-note
```
=> Disabled auto generation of rbac ClusterRoles

config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/networkservice.go
Use dnsNameservers option to configure nameserver for created subnets.
Fixes #215
=> Configure DNS Nameservers for created network

config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go
the openstackproviderspec removed in #193 and
because of missing 'metav1.ObjectMeta' so it failed to
generate the CRD file.
Fixes #217
Fix bug 217
Fixes #
related to #193, not create the crds files correctly at that PR
```release-note
```
=> Make auto generate crds generate openstackproviderspec

pkg/cloud/openstack/clients/secgroupservice.go
This PR fixes index out of range error if managedSecurityGroups is set to true.
**Which issue(s) this PR fixes** 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/225
```release-note 
NONE
```
=> Fix IngexOutOfRange error if managedSecurityGroups:true

pkg/cloud/openstack/clients/machineservice.go
This PR ensures trunk cannot be set if the system doesn't have trunk
support. This will avoid leaving orphan ports when failing to create
the trunk for it.
=> Ensure trunk is not enabled if there is no support

cmd/clusterctl/examples/openstack/README.md, cmd/clusterctl/examples/openstack/machines.yaml.template, docs/config.md
It is required to use security group UUIDs instead of their names at the machine yaml
=> Add information about security group UUID usage

pkg/cloud/openstack/machine/actuator.go
I deleted 2 machines and one is gone.. this log didn't provide which is skipped.
I0315 07:01:55.409478       1 actuator.go:193] Skipped deleting a VM that is already deleted.
Fixes #
```release-note
```
=> Enhance log of VM skip delete

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
Kubeadm 1.14.0 does not support v1alpha3 for anything else than
migrating the config.
See: https://github.com/kubernetes/kubernetes/pull/74025
Fixes #
The resulted config is produced by `kubeadm config migrate`.
```release-note
```
=> Migrated kubeadm config to v1beta1 for kubeadm 1.14

docs/config.md
Port number 443 is hard coded in master-user-data.sh so that 6443 is not needed. This patch removes port number 6443 from security group rules example.
=> Fix security group rules example in docs/config.md

cmd/clusterctl/examples/openstack/machines.yaml.template
so that we can avoid kubernetes/kubernetes#75683
we may need consider backward compatible issue (for 1.12.3 etc), so further fix might be added 
to allow older control pane
refer to #286 for further info
Fixes #
```release-note
```
=> Upgrade kubeadm version

cmd/clusterctl/examples/openstack/machines.yaml.template
SecurityGroupParam
Default template is not correct after changes of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/236
Fixes #265
```release-note
```
cc @iamemilio
=> fix template after change securityGroups from string to SecurityGroupParam

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
encounter issue when kubeadm start as swap is on
so disable swap during start of user-data execution.
Fixes Bug #292
Fixes #
```release-note
```
=> disable swap in master and node

Makefile, cmd/clusterctl/Dockerfile
Create the Dockerfile so that we can build the clusterctl docker image for:
1) Use k8s job/cronjob to create the k8s cluster
2) Integrate with knative to use tekon pipeline for k8s cluster deploy.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/304
```release-note
```
=> add Dockerfile of clusterctl

README.md, cmd/clusterctl/examples/openstack/README.md
Fixes #
Update the document to add coreos support and kustimize package required.
```release-note
```
=> update README to add coreos support and kustomize required

overlays-config/coreos/manager/deployment.yaml, overlays-config/generic/manager/deployment.yaml
PR 319 fixed the deployment configuration file but failed to add kustomize update..
Error: failed to find an object with gvk.Gvk{Group:"apps", Version:"v1beta1", Kind:"Deployment"} to apply the patch
was caused by kustomize function, this is because the kustomize file didn't updated with the main manager file...
Fixes #
```release-note
```
=> Use apps/v1 for deployment apiVersion

Makefile
Fixes #
```release-note
NONE
```
=> MERCURIAL is not need by Makefile.

docs/config.md, pkg/cloud/openstack/machine/actuator.go
timeout is hard code and sometimes it's might be need to wait
for more than 5 min for instance create in some cloud.
Fixes #
```release-note
```
=> Add configuration for create timeout

cmd/clusterctl/examples/openstack/generate-yaml.sh, cmd/clusterctl/examples/openstack/provider-component/clouds-secrets/kustomization.yaml, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/common.yaml, cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh, config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go, pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/cluster/actuator.go
This PR supports keystone endpoint with certificate by the following clouds.yaml with cacert key.
```yaml
clouds:
openstack:
auth:
auth_url: https://yourauthurl:5000/v3
username: foo
password: bar
project_id: foobar123
project_name: foobar
user_domain_name: "Default"
cacert: /path/to/cacertfile
region_name: "Region_1"
interface: "public"
identity_api_version: 3
```
Fixes #209 
```release-note
```
=> Support keystone with certificate

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
when selinux did not enabled, the init-cloud will be failed, so before run command setenforce, need to check if the selinux enabled or not.
Fixes #
```release-note
```
=> init-cloud exit if the selinux did not enabled

pkg/cloud/openstack/clients/secgroupservice.go, pkg/cloud/openstack/cluster/actuator.go
This changes provide security groups removal
during cluster deletion if managedSecurityGroups
is true in clusterSpec.providerSpec
Fixes #227
=> Delete SecurityGroups from cluster

pkg/cloud/openstack/cluster/actuator.go, pkg/cloud/openstack/machine/actuator.go
cluster variable might be be nil due to some configuration error
so this patch adds a check of cluster status before use it
Fixes #317 
```release-note
```
=> Fix cluster nil lead to panic

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go
we are not providing any info about control pane CA key and pem
add those info will be confusing to end user
and seems add private key info into the status is not that secure..
Fixes #333 
```release-note
```
=> Remove CACertificate and CAPrivateKey

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh
without this PR, the test template can not parse the {{.CgrouDriver}} and throws below errors:
```
E0505 13:41:20.202163       1 machineScript.go:67] the erro was: template: masterStartUp:81:36: executing "masterStartUp" at <.CgroupDriver>: can't evaluate field CgroupDriver in type machine.setupParams
E0505 13:41:20.208434       1 actuator.go:385] Machine error hchenxa-master-tx6nn: error creating Openstack instance: template: masterStartUp:81:36: executing "masterStartUp" at <.CgroupDriver>: can't evaluate field CgroupDriver in type machine.setupParams
```
and looks like we do not need to check the cgroup driver as kubeadm will help to do this check, refer https://github.com/kubernetes/kubernetes/pull/64347/files …
=> no need to check the cgroup driver in user data

cmd/clusterctl/Dockerfile, cmd/manager/Dockerfile
Since both kubernetes 1.14 and cluster-api release-0.1 uses golang 1.12, let's move to golang 1.12.5.
Fixes #
This PR needs to re-create images.
```release-note
```
=> Move to golang 1.12.5

cmd/clusterctl/examples/openstack/generate-yaml.sh
below code will exited when the cluster.yaml exists.
```
mkdir -p $PWD/$OUTPUT
cp -n $PWD/cluster.yaml.template $PWD/$OUTPUT/cluster.yaml  >>>>>>>> The return code was 1
cp -n $PWD/machines.yaml.template $PWD/$OUTPUT/machines.yaml 
```
so in order to avoid the file overwrite and keep the updated file of cluster.yaml and machines.yaml, create this PR.
Fixes #
```release-note
```
=> the generate.sh exited when the cluster.yaml exists

cmd/manager/Dockerfile
Change base image to fix security issues.
1) Build image local and docker run works.
2) Push quay.io to do security scan.
3) Same issue has been fixed.
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/115
Fixes #345
Scan result from link below.
https://quay.io/repository/wanghh2000/openstack-cluster-api-controller/manifest/sha256:254ae9a09659f381de4bfb8e988f04a37eb20153657cbf2292fb5a7932148157?tab=vulnerabilities
No version change. …
=> change base image to fix security issue

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/cluster/actuator.go
Fixed handling of verify property from clouds.yaml
**Which issue(s) this PR fixes** :
Fixes #360 
```release-note
NONE
```
=> Fix usage of verify property from clouds.yaml

cmd/manager/main.go, pkg/cloud/openstack/machine/actuator.go, pkg/cloud/openstack/options/options.go
make TokenTTL configurable through CLI
Fixes #370 
```release-note
```
=> make TokenTTL configurable through CLI

Makefile, README.md
Hi Team.
I happen trouble that set `GO111MODULE=on` on my laptop.
This is a potential problem for modern Go developers, so I want to include it in make script.
Fixes #
```release-note
```
=> Set GO111MODULE=off when make build

cmd/clusterctl/examples/openstack/generate-yaml.sh, cmd/clusterctl/examples/openstack/machine-deployment.yaml.template
This PR adds MachineDeployment template as in cluster-api-provider-aws.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/cmd/clusterctl/examples/aws/machine-deployment.yaml.template
Fixes #
```release-note
```
=> Add MachineDeployment template

cmd/clusterctl/main.go
this is different to container (statefulset), it's clusterctl command
that didn't register openstack provider
Fixes #395 
```release-note
```
=> Fix failed to create cluster

docs/trouble_shooting.md
=> Add tip on fixing node xxxx not found

pkg/deployer/deployer.go
by default we are using 443 port ,so let's stick to it
otherwise the master will fail to start 
Fixes #399 
```release-note
```
=> move port from 6443 to 443

cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml, pkg/cloud/openstack/services/userdata/machinescript.go
We had a problem with generate-yaml.sh because yq rejected the invalid YAML.
To work around this we have to make sure the master.yaml is also a valid YAML.
So functions like Indent are no option. One option to solve this would have been
base64Encode, but the problem is that Ignition has no property to specify that the
inline content is base64 encoded. The only would have been `inline: !! binary |`, but
then yq complains that {{ .CaCert | Base64Encode }} is not correctly encoded.
So the solution was to just replace the new lines with \n
Fixes #402
=> fix generate-yaml by escaping newlines

README.md
ssh key is not needed anymore ...
Fixes #
```release-note
```
=> update doc for ssh key creation

cmd/clusterctl/examples/openstack/provider-component/cluster-api/kustomization.yaml
kustomization.yaml: Use patchesStrategicMerge
A previous release of kustomize deprecated "patches:" and the latest
version (v3.0.3) will fail on it.  Replacing this with
"patchesStrategicMerge:" should make this kustomization.yaml continue
to work across kustomize versions.
referred from
https://github.com/kubernetes-sigs/cluster-api/commit/8d4cb92c5c7ffce28750f74a47bbddc10efa8688
Fixes #
```release-note
```
=> Fix kustomize

pkg/cloud/openstack/machine/actuator.go, pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
1) seems we don't need port 22, have no idea why use here
2) when pool not exist, should check and ignore following actions
Fixes #429 
```release-note
```
=> Fix delete pool lead to panic

README.md
=> update doc about delete cluster

docs/trouble_shooting.md
=> Add tips for https cacert

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/worker-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
The PR #421  has some missing code change for ubuntu and centos, 
I created ubuntu correctly but centos has some issue (#391), so modify the code according to
ubuntu changes only 
Fixes #
```release-note
```
=> follow up PR 421 to make ubuntu and centos work

pkg/cloud/openstack/cluster/actuator.go, pkg/cloud/openstack/services/loadbalancer/loadbalancer.go
during cluster deletion, the floating ip created and lb created are not deleted correctly
Fixes #433 
```release-note
```
=> Add delete loadbalancer support

README.md, cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml, cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/worker.yaml
backport those 2 into release 0.1
Fix clouds.yaml link and add some notes (#440)
fixed quotes in coreos userdata (#441) 
Fixes #
```release-note
```
=> Backport changes from master to release-0.1

README.md
=> Update doc about release-0.1 and master branch

pkg/cloud/openstack/machine/actuator.go, pkg/cloud/openstack/services/loadbalancer/loadbalancer.go, pkg/cloud/openstack/services/networking/floatingip.go
This PR creates machine floating ips if they don't exist. Depending on the interpretation fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/427 :)
Floating IP handling is now consistent. LoadBalancer & machine floating ip's are both created if they don't already exist. If they already exist they are just associated.
Fixes #427
=> Pr create floating ip on demand

pkg/cloud/openstack/services/userdata/kubeadm.go
Fixes the problem with empty value in imageRepository. I didn't get this before because I never tried CoreOS with the default imageRepository. Also replaces the other default values with the corresponding constants
=> fix empty default values if imageRepository is not set

examples/provider-components/manager_tolerations_patch.yaml
fix following error:
when 
./generate.sh clouds.yaml openstack output1
Error: no matches for OriginalId apps_v1_Deployment|cluster-api-system|cluster-api-controller-manager; no matches for CurrentId apps_v1_Deployment|cluster-api-system|cluster-api-controller-manager; failed to find unique target for patch apps_v1_Deployment|cluster-api-controller-manager
Fixes #
```release-note
```
=> Fix generation issue

controllers/openstackcluster_controller.go, examples/cluster/cluster.yaml
The kustomize will remove the # comments ... so no one knows the info provided
and even if we some one failed to set the failure, we should not let container panic ...
so I added a default value here
Fixes #
```release-note
```
=> Fix api port

cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/worker-user-data.sh
#436 
> What I felt is when any sudo commands run from master-user-data.sh, it hangs for a bit and then proceeds. If we can map loopback-ip to the hostname in /etc/hosts (can add command in master-user-data file), it would not get stuck.
=> Hostname missing in /etc/hosts file in openstack instance

Dockerfile, Makefile, README.md, config/default/manager_image_patch.yaml, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, examples/controlplane/controlplane.yaml, examples/generate.sh, examples/machinedeployment/machinedeployment.yaml, go.sum, pkg/cloud/services/provider/provider.go
Final fixes for v1alpha2. This has been tested with:
=> Pr finalize v1alpha2

cloudbuild.yaml, examples/generate.sh
Blocked by: https://github.com/kubernetes/k8s.io/pull/351
=> Add release process for staging images

pkg/cloud/services/compute/instance.go
Before triggering the creation of a new Instance in OpenStack, Network
filters are used to fetch actual NetworkIDs from OpenStack.
Before this change, if no OpenShift network was found based on the
filters, the Instance spec was sent to OpenStack with an empty Network
segment, resulting in an error.
With this change, Create returns an error to the caller if no matching
networks are found in Openstack.
A Machine definition with an invalid Network section is currently converted for OpenStack to an Instance definition with an empty Network section, resulting in a `Bad Request` with error message `'networks' is a required property`.
```
spec:
providerSpec:
value:
networks:
- filter: {}
subnets:
- filter:
name: cluster-nodes
tags: …
```
=> Stop Instance creation on invalid Network spec

Makefile, main.go
Running several Cluster API pods (e.g. CAPI + CABPK + an infra provider)
in the same namespace results in leader election errors.
This PR added the leader election ID.
Fixes #
```release-note
```
=> LeaderElectionID should be unique

Makefile, api/v1alpha2/openstackcluster_types.go, api/v1alpha2/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, controllers/openstackcluster_controller.go, examples/controlplane/controlplane.yaml, examples/machinedeployment/machinedeployment.yaml, pkg/cloud/services/compute/instance.go, pkg/cloud/services/networking/router.go
Ups, deleted the old branch so the old PR was closed. So again:
Okay I tested my existing multi-node setup and I tested it with remove networks filter. Both worked
@jichenjc Can you test if you're now able to use loadbalancers by setting the network and subnet fields (filters) in the ClusterSpec?
Edit: Old PR was this one: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/475
=> Pr use existing networks

cmd/clusterctl/examples/openstack/provider-component/user-data/centos/templates/master-user-data.sh, cmd/clusterctl/examples/openstack/provider-component/user-data/coreos/templates/master.yaml, cmd/clusterctl/examples/openstack/provider-component/user-data/ubuntu/templates/master-user-data.sh
The version of existing calico is incompatible
with kubenetes 1.13.x, 1.14.x and 1.15.x.
So it needs to be updated.
Fixes #481
NONE
=> update calico version to v3.8 (#481)

go.mod
Resolves issue with date parsing in `Ocata`. See #485 for more details
Fixes #485 
```release-note
NONE
```
=> Upgrade gophercloud to v0.4.0

.gitignore, Makefile, RELEASE.md, config/default/kustomization.yaml, config/default/manager_image_patch.yaml, config/default/manager_pull_policy.yaml, config/manager/manager.yaml, docs/getting-started.md, examples/cluster/multi-node/cluster.yaml, examples/cluster/single-node/cluster.yaml, examples/controlplane/multi-node/controlplane.yaml, examples/controlplane/single-node/controlplane.yaml, examples/machinedeployment/machinedeployment.yaml, go.sum
Finalizes doc & examples for v0.2.0
See also https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/480
=> finalize doc & examples for v0.2.0

Makefile
Our generate example tests are currently broken because yq couldn't be go-get'ed anymore. This PR fixes it :)
=> fix generate example tests

docs/getting-started.md
fix #493
create a k8s cluster with 1 master node and 1 worker node, then manually delete this cluster according to doc here , but it doesn't work, this is due to no label like set=node and set=master on the Machine resource.
Fixes #493
None
=> enhance doc regarding to manually delete cluster

api/v1alpha2/openstackcluster_types.go
I am working on my env and noticed that the new VM is not able to
start because my VM can't talk to openstack URL (which is web URI
instead of IP), so we need guide user to create this DNS explicility.
Fixes #
```release-note
```
=> Add additional description for DNS

.golangci.yml, pkg/cloud/services/compute/instance.go
The set of machine tags needs to be de-duplicated prior to applying tags on a machine or the Openstack API call will fail.
Fixes #501
=> :bug: deduplicate machine tags prior to openstack API apply call

pkg/cloud/services/provider/provider.go
Before this PR it was mandatory to set a cacert. Without it the cloud.yaml was not parsed correctly.
Bug was identified here: https://kubernetes.slack.com/archives/CFKJB65G9/p1579624001004800?thread_ts=1579502983.003200&cid=CFKJB65G9
=> 🐛 don't require cacert in cloud.yaml

config/manager/manager.yaml, main.go
Similar was made here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1487 and https://github.com/kubernetes-sigs/cluster-api/pull/2156 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/374
Adding the liveness and readiness probes
Fixes #
```release-note
- health: add liveness and readiness probes
```
/cc @vincepri
=> ✨health: add liveness and readiness probes

docs/getting-started.md
image builder is good but we may tip folks to use other potential
easier way (learning curve perspective) to build an image.
Fixes #
```release-note
```
=> Add alternative to OS image

docs/development.md
Follow up 0.2.0.
Fixes #
```release-note
```
=> 📖 Fix development.md

controllers/openstackmachine_controller.go
This PR fixes PROVIDERID to start with openstack://, not openstack:////.
Fixes #511 
```release-note
```
=> 🐛 Fix PROVIDERID

RELEASE.md, templates/cluster-template-without-lb.yaml, templates/cluster-template.yaml
I just did a final manual test and saw that the quickstart with 0.3.0 only worked when --target-namespace was equal to the cluster-name. This PRs fixes our templates so that the namespace where all resources are deployed is equal to our secret references in the CAPO resources
P.S. I already replaced the uploaded cluster-templates in the published 0.3.0 release to avoid that somebody who is trying CAPO out right now directly fails with this error, which would be bad :)
=> ⚠️ fixup namespace handling in 0.3.0

api/v1alpha3/openstackmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, pkg/cloud/services/compute/instance.go
With this change, it is possible to assign a machine to an [OpenStack
Server group][1]. By passing a server group ID to the Machine Spec, it
is possible to leverage affinity policies and control how machines are
distributed across physical hosts.
[1]: https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/server-group.html
```release-note
OpenStackMachineSpec: add ServerGroupID property for assigning a Nova Server Group
```
=> ✨ Add ServerGroupID to OpenStackMachineSpec

controllers/openstackcluster_controller.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go
This PR adds to delete router, network, and subnet feature. Currently how to delete cluster is not provided explicitly in my understanding, but we need to delete OpenStack resources easily even for testing. By this PR, we can delete OpenStack resources created with `cluster-template-without-lb.yaml` by the following.
```
kubectl delete machinedeployment capi-quickstart-md-0 -n capi-quickstart
kubectl delete kubeadmcontrolplane capi-quickstart-control-plane -n capi-quickstart
kubectl delete cluster capi-quickstart -n capi-quickstart
```
Fixes #
1. Please …
=> ✨ Delete router/network/subnet

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/provider/provider.go
This PR fixes to issues:
* When using an admin user it wasn't possible to assign security groups to machines because the security group list call returned sec groups from all projects, now it's filtered to the current one
* When reconciling load balancer there was an issue when the lb was still "pending create" from the last reconcile. Now the controller also waits even when the lb already exists from before.
=> 🐛  use sec groups from the current project, wait for lb from last reconcile

pkg/cloud/services/networking/securitygroups.go, templates/cluster-template.yaml
This PR updates cluster-template.yaml to work.
OpenStack environment needs the followings.
- Port security feature to use OpenStack Octavia with HAProxy Amphora.
- Appropriate security groups to master and worker nodes.
Fixes #
```release-note
```
=> 🐛 Fix cluster-template.yaml

Makefile
Updated to cluster-api v0.3.3 in #532 which was imcomplete.
This PR update to  cluster-api v0.3.3 in Makefile.
Fixes #
```release-note
```
=> 🐛 Fix updating to Cluster API v0.3.3

Makefile, scripts/ci-build.sh, scripts/ci-test.sh
Add build scripts similar to CAPA (old Prow targets in Makefile (images & check) will be removed in a follow up PR
=> 🏃 Pr add prow test scripts

scripts/ci-build.sh
I would suggest removing the docker-build from the test target so we don't need docker-in-docker in Prow. We're testing the docker build in OpenLab anyway in our e2e test
=> 🐛 remove docker-build from build test

hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Not sure why but looks like they removed the bin folder in the build output. So we're using the -bazel folder for now:
https://console.cloud.google.com/storage/browser/kubernetes-release-dev/ci/v1.19.0-alpha.1.254+4a897137b6b6dc-bazel/
(our periodic job is failing because of that: http://status.openlabtesting.org/builds?project=kubernetes-sigs%2Fcluster-api-provider-openstack)
=> 🐛  e2e test: switch to -bazel folder because bin folder has been removed

pkg/cloud/services/provider/provider.go
it took me long time to find when I define the wrong cloud different to clouds.yaml 
in make file... I got err like `'auth_url' input can't be empty` which is really confusing
add this will be much helpful ..
Fixes #
```release-note
```
=> Add additional info when error occur

api/v1alpha3/openstackcluster_types.go, api/v1alpha3/types.go, api/v1alpha3/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, controllers/openstackcluster_controller.go, docs/configuration.md, pkg/cloud/services/networking/securitygroups.go, templates/cluster-template.yaml
This PR updates generate security groups to follow kubeadm install documentation.
Fixes #553 
```release-note
Fixed generate security groups to follow kubeadm install documentation for using NodePort services.
```
=> 🐛 Fix auto generate security groups

templates/cluster-template.yaml
It is not good practice that ssh to controller nodes via API Server load balancer.
This PR removes APILoadBalancerAdditionalPorts.
Fixes #
```release-note
```
=> Remove APIServerLoadBalancerAdditionalPorts

pkg/cloud/services/compute/instance.go, templates/cluster-template.yaml
Currently generate security groups are not added to the instances.
This commit makes it automatically.
Currently generate security groups are not added to the instances if managedSecurityGroups: true.
This PR makes generate security groups to be added automatically.
Fixes #556 
```release-note
Makes generate security groups to be added automatically if managedSecurityGroups: true
```
=> Add generated security groups automatically

Makefile
MTU size 1430 is enough due to [Calico MTU with IP-in-IP (IPv4)](https://docs.projectcalico.org/networking/mtu#determine-mtu-size). This PR comes from [the discussion](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/595#discussion_r459196081).
Fixes #
```release-note
```
=> 🐛Update mtu size in Makefile

api/v1alpha3/openstackcluster_types.go, api/v1alpha3/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, templates/cluster-template.yaml
This PR finds external network and create floating ip if `externalNetworkId`, `apiServerLoadBalancerFloatingIP`, and
`apiServerLoadBalancerPort` are not given when `managedAPIServerLoadBalancer: true`.
When `managedAPIServerLoadBalancer: false`, this PR also works without `controlPlaneEndpoint` and `floatingIP` in the manifest.
Fixes #566 
```release-note
Add external network discovery
```
=> ✨Add external network discovery

Makefile, hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
#613 was incomplete. The PR removed preKubeadmCommands at all. By #613, Image version actually becomes official version, but binaries(kubeadm, kubectl, and kubelet) are not updated. This PR fixes to update binaries version by preKubeadmCommands.
Fixes #612 
```release-note
```
=> 🐛 Fix e2e test Kubernetes official binaries version

docs/external-cloud-provider.md
The link goes one folder up too much causing the reference link to be broken.
The link goes one folder up too much causing the reference link to be broken.
1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes. 
No, this changes only the documentation.
=> 📖 Fix Link for external openstack template

hack/ci/e2e-conformance/e2e-conformance_patch.yaml.tpl
Currently master node wget kubernetes binary logs quiet, but worker is not quiet. This PR makes wget kubernetes binary be quiet as master does.
Fixes #
```release-note
```
=> CI: Wget kubernetes binary be quiet

main.go
make reconcile handle maximum concurrent handling machines to 10
as default 1 will handle machine one by one
note I didn't update concurrent cluster handle as it might need further test
Fixes #
```release-note
```
=> default concurrent reconcile from 1 to 10

templates/cluster-template-external-cloud-provider.yaml, templates/cluster-template-without-lb.yaml, templates/cluster-template.yaml
Fixes #626 
with this , latest clusterctl should be able to force move secret we created in CAPO
```
commit 0e886b905a67c68b5bce3f249aaff13079affeeb (origin/bug/3603, bug/3603)
Author: jichenjc <jichenjc@cn.ibm.com>
Date:   Thu Sep 10 02:59:08 2020 +0000
Add force move support for object
```
```release-note
```
=> Add force move of secret cloud config

docs/configuration.md
:book:
Added machine flavor under required configuration
In the current configuration document, machines flavors related configuration is not mentioned even though 
these are mandatory parameters.
Added machine flavors in the documentation
=> Update configuration document

docs/configuration.md, docs/mover.md
Add a doc on how to move a cluster
Fixes #
```release-note
```
=> Add doc for how to move a cluster

controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go
We need floating IP address status when non HA cluster deployed for implementing #621 .
Fixes #
```release-note
```
=> Add openStackMachine.Status.Addresses value

docs/external-cloud-provider.md
:book: Updated calico version in external-cloud-provider documentation
Calico version mentioned in the document is 2 releases old. Updated the same in the document.
```release-note
None
```
=> 📖 Update calico version in documentation

controllers/openstackcluster_controller.go
✨ 
**What this PR does / why we need it**: 
To correct  the previous #594swapping ifs precedence for error check after
https://github.com/pramchan/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L300
to...
if err != nil {
return errors.Errorf("failed to find network: %v", err)
}
if len(networkList) == 0 {
return errors.Errorf("failed to find any network: %v", err)
}
if len(networkList) > 1 {
return errors.Errorf("failed to find only one network (result: %v): %v", networkList, err)
}
openStackCluster.Status.Network = &infrav1.Network{
ID: networkList[0].ID,
Name: networkList[0].Name,
}
**Which issue(s) this PR fixes** *:
Fixes #590 , #594
the way I did it is 
git log --oneline
c528adda (HEAD -> my594) revised #590 …
=>  ✨ My594 revised #590 #594 wrong parameter for a user provider network

templates/cluster-template-without-lb.yaml
This commit deletes spec.kubeadmConfigSpec.ntp.servers of KubeadmControlPlane resource in cluster-template-without-lb.yaml.
Other templates(HA version and external version) do not have spec.kubeadmConfigSpec.ntp.servers.
Fixes #
```release-note
```
=> 🏃 Delete spec.kubeadmConfigSpec.ntp.servers in cluster-template-without-lb.yaml

api/v1alpha3/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, docs/configuration.md, pkg/cloud/services/networking/floatingip.go
This PR deletes floating IP when deleting cluster if it is automatically created by CAPO.
`APIServerLoadBalancerFloatingIP` and `APIServerLoadBalancerPort` are now deprecated.
Both Non HA and HA uses common parameters to set openStackCluster.Spec.ControlPlaneEndpoint.
- APIServerFloatingIP
- APIServerPort
Fixes #621 
```release-note
Delete automatically created floating IP when deleting cluster
Introduced `APIServerFloatingIP` and …
```
=> ✨ Delete automatically created floating IP when deleting cluster

Makefile, clusterctl-settings.json
Fixes #651 
```release-note
```
=> 🐛 Update reference to the latest version of CAPO v0.3.1

docs/configuration.md
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
:book: 
**What this PR does / why we need it**: fix location for env.rc script at documentatin
**Special notes for your reviewer**: nothing
=> fix location for env.rc file

controllers/openstackmachine_controller.go
When deleting highly available k8s cluster with automatically created floating IPs, floating IPs not related to k8s cluster are also deleted.
This PR fixes to delete only automatically created floating IPs.
Fixes #668 
```release-note
```
=> 🐛 Fix to delete only automatically created floating IPs

.gitignore, docs/development.md, tilt-provider.json
Fixes #649 
```release-note
```
=> ✨ Add support for Tilt

docs/external-cloud-provider.md
Update to use clusterctl get kubeconfig which is available in clusterctl v0.3.9 or newer.
Fixes #
```release-note
```
=> 📖  Update how to retrieve kubeconfig

controllers/openstackmachine_controller.go
keep seeing 
```
I1113 00:24:14.043296       1 openstackmachine_controller.go:291] controllers/OpenStackMachine "msg"="Creating Machine" "cluster"="capi-openstack-3" "machine"="capi-openstack-control-plane-d2fnl" "namespace"="default" "openStackCluster"="capi-openstack-3" "openStackMachine"="capi-openstack-control-plane-rthx6"
```
but actually it's not creating .. it's getOrCreate, so the log is confusing
Fixes #
```release-note
```
=> Move log to creating place

README.md
Add openstack ussuri into support list (tested)
Fixes #
```release-note
```
=> Add openstack ussuri into support list

config/manager/manager.yaml, config/manager/manager_auth_proxy_patch.yaml, config/webhook/manager_webhook_patch.yaml, main.go
This changes the name of following flags to allign with k8s upstream.
1. `--metrics-addr` to `--metrics-bind-addr`
2. `leader-election` to `leader-elect`
Fixes #689 
```release-note
```
=> ✨ Align flag names with upstream Kubernetes components

templates/cluster-template-external-cloud-provider.yaml
Spec.disableServerTags of OpenStackCluster is deleted in e58572d3ec46a8a9767e98ef9b8cd223d7dfaf09. But cluster-template-external-cloud-provider.yaml was missed. This PR deletes it.
Fixes #691 
```release-note
```
=> 🐛 Delete spec.disableServerTags of OpenStackCluster

docs/troubleshooting.md
Since capo-controller has two containers, kubectl logs needs -c option.
Fixes #
```release-note
```
=> 📖 fix getting log

pkg/cloud/services/compute/instance.go
This PR deletes port when an instance creation is not executed such as cpu quota error.
Fixes #701 
```release-note
```
=> 🐛 Fix SecurityGroupInUse error

templates/env.rc
Currently, _domain_name_ and _domain_id_ are being ignored when getting the OpenStack credentials from clouds.yaml.
Fixes #713 
```release-note
NONE
```
=> :bug: Fix domain_name and domain_id usage in env.rc

Makefile
the v0.3.1 is confusing ,we should update to latest version
Fixes #
```release-note
```
=> move from 0.3.1 to 0.3.3 in the CI test

templates/env.rc
When using cacert in cloud.yaml, the local CA certificate path is set also in the OpenStack VM's /etc/kubernetes/cloud.conf, while the certificate is always copied in /etc/certs/cacert
This issue causes the deployment to fail as the certificate file cannot be found in the VM.
Fixes #715
```release-note
NONE
```
=> Fix ca-file path in env.rc

docs/configuration.md
Currently the capi quick-start only refers to generating config for default template. This PR adds instructions on how to use `without-lb` cluster-template.
Fixes #
```release-note
```
=> 📖 Add instructions to use cluster template with load-balancer

config/manager/manager.yaml
add --metrics-bind-addr=127.0.0.1:8080 so that capo can report metrics info
this previously exist and removed somehow..
Fixes #
```release-note
```
=> Specify --metrics-bind-addr for CAPO manager

config/manager/manager.yaml
This reverts commit 8f51aa22db22e0b5f53b7cb7aa28bae9d6ce8fea.
Because `--metrics-bind-addr=127.0.0.1:8080` is added by patches:
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/manager/manager_auth_proxy_patch.yaml#L24
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/config/webhook/manager_webhook_patch.yaml#L12
Actually we can get the same result using `kustomize build` under `config` directory.
Fixes #
1. Please confirm that if this PR changes any image versions, then that's the sole …
=> 🏃 Revert Merge pull request #725

Makefile
This PR passes the GOPROXY environment variable to the Docker image build.
It was introduced with https://github.com/kubernetes-sigs/cluster-api/pull/3061 but most likely forgotten for `cluster-api-provider-openstack`.
> Sometimes, using a custom GOPROXY can speed up the build.
Fixes #
```release-note
NONE
```
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> 🐛  Pass GOPROXY environment variable to Docker image build

pkg/cloud/services/loadbalancer/loadbalancer.go
Currently subnet argument is given when creating load balancer member. it causes error.
This PR removes subnet argument so that LBaaS uses the vip_subnet_id parameter value for the subnet UUID
Fixes #738 
We follow [Deploy a basic HTTP load balancer using a floating IP](https://docs.openstack.org/octavia/latest/user/guides/basic-cookbook.html#deploy-a-basic-http-load-balancer-using-a-floating-ip) model. The subnet for lb members equals to vip_subnet_id in this case.
1. Please confirm that if this PR changes any image versions, then that's the sole change this …
=> Fix LoadBalancerMember creation

pkg/cloud/services/loadbalancer/loadbalancer.go
Fixes #754
I'm not sure this is the correct way to solve this, but fixed the problem for us
```release-note
You can use a FQDN in `openStackCluster.Spec.ControlPlaneEndpoint.Host`
```
=> 🐛 use APIServerFloatingIP instead of ControlPlaneEndpoint.Host for LB

api/v1alpha3/openstackmachine_types.go, api/v1alpha3/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, pkg/cloud/services/compute/instance.go
Currently, when we want to use multiple networks, the IP address is assigned basically randomly, this PR adds the ability to specify from which subnet the IP address will be obtained.
none
This is the minimal amount of changes I found to achieve the goal of getting IP address from the correct CIDR.
```release-note
Added the ability to specify source subnet of compute instance access IP address
```
=> :sparkles: AccessSubnetUUID: we can specify source subnet for access IP address

.github/PULL_REQUEST_TEMPLATE.md
Adjust the pull request template to use /hold per default. Goal is just to avoid accidental instant merges on-/hold. We can always deliberately remove the hold if we really want to merge instantly :).
/hold
=> 🏃 Update pull request template to use /hold per default

OWNERS, OWNERS_ALIASES
Currently most approvers and reviewers in OWNERS files do not review even if they are assigned as reviewers. For reviewer assignment work, we need to update OWNERS files.
- Update members of sig-cluster-lifecycle-leads, cluster-api-admins, and cluster-api-maintainers.
- Move inactive members of cluster-api-openstack-maintainers, and cluster-api-openstack-reviewers to emeritus.
- Add @hidekazuna to cluster-api-openstack-maintainers.
- Add @prankul88 to cluster-api-openstack-reviewers.
Fixes #
1. Please confirm that if this PR changes any image versions, then …
=> 🏃 Update OWNERS files

Dockerfile
Fixes #760
```release-note
```
/hold
=> 🐛Remove start.sh and restart.sh

docs/configuration.md
This PR updates configuration document to follow up #757 . The PR changed API related to bastion.
Fixes #
```release-note
```
/hold
=> 📖  Update configuration doc

pkg/cloud/services/networking/securitygroups.go
Reimplements the security group reconcilation by only creating and/or
deleting the rules desired / not desired instead of deleting all and creating all rules.
Fixes #771 
```release-note
```
/hold
=> ✨ pkg/cloud/services/networking/securitygroups.go reimplement reconcilation

.github/PULL_REQUEST_TEMPLATE.md
I saw that in CAPZ and I like it. Especially as a reminder to squash commits before merge
Example: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1239
/hold
=> 🏃 Add todos to PR template

.golangci.yml, api/v1alpha3/conversion.go, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, controllers/suite_test.go, main.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/service.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/service.go, pkg/cloud/services/provider/provider.go
This PR sorts the imports in the order stdlib, 3rd-party, local and adds the local-prefix to the linter settings.
Fixes #790
**TODOs**:
```release-note
NONE
```
/hold
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> 🏃 goimports: fix import order, add local-prefix to linter

templates/cluster-template-external-cloud-provider.yaml, templates/cluster-template-without-lb.yaml, templates/cluster-template.yaml
This PR removes disablePortSecurity: false from template files. Because disablePortSecurity is false by default.
Fixes #
**TODOs**:
```release-note
```
/hold
=> 🏃 Remove disablePortSecurity: false from template

templates/cluster-template-without-lb.yaml
This PR removes useOctavia from nonha template. Because nonha template does not create load balancer, useOctavia is not used.
Fixes #
**TODOs**:
```release-note
```
/hold
=> 🏃 Remove useOctavia from nonha template

Makefile
The conversion-gen command has an --output-base argument to control
where generated files are placed. The default value for this argument
can vary depending on whether or not $GOPATH is set or not. This results
in our generated files being created in the wrong place for some people
in a subtle and non-obvious way.
For those running `make generate` with GOPATH set, the files are created
in `$GOPATH/src/[file path]`. For those without GOPATH set, files are
created where we expect them to be within the repo at `./[file path]`.
To make sure files are always generated to the location where we expect
them to be, this updates our calls to conversion-gen to always be
explicit when not within GOPATH by setting  `--output-base=[repo_path]`.
**Which issue(s) …
=> 🐛  Make conversion-gen output location explicit

pkg/cloud/services/compute/instance.go
The server list api defines the name parameter to be a regular
expression:
https://docs.openstack.org/api-ref/compute/?expanded=list-servers-detail#list-servers
This meant that the usage of it in InstanceExists was a
substring lookup rather than the intended lookup by name.
This is an 'upstream port' of the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1747270
=> 🐛 InstanceExists should not do substring search on name

.github/PULL_REQUEST_TEMPLATE.md
We don't actually use this data. It's for tooling of the main Kubernetes project we don't use in CAPO. We only 
rely on PR title and icon.
/hold
=> 🏃 Remove unused release note section in the PR template

cloudbuild.yaml
The job which pushes images post-merge has been broken: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-openstack-push-images/1375280030887710720
This PR upgrades the image to the latest build image available. This changes the go version from 1.12 to 1.13.
Imho this is not ideal but might already fix the job. I'll try to figure out via an issue in the cluster-api Repo if we should bump the go version in this image to 1.16
/hold
=> 🐛 fix post-cluster-api-provider-openstack-push-images

Makefile, hack/image-patch/kustomization.yaml, hack/image-patch/pull-policy-patch.yaml, hack/tools/go.mod, hack/tools/go.sum, hack/tools/tools.go
Follow-up to: #809
This fixes our image push on post-submit (hopefully I tested it locally this time).
It also publishes respective manifests to: https://console.cloud.google.com/storage/browser/artifacts.k8s-staging-capi-openstack.appspot.com;tab=objects?forceOnBucketsSortingFiltering=false&project=k8s-staging-capi-openstack&prefix=&forceOnObjectsSortingFiltering=false
Those should then be available similar to CAPA via:
https://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/components/<tag>/infrastructure-components.yaml
/hold
=> fix post-cluster-api-provider-openstack-push-images and add post-submit manifests

.golangci.yml, Makefile, controllers/openstackcluster_controller.go, go.mod, hack/ci/devstack-cloud-init.yaml.tpl, hack/ci/devstack-on-gce-project-install.sh, main.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/networking/service.go, scripts/ci-e2e.sh, test/e2e/data/ccm/cloud-controller-manager.yaml, test/e2e/data/ci-artifacts-platform-kustomization.yaml, test/e2e/data/e2e_conf.yaml, test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml, test/e2e/shared/cluster.go, test/e2e/shared/common.go, test/e2e/shared/context.go, test/e2e/shared/defaults.go, test/e2e/shared/exec.go, test/e2e/shared/exec_test.go, test/e2e/shared/openstack.go, test/e2e/shared/openstack_test.go, test/e2e/shared/suite.go, test/e2e/suites/conformance/conformance_test.go, test/e2e/suites/e2e/e2e_suite_test.go, test/e2e/suites/e2e/e2e_test.go
This PR adds e2e tests for all our flavors (and some additional ones).
Fixes #577
Fixes #723
Fixes #741
Notes:
This PR can also be reviewed but won't be merged before the test framework and the linter PR and also contains those commits/PRs
/hold
=> 🏃 Add e2e tests for all flavors

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go
This PR follows up #817, reorder function variables follows https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/817#issuecomment-810763684
Fixes #
**TODOs**:
/hold
=> 🏃 Reorder function variables

Makefile
Nightly and postsubmit artifacts are currently uploaded to:
* https://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/components/nightly_master_20210403
this should actually be, e.g.:
* https://storage.googleapis.com/artifacts.k8s-staging-capi-openstack.appspot.com/components/nightly_master_20210403/infrastructure-components.yaml
Fixes #
**TODOs**:
/hold
=> 🐛 fix path of uploaded artifacts

docs/mover.md, pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/service.go, pkg/cloud/services/networking/floatingip.go, test/e2e/suites/e2e/e2e_test.go
Overall this PR only refactors code to clean up some parts.
* This PR fixes the notation for load balancer related logs. The split notation `load balancer` is used.
* Also this PR restructures the `GetOrCreateFloatingIP` function for easier readability and removes a possible nil reference in the log line.
* This PR also renames some variables that shadowed imported package names.
**TODOs**:
/hold
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> 🏃 Refactor/cleanup load balancer related code

pkg/cloud/services/provider/provider.go
This PR stops propagating the `cloud` field to `clientconfig.AuthOptions`. If this field is actually set, we hit a branch in `AuthOptions` which always fails: (I don't think we have to validate that the field is not set, when we can just change the code that it doesn't matter if it is set or not)
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/31df024b3205232c3545631afb5027f1f0a3f213/pkg/cloud/services/provider/provider.go#L80-L91
https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L352-L370
https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L192 …
=> 🐛 do not propagate the cloud field to clientconfig.AuthOptions

scripts/ci-e2e.sh
Adds a copy of the conformance tests as e2e tests. This means that in place of the e2e tests the conformance tests are required for merge. I think this is a valid workaround to be able to merge PRs again on the release branch and have some test coverage there. I think it wouldn't be worth it to cherry-pick all our e2e tests to the release branch.
Fixes #
**TODOs**:
/hold
=> 🏃 Pr add e2e tests

docs/book/src/clusteropenstack/configuration.md, test/e2e/data/e2e_conf.yaml
Bump e2e tests to latest k/k release. There are some reports which suggest there might be an issue with kubeadm join.
xref:
* https://github.com/kubernetes/kubeadm/issues/2450
* https://kubernetes.slack.com/archives/C8TSNPY4T/p1618848917097800
Fixes #
**TODOs**:
- [] includes documentation
- [] adds unit tests
/hold
=> bump tests to Kubernetes 1.20.6

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go
This PR fixes deleting cluster and machines.
- We can not delete OpenStack network resources just after resources are created.
- We can not delete machine before assigning provider ID.
Fixes #841 
**TODOs**:
/hold
=> Delete watching Status when deleting

api/v1alpha3/openstackmachine_types.go, api/v1alpha4/openstackmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
=> set image param as optional for boot from volume

pkg/cloud/services/compute/instance.go
Waiting for instance deletion is implemented by commit e10835fe7cdc1670e49904f575eafbc519f88f4f, but it has a bug and always timeout.
Because `GetInstance` returns `nil ,nil` if `capoerrors.IsNotFound(err)` is `true`, we never go into `if capoerrors.IsNotFound(err)` statement in `PollImediate`. This PR fixes it.
Fixes #
**TODOs**:
/hold
=> 🐛 Fix polling deleting instance

pkg/cloud/services/loadbalancer/loadbalancer.go
Adjusts the wait.Backoff definition which is used in `waitForLoadBalancerActive` and `waitForListener`.
With the current implementation the controller waits 30s also for tasks which are pretty fast like adding a load balancer member.
The old values did result in:
* executing the wait function up to 10 times
* having a maximum of 9 sleeps with 30s each
* in worst case sleep for `9*30s = 270s`
The new values result in a exponential backoff:
* executing the wait function up to 20 times
* having a maximum of 19 sleeps, which vary between 1s to a maximum of ~55s 
* in worst case sleep for ~`273s`
<details>
1 sleep=1.000000 sum=1.000000
2 sleep=1.250000 sum=2.250000
3 sleep=1.562500 sum=3.812500
4 sleep=1.953125 sum=5.765625
5 sleep=2.441406 sum=8.207031 …
=> ✨ adjust loadbalancer wait.Backoff

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/provider/provider.go
This PR enables the gophercloud request logs when setting the log level to `6` with `--v=6`.
In addition, some contexts are fixed.
Fixes #854. 
**TODOs**:
- ~~[ ] includes documentation~~
- ~~[ ] adds unit tests~~
/hold
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> ✨ Add gophercloud request logs, fix contexts

controllers/openstackmachine_controller.go, pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go
Add events
- Delete attachinterface, trunk, and port
- Create port and trunk
- Replace all attributestags
Fixes #
**TODOs**:
/hold
=> 🏃 Add some events and refactor related to instance

pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go
This PR refactored to use gophercloud clients and logger in Service struct instead of function argument.
We can easily log something using `s.logger` without adding logger to function argument.
Fixes #
**TODOs**:
/hold
=> 🏃 Refactor: use Service struct field more

api/v1alpha4/openstackmachinetemplate_webhook.go, api/v1alpha4/openstackmachinetemplate_webhook_test.go
Signed-off-by: Johannes Frey <johannes.frey@daimler.com>
This PR blocks changes to `OpenStackMachineTemplate.Spec.Template.Spec` and provides a message that a new resource should be created if the user does try to mutate it.
Credits where credit's due. This is mainly copy-pasted from https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1275 :slightly_smiling_face:.
Fixes #858
**TODOs**:
/hold
<sub>Johannes Frey …
=> 🏃 Validate OpenStackMachineTemplate spec.template.spec immutability

pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/utils/names/names.go, pkg/utils/utils.go
part of #868 
please note server description not added yet
https://github.com/gophercloud/gophercloud/pull/1505
I need drive that...
**TODOs**:
/hold
=> Add description to resource capi created

go.mod, main.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go, pkg/metrics/metrics.go
Part of #856 
**TODOs**:
/hold
=> Add metrics of gophercloud (POST,UPDATE and DELETE) actions

pkg/cloud/services/compute/instance.go
**What this PR does / why we need it**: Ensure that errors are logged properly when OpenStack instance creation fails.
Fixes #888
**TODOs**:
/hold
=> Fix error logging for OpenStack instance creation

docs/book/src/clusteropenstack/configuration.md
**What this PR does / why we need it**: Following up on the custom ports feature #876, this adds documentation to let users know about how to use the feature, as suggested in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/876#discussion_r646217134
Fixes #899 
Let me know if you'd like me add any further details, or add documentation to any other areas.
**TODOs**:
/hold
=> 📖 Document custom ports feature

hack/image-patch/pull-policy-patch.yaml
I broke the release staging target which I now need to release CAPO. This was caused by dropping kube-rbac-proxy. I only saw this in the post-submit image publish job.
ref: https://console.cloud.google.com/cloud-build/builds;region=global/618bcb4d-1360-4f99-812d-77f7f07e833b;step=0?project=k8s-staging-capi-openstack
**TODOs**:
/hold
=> 🐛 fix release staging target

api/v1alpha3/openstackcluster_types.go, api/v1alpha3/openstackmachine_types.go, api/v1alpha3/openstackmachinetemplate_types.go, api/v1alpha4/openstackcluster_types.go, api/v1alpha4/openstackmachine_types.go, api/v1alpha4/openstackmachinetemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
Adds short names for `openstackclusters, openstackmachines, and openstackmachinetemplates` resources
Fixes: #895
=> Add resource shortNames

docs/book/src/topics/external-cloud-provider.md
This comes from manual testing v0.4.0-beta.0.
- Bump calico version v3.16 to v3.19 which is tested against v1.19, v1.20, and v1.21.
Please refer to: https://docs.projectcalico.org/getting-started/kubernetes/requirements
- Fix URLs of RBAC resources
Fixes #898 
**TODOs**:
/hold
=> 🐛 Fix doc about external cloud provider

Makefile, RELEASE.md
Updates the release targets and doc so they work again with v1alpha4.
Fixes #796 
/hold
=> 🐛 fixup release targets and update doc accordingly

README.md
Upgrading a cluster without LBaaS is not supported.
Fixes #912 
**TODOs**:
/hold
=> 📖 Upgrading a cluster without LBaaS is not supported

hack/ci/devstack-default-cloud-init.yaml.tpl
After this PR we only use images from the CAPO GCS bucket in our tests. I uploaded the amphora image together with the others a while ago, but forgot to change the cloud init yaml.
Note: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/794 still has to be done in a follow-up issue.
**TODOs**:
=> 🏃 use amphora image from GCS in e2e tests

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go
This PR adds a description and tags to floating ips.
Part of #868
**TODOs**:
/hold
=> ✨ add description and tag to floating ips

pkg/cloud/services/compute/availabilityzone.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/provider/provider.go, pkg/metrics/metrics.go
Signed-off-by: Tobias Giese <tobias.giese@daimler.com>
Fixes #856
**TODOs**:
/hold
=> ✨ Add GET gophercloud metrics

controllers/openstackmachine_controller.go
Reverts kubernetes-sigs/cluster-api-provider-openstack#930
Because #930 did not fix #927.
=> Revert "reassociate Floating IP if first associate fails"

hack/ci/devstack-on-aws-project-install.sh, hack/ci/devstack-on-gce-project-install.sh
The --ttl flag has been removed from the latest version of sshuttle.
Previously, this was required to override the default TTL that sshuttle
sets of 63, so that packets from Prow / kind pods weren't ignored.
However, in the latest version of sshuttle, the TTL of packets leaving
the sshuttle server are no longer adjusted, so let's try without this
option.
Fixes #940
/hold
=> 🐛 Remove the ttl flag from sshuttle invocation

test/e2e/suites/e2e/e2e_test.go
The ports e2e test was checking that a failure condition had not occurred. However, it's possible the failure condition hadn't occurred because the machine used for the test had not been created yet, and the rest of the tests race ahead and do not find the port.
This commit ensures that we wait for the port to be created before testing properties of it.
We need to wait for machine deployment to finish before listing ports in the deployment.
Maybe fixes #927
/hold
=> 🐛 Wait for ports creation in ports e2e test

api/v1alpha4/openstackcluster_webhook.go, api/v1alpha4/openstackmachinetemplate_webhook.go, config/webhook/manifests.yaml
This PR fixes the Webhook names for the `OpenStackMachineTemplate` and `OpenStackCluster`.
As this fix is only for the webhook names (i.e., `ValidatingWebhookConfiguration.webhooks.name` and `MutatingWebhookConfiguration.webhooks.name`), it should only be updated.
diff of `kubectl kustomize`
```diff
--- /tmp/without-fixed-names.yaml	2021-07-20 07:50:41.591885981 +0200
+++ /tmp/with-fixed-names.yaml	2021-07-20 07:52:11.807954324 +0200
@@ -7823,7 +7823,7 @@
path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-openstackcluster
failurePolicy: Fail
matchPolicy: Equivalent
-  name: default.openstackcluster.infrastructure.x-k8s.io
+  name: default.openstackcluster.infrastructure.cluster.x-k8s.io
rules:
- apiGroups:
- infrastructure.cluster.x-k8s.io
@@ …
```
=> ✨ Fix Webhook names for OpenStackMachineTemplate and OpenStackCluster

controllers/openstackcluster_controller.go
…
On successful execution of `reconcileNormal` this ensures to reset the `.Status.FailureMessage` and `.Status.FailureReason` fields to nil.
Fixes #951
This could also be done for the openstack machine reconciliaton at https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackmachine_controller.go#L364
**TODOs**:
/hold
<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a …
=> 🐛 openstackcluster reconciliation: reset .Status.failureMessage and .Status.FailureReason on success

go.mod, go.sum, main.go
Signed-off-by: Tobias Giese <tobias.giese@daimler.com>
Fixes #954
**TODOs**:
/hold
=> ✨ Add webhook readiness and health checks

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, docs/book/src/clusteropenstack/configuration.md, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go
Trying to create a machine with specified tags would fail with:
Additional properties are not allowed ('tags' was unexpected)
We fix this by raising the minimum supported microversion to 2.53. Note
that this means we no longer support versions of OpenStack prior to
Pike.
Fixes #917
Note that this change has the potential to break code anywhere in CAPO by changing the behaviour of the Nova API. From a quick review of the microversion history I think we should be OK (the change to Flavor looked most significant, but it doesn't affect us yet). CI is especially important here.
I don't think a unit test …
=> 🐛 Fix failure to create server with specified tags

pkg/cloud/services/compute/instance.go, pkg/metrics/metrics.go, pkg/utils/errors/errors.go
…face
Fixes #959 
**TODOs**:
/hold
=> 🐛 ignore Conflict status in order to make instance able to detach interface

docs/book/src/clusteropenstack/configuration.md
=> 📖Add port security doc

pkg/cloud/services/compute/instance.go
If instance go error due to some exceptions of openstack, we can return error at once and not nesscessary to wait for timeout.
Fixes #968
**TODOs**:
/hold
=> 🏃Return error if instance go error

Makefile
in Makefile we are still using v1alpha3 (review Makefile found this) 
seems we need update to v1alph4 anyway though I didn't find changes after run the generate-go command
Fixes #
**TODOs**:
/hold
=> update from v1alpha3 to v1alpha4 in Makefile

api/v1alpha4/types.go, api/v1alpha4/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, docs/book/src/clusteropenstack/configuration.md, pkg/cloud/services/compute/instance.go
Configuring port profiles can be useful to enable an application
running on the specified host to pass and receive VIF port-specific
information to the plugin.
One of the use-cases here is when configuring ports in OVS Hardware
offload, where we need to use the profile:
{"capabilities": ["switchdev"]}
Thanks to this patch, we'll now able to do it when creating the
machines and their ports.
Fix #965
=> getOrCreatePort: add support to configure port Profile

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go
This PR primarily renames InstanceExists to GetInstanceByName to better represent its purpose.
In renaming this method it became clear that we were using the OpenStack API very inefficiently in DeleteInstance, so we clean that up, too. These changes fall into 2 categories:
* Don't re-fetch an object which we already have
* Handle 404 errors during DELETE operations
**TODOs**:
/hold
=> ✨ Cleanup and refactor InstanceExists and DeleteInstance

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_types.go, test/e2e/shared/openstack.go
This is predominantly a non-functional change. It contains some minor
changes to log messages, and omits a check for instance name being empty
prior to delete in OpenStackMachine controller because this check is no
longer relevant when we delete by ID. Apart from that it contains no
(deliberate) functional changes.
Currently we use infrav1.Instance as our internal representation of an
OpenStack instance. There are several problems with this:
* infrav1.Instance is part of the API, so is hard to change for internal
use
* infrav1.Instance is used to represent both the 'spec' and 'status' of
an instance
* When used as a spec for the Bastion host, it allows fields to be set
which will be ignored
* When used as the status of an instance fetched from OpenStack not all
fields are populated, …
=> :sparkles: Refactor: Don't use infrav1.Instance internally

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go
When failed to create instance with error state in OpenStack, currently `DeleteInstance` logic didn't delete port of the error instance.
Because, error instance's port detached from the instance by OpenStack.
If a port of error instance is still living until deleting managed security group, deleting a security group fails because the port is not deleted and is still associated with the security group.
As a result, OpenStackCluster deletion reconcile loop stuck.
To resolve above problem, I added logic of deleting port of error instance.
Fixes #976
1. Please …
=> Add gc for error instance's port

api/v1alpha4/types.go, api/v1alpha4/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, pkg/cloud/services/compute/instance.go
Allow Trunk configuration at a Port level
This PR enables and disables port level trunk setting as follows.
- If user provides trunk field (true or false) at Port level, then that value is used for the port.
- If user does not provide trunk field at Port level, then the port inherits the trunk field of the instance. 
Example spec:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: OpenStackMachineTemplate
metadata:
name: basic-1-control-plane
namespace: default
spec:
template:
spec:
template:
spec:
trunk: true
ports:
- description: "Port 1, no trunk specified"
- description: "Port 2, trunk disabled"
trunk: false
- description: "Port 3, trunk enabled"
trunk: true
cloudName: openstack-1
flavor: 2C-4GB-100GB
identityRef:
kind: Secret
name: basic-1-cloud-config
image: …
```
=> ✨ Allow Trunk configuration at a Port level

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go
=> only use loadbalaner reference if needed

api/v1alpha3/conversion.go
This patch sets the `Kind` in `IdentityRef` to `Secret` during the conversion
from the `CloudSecret` to the `OpenStackIdentityReference`. Without a `Kind`
set, the admission hook rejects the converted resource, because it is invalid, which makes it
impossible to upgrade.
=> :bug: Fix Conversion from alpha3 to alpha4

docs/book/src/development/development.md
Documents how to run E2E tests locally, including the enhancements added in #981.
=> ✨Document running E2E tests locally

controllers/openstackcluster_controller.go
Assumption: provisioned openstackcluster
When the controller for openstackcluster does reconcile and returns an error after [line 406](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackcluster_controller.go#L406) the defer patch will update the openstackcluster and remove values because the openstackcluster.status.network gets rebuilt on each reconciliation.
Fixes #
**TODOs**:
/hold
<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a …
=> ⚠️ Don't overwrite openstackcluster.status.network on reconciliation

main.go
Upgrading from alpha3 to alpha4 is only possible, if the schemes are added.
Otherwise the controller is not able to fetch those resources.
This PR adds the old alpha3 schemes to the controller. We need it, because otherwise it is impossible to use those resources and the conversion does not work properly.
This is pretty similar to https://github.com/kubernetes-sigs/cluster-api/pull/4417
=> :bug: Add alpha3 Resources to Scheme

pkg/cloud/services/compute/bastion.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/networking/client.go, pkg/cloud/services/networking/mock_networking/client_mock.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/trunk.go
This refactors all networking client behavior into the networking package. The network client has been removed from the compute Service struct, instead, we use the networking Service. Ports and trunking logic have been moved out of instance.go in the compute package into port.go and trunk.go in the networking package.
The process for refactoring is simple enough:
1. Delete network client from compute package
2. Move any functions using the network client to the networking package
3. Refactor the functions to call the networking client interface instead of gophercloud directly
This will allow us to write unit tests for ports and trunk functionality using the mocks in the networking package. It also considerably tidies up instance.go, since now all …
=> 🏃 Refactor all network client calls into networking package

pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_types.go, test/e2e/shared/openstack.go
This is currently only required by MAPO, where it's used to label the
node with its AZ. It doesn't fetch any additional data from OpenStack,
just exposes it in Go.
CAPO doesn't need it, yet. MAPO does, though, it's 'free', and CAPO will almost certainly require it eventually.
Fixes #
**TODOs**:
=> ✨Add InstanceStatus.AvailabilityZone()

pkg/cloud/services/compute/instance.go, pkg/cloud/services/networking/port.go
Following up on @mdbooth's review of #950, this moves the `deletePorts` function from the networking package back to the compute package where it can be made a private function.
**What this PR does / why we need it**: fixes a nit from a review of #950 
**TODOs**:
/hold
=> 🏃 Move deletePorts back to compute package

api/v1alpha4/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, docs/book/src/clusteropenstack/configuration.md, pkg/cloud/services/networking/securitygroups.go, test/e2e/data/infrastructure-openstack/cluster-template-external-cloud-provider.yaml
This PR implements an additional flag that allows the creation of managed security groups that permit all in-cluster traffic. Note that all traffic from outside the cluster (except API server and NodePort services) is still blocked.
This makes it much easier to deploy a CNI other than Calico while still using managed security groups.
In the future, we could look at maintaining rules for multiple CNIs which can be selected from, or allowing users to specify custom rules for the managed security groups. However I think this represents a good catch-all.
Fixes #995 
**Special notes for your …
=> :sparkles: Implement allowAllInClusterTraffic flag

pkg/cloud/services/networking/client.go, pkg/cloud/services/networking/trunk.go
This ensures that all calls made by the client in the networking package have a Prometheus metric associated with them.
Delete and Get calls are standardized to not record an error in the metrics if the resource in OpenStack is not found. (However, the not found error will still be returned by the function as nil, err.)
Finally, the replace all attributes tags call is no longer recorded as a trunk update event.
**What this PR does / why we need it**: based off fixing a comment in @mdbooth 's review of #950.
Partially fix #997 (for networking related calls, but compute related calls are still TODO.)
**TODOs**:
/hold
=> 🏃 Standardize metrics in networking package

api/v1alpha4/openstackcluster_webhook.go, api/v1alpha4/openstackmachine_webhook.go
Only allow the field's update at first time, as that will be updated by CAPI internally,
after that, customer's update will be rejected..
follow up of #1006 
**TODOs**:
/hold
=> ✨Allow update for some param only first time update

api/v1alpha4/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/networking/service.go
If we specify a network with a subnet filter but no network filter, we now execute a single subnet query rather than executing one for every network. We also no longer execute queries at all when the user has specified a uuid explicitly.
Fixes #993
This PR is intentionally structured in 2 commits:
The first adds unit tests for getServerNetworks (ironically using the excellent work in #935, which also happened to be the commit which introduced the regression). The second fixes getServerNetworks and makes the necessary changes to the unit tests.
The purpose of …
=> 🐛 Don't make unnecessary REST API calls in getServerNetworks

test/e2e/data/cni/calico.yaml
Since calico v3.18 is not actively tested against kubernetes v1.21, it is better to update.
Reference: https://docs.projectcalico.org/archive/v3.18/getting-started/kubernetes/requirements
Fixes #
**TODOs**:
/hold
=> 🏃 Bump calico from v3.18.1 to v3.20.1

controllers/openstackmachine_controller.go
Signed-off-by: Schlotter, Christian <christian.schlotter@daimler.com>
Fixes occurencies of `context.TODO()` and replaces it with the real context object.
I left out the `test/e2e` directory :-)
Fixes #
**TODOs**:
/hold
<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH, 
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Provider Information</a>
</sup>
=> ✨ controllers: replace context.TODO with real context objects

pkg/cloud/services/compute/instance.go
This PR adds a check on trunk support before enabling trunk at port level.
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1013
=> Check trunk support before enabling trunk at port level

Makefile, test/e2e/suites/e2e/e2e_test.go
This makes 2 improvements to error logging in E2E tests:
* Specific improvements in gomega error reporting in the multi-network test
* Stop using --stream for ginkgo output
=> ✨E2E error logging improvements

Makefile, common.mk
This PR should fix the [failing `post-cluster-api-provider-openstack-push-images` job](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-cluster-api-provider-openstack-push-images?buildId=1435576994635976704).
It seems that the first failing job was on September 2nd 11:02am, which was PR #981.
last successful job: [Sep 01 10:35:07](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-openstack-push-images/1432985330457251840)
first failing  job: [Sep 02 11:02:17](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-openstack-push-images/1433354559073292288)
I found the following errors:
```
ERROR: (gcloud.builds.submit) build 4b63deb7-f8ff-45ca-8d00-977233c67a78 completed with status …
```
=> 🐛 Fix image push in Makefile for image-push jobs

test/e2e/data/cni/calico.yaml
docker.io is rate limited without authentication, quay.io is not. This
is causing failures in local CI testing because provisioned machines
can't pull the calico image and therefore never become Ready.
We likely avoid this issue in CI due to the implementation of rate
limiting in docker.io, but it would not be impossible to hit it there,
either.
Calico publishes images to both repositories, so this just works.
=> 🐛Pull Calico from quay.io instead of docker.io

OWNERS, OWNERS_ALIASES
Signed-off-by: Stefan Büringer buringerst@vmware.com
Hey folks,
I think it's time to reflect reality in the OWNERS files ;)
=> 🏃 Move sbueringer to emeritus maintainers

controllers/openstackmachine_controller.go
This commit deletes unused annotation `cluster-api-provider-openstack: true`. It is not used since Cluster API v1alpha3.
CAPA already removed: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1881
Fixes #
/hold
=> 🏃 Delete unused annotation

api/v1alpha3/conversion.go, api/v1alpha3/conversion_test.go, api/v1alpha3/zz_generated.conversion.go, api/v1alpha4/conversion_test.go, api/v1alpha4/openstackcluster_types.go, api/v1alpha4/openstackmachine_types.go, api/v1alpha4/zz_generated.conversion.go, api/v1beta1/openstackcluster_types.go, api/v1beta1/openstackmachine_types.go, go.mod
The most interesting parts of this PR are the new unit tests. The tests are little more than a 'do the fields line up' test, but they did highlight that we were missing conversion of IdentityRef.
I will be adding to these tests in #1030
Fixes #1065 #1060
=> 🐛Fix conversion of IdentityRef converting between v1alpha4 and v1beta1

pkg/cloud/services/networking/securitygroups.go, test/e2e/data/infrastructure-openstack/cluster-template.yaml, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
When ManagedSecurityGroups: true, security groups created by CAPO
are tagged with the tags on OpenStackCluster.spec.tags. Update
e2e tests to include tests for various resources that are tagged.
Fixes #1044 
1. Tags on SG are only added on creation, they are not propagated to cluster.status nor reconciled. Please let me know if you think any of the 2 needs to be added.
1. I didn't find any unit tests for the securitygroups but i updated the e2e tests. I used an existing test scenario as creating a new one seemed like an overkill. Also added tests for other resources that are also tagged
**TODOs**:
/hold
=> :sparkles:  Add tags on security groups created by capo

pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go
**This PR is only the final commit in the series! All other commits are from #1061, which needs to merge first**
This fixes a leak of ports when failing to fetch image or flavor for any reason, including user error, during instance creation.
Fixes #1062
**TODOs**:
/hold until #1061 merges
=> 🐛Cleanup ports

api/v1alpha4/openstackcluster_webhook.go, api/v1alpha4/openstackcluster_webhook_test.go, api/v1alpha4/openstackclustertemplate_webhook.go, api/v1alpha4/openstackmachinetemplate_webhook.go, api/v1beta1/openstackcluster_webhook.go, api/v1beta1/openstackcluster_webhook_test.go, api/v1beta1/openstackclustertemplate_webhook.go, api/v1beta1/openstackmachinetemplate_webhook.go, docs/book/src/clusteropenstack/configuration.md
This PR allows `OpenStackCluster.Spec.Bastion` to be updated (i.e., to be mutable).
Fixes #1054
**TODOs**:
/hold
=> ✨ Allow webhook changes to OpenStackCluster.Spec.Bastion

hack/ci/create_devstack.sh
When creating multiple capo-e2e devstacks on the same shared cloud you will need to give them different names. We were also using this name when writing the local clouds.yaml. However, that requires also modifying the local e2e_conf.yaml. As there is no naming conflict between developers' local clouds.yaml copies these can safely be the same everywhere, which is easier to work with.
=> 🏃Fix generated clouds.yaml for local e2e tests

pkg/cloud/services/loadbalancer/loadbalancer.go
When CAPO enters `service.ReconcileLoadBalancerMember` at [pkg/cloud/services/loadbalancer/loadbalancer.go](https://git.daimler.com/c445/cluster-api-provider-openstack/blob/master/pkg/cloud/services/loadbalancer/loadbalancer.go#L250) and detects a already finished port during inside the for loop, the function immediately returns instead of reconciling the other ports too.
**TODOs**:
/hold
=> 🐛 fix loadbalancer service to reconcile all ports instead of returning at the first

pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go
fail fast, inspired by recent discussion in port leak 
for those kind of error handling, we can fail fast without go to create port then delete port stage
if we know it's definitely will fail...
Fixes #
**TODOs**:
/hold
=> Fail fast without create port at all

README.md, hack/ci/cloud-init/controller.yaml.tpl, hack/ci/cloud-init/worker.yaml.tpl, hack/ci/create_devstack.sh
Migrate the CI to use the Wallaby release. This is an incremental change to get
us up to the latest stable release, Xena.
Fixes: #1092
No image version changes.
**TODOs**:
/hold
=> 🏃 Migrate CI to Wallaby

pkg/cloud/services/networking/service.go
When trunk is enabled at Port or Instance level and no tags are provided at either level, deployment fails. 
This PRs fixes this issue by avoiding performing the ReplaceAllAttributesTags when no tags are provided.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1106
=> 🐛  Avoid replacing tags when no tags are provided.

docs/book/src/development/ci.md, hack/ci/gce-project.sh
#1109 pointed out that it's useful to have an alternative OS option, albeit for a reason I didn't think of when I originally made it possible to use CentOS in addition to Ubuntu. This simply documents the alternative and encourages developers to keep the option open.
Fixes #1109 
/hold
=> Document running CI devstack on CentOS

pkg/cloud/services/networking/service.go
Remove duplicate tags before making API calls.
Tags that come from instance and port levels could contain duplicate values, causing failure when making api call.
This PR removes duplicate values before making the call. The change is done on the `replaceAllAttributesTags` function in order to avoid making changes in multiple places where tags are collected.
fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1111
=> Remove duplicate tags before making API calls

pkg/cloud/services/loadbalancer/loadbalancer.go
ReconcileLoadBalancer check for appropiate load balancer state implemented to prevent creation of floating ip's for load balancer with states other than ACTIVE.
Documentation link to openstack load balancer states updated.
Reconcilation of load balancers in other states than ACTIVE could cause the creation of unused floating iIPs until the quotas exceeds.
This PR provides a check of the appropriate load balancer state before creating other resources.
Fixes #1114
**TODOs**:
/hold
=> 🐛 Prevent creation of floating IPs when reconcile load balancer in non ACTIVE state

hack/ci/cloud-init/controller.yaml.tpl, pkg/cloud/services/networking/trunk.go
This PR has two purposes:
- Enabling trunk support on the e2e infra
- fixing issue related to trunk deletion
Port deletion involves three steps.
1. Detaching port
2. Deleting trunk
3. Deleting port
The `Openstack api call` to `Detaching port` (1), returns immediately without waiting for the operation to complete. Due to this, it is possible that the `Deleting trunk `(2) be execute first, resulting in error.
This PR ensures `Deleting trunk` (2) is executed after a successful `Detaching port` (1). 
fixed #1124
=> ✨  Ensure trunk deletion

OWNERS
* remove reviewers according to [cleanup instructions](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#cleanup)
* rename emeritus_maintainers to emeritus_approvers
Fixes #1122
**TODOs**:
/hold
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)</sub>
=> 🏃 OWNERS: satisfy the maintainers tool

controllers/openstackcluster_controller.go
Avoid set failMessage if create bastion failed (which we will not reconcile again)
instead, give some chance to re-create or customer might do some manual changes in order to
make cluster able to create again
Related: #1131 
**TODOs**:
/hold
=> Avoid set failMessage when bastion creation failed

Containerfile
Keep in sync with Dockerfile.
Aligns Containerfile's Go version to Dockerfile's.
Fixes #1155
**Notes for the reviewer**:
This patch should only impact local development environments, and not affect any release image.
**TODOs**:
=> 🐛 containerfile: Bump Go version

README.md, hack/ci/cloud-init/controller.yaml.tpl, hack/ci/create_devstack.sh
part of this steal from https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1098
but I can't update that PR so created a new one
the main change to that PR is the sequence of upload ubuntu and cirros image
the reason is https://docs.openstack.org/glance/latest/admin/quotas.html 
introduced a limit and if ubuntu is uploaded first then cirros will not be able to upload due to limit introduced in x release, on the contrary , ubuntu is able to be uploaded because at time of upload
the limit is not reached  (yet)
Fixes #
1. Please confirm that …
=> move CI to xena

README.md
Currently our Office Hours are not easily discoverable, they are only linked in a Slack Channel message and in the sig-cluster-lifecycle Calendar. This PR adds links to the Office Hours to our `README.md` and the front page of the published book (which is the README).
Topic came up in Slack: https://kubernetes.slack.com/archives/CFKJB65G9/p1646745862386189?thread_ts=1646731771.368219&cid=CFKJB65G9
=> 📖 add info about office hours to README and Book

controllers/openstackcluster_controller.go
Previously we only added to the List of `FailureDomains`, but this can cause issue in case any Availability Zone is removed in OpenStack, as that AZ will still be used by CAPI to deploy Control Plane machines. With this PR, the list of available FailureDomains/AZs is recreated on every reconcile and outdated entries are removed.
Fixes #1163
**TODOs**:
/hold
=> 🐛 Clean up removed AvailabilityZones from `OpenStackCluster.status.failureDomains`

pkg/cloud/services/loadbalancer/loadbalancer.go
I have been running into this issue (#1114 #1159) often recently. It is annoying to have to clean up the extra floating IPs manually. The fix on `main` hasn't been released yet so I would like to backport it for release as v0.5.3.
Fixes #1114
Cherry-pick of #1115
**TODOs**:
/hold
=> :bug: [v0.5.0] Prevent creation of floating IPs when reconcile load balancer in non ACTIVE state

pkg/cloud/services/compute/instance.go
Conflicts:
pkg/cloud/services/compute/instance_test.go
Unit tests have not been backported because they added test cases to
unit tests which don't exist in release-0.5.
(cherry picked from commit 28f820b3580ac901864b169560ab89b325f323bd)
/hold
=> 🐛 Delete trunk on failure

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/floatingip_test.go
Floating IP operations were always reporting events against the cluster,
even when creating a floating IP on behalf of a machine.
Fixes: #1176 
/hold
=> 🐛 Fix event target of floating ip operations

pkg/cloud/services/networking/floatingip.go
Although there are currently no internal users, this allows fetching a
floating IP without attempting to create one if it doesn't exist.
I'm actually adding this because we need it [in MAPO](https://github.com/openshift/machine-api-provider-openstack/blob/4adc3323d876799867e5bf66e6244fdcc99b415b/pkg/machine/actuator.go#L313). The use case is associating a specific floating IP to a machine which is required to exist already. We don't want to make any attempt to to create the floating IP if it doesn't exist.
/hold
=> ✨Export GetFloatingIP

go.mod, go.sum
Upgrade the Prometheus client to v1.11.1.
This commit is the result of running:
```
go get github.com/prometheus/client_golang@v1.11.1 \
&& go mod tidy
```
See https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
Upgrades `github.com/prometheus/client_golang` to v1.11.1, where the vulnerability has been fixed.
Fixes #1181
One handy way to check that the version of `client_go` used for compiling contains the security patch, is to run `go mod vendor` and check that the `InstrumentRoundTripperCounter` method [contains a variadic `options` argument](https://github.com/prometheus/client_golang/compare/v1.11.0...v1.11.1#diff-7871a83741d29b5f29e3c47d1c284f9 …
=> 🐛 Address CVE-2022-21698

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/service.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/service.go, pkg/scope/scope.go
This refactoring will make it easier to pass the `ProjectID` into the services that need it (see #1146). The Scopes pattern is also used by other CAPI Providers:
- CAPA: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/scope/cluster.go
- CAPG: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/scope/cluster.go
- CAPV (Called `Context`): https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/context/cluster_context.go
/hold
=> 🏃 Add Scopes to pass data to services

hack/ci/create_devstack.sh
We used to install sshuttle from source because we needed a commit that was not in the latest release. There is however a new release now that includes the commit. Upstream sshuttle also [dropped support for python 3.6 and 3.7 recently](https://github.com/sshuttle/sshuttle/commit/6d36916f48ae69abe175682f111f505923aba339) which means we can no longer install that, since we use python 3.7.
**TODOs**:
=> 🐛 Install sshuttle using pip instead of from source

Makefile, controllers/suite_test.go, scripts/go_install.sh
The controller test suite was disabled due to missing kubebuilder
assets. These are now installed before running the tests. There are no
tests yet but now it is possible to add some.
**TODOs**:
=> 🏃 Enable controller tests

README.md, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/service.go, pkg/cloud/services/provider/provider.go, pkg/scope/scope.go, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
We currently require an explicit `project_id` field in the clouds.yaml. This conflicts with the usual fields for Application Credentials, as they already include a scope, and setting another conflicts with that.
In this commit, we instead save the returned `project_id` from the initial auth api call, and pass it around to all services using the `Scope` struct.
Fixes #1146 
/hold
=> ✨ Support Application Credential auth

go.mod, go.sum
Cherry pick of #1204 onto `release-0.5`. Automated cherry-pick failed because of conflicts.
=> 🐛 address CVE-2022-27191

controllers/openstackcluster_controller.go, test/e2e/shared/openstack.go
* fixes nil pointer when reconcileDelete gets executed a second time and security groups already got deleted
* ```
I0425 01:06:29.568971       1 openstackcluster_controller.go:132] controller/openstackcluster "msg"="Reconciling Cluster delete" "cluster"="cluster-conformance-tn6axt" "name"="cluster-conformance-tn6axt" "namespace"="conformance-tn6axt" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x14e6d9a]
goroutine 419 [running]:
sigs.k8s.io/cluster-api-provider-openstack/controllers.bastionToInstanceSpec(0xc000069000, {0xc0006300c0, 0xc000069000}) …
```
=> 🐛 controllers/openstackcluster_controller.go fix nil pointer and dump openstack ports

docs/book/src/SUMMARY.md, docs/book/src/topics/crd-changes/index.md, docs/book/src/topics/crd-changes/v1alpha4-to-v1alpha5.md
List backwards-incompatible changes made to the CRDs going from v1alpha4 to v1alpha5. I only added those I knew about and I understood. @mdbooth maybe you want to provide some more details about the Port and Network changes you can Emilio did, but I did not have the time to understand and document them.
Fixes #1188
/hold
=> 📖 Document CRD changes from v1alpha4 to v1alpha5

api/v1alpha4/conversion.go, api/v1alpha4/conversion_test.go
Root volumes in v1alpha4 can only specify root volume image by UUID. We were
translating this to use Image from the parent, which requires a name,
not a UUID. In v1alpha5 we can also have the ImageUUID field, so we
translate to that instead.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1220
/hold
=> 🐛Fix conversion of boot from volume images

docs/book/theme/css/general.css
Currently we only show the first 7 tabs in the book. This is a problem because the OpenStack Tab in the getting started guide is on position 10, potentially causing issues when people do not see some necessary steps.
This was recently fixed in upstream CAPI in kubernetes-sigs/cluster-api#6435
=> 📖 allow up to 20 tabs in book

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
We use the CAPI release-note tool to generate Release Notes. They switched the icon for "other" from `:running:` to `:seedling:`.
This caused issues with the latest release because the title for many PRs could not be automatically parsed and we needed to fix the generated release notes manually.
The new text is a direct copy of CAPI PULL_REQUEST_TEMPLATE.md: https://github.com/kubernetes-sigs/cluster-api/blob/582b0e1354cdb59221e55b05e13cc43d94ce04cc/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L2
/hold
=> 🏃 update PR icon template to match CAPI

RELEASE.md
Lessons learned from v0.6.0.
/hold
=> :seedling: Update RELEASE.md process for release branches

controllers/openstackcluster_controller.go
Fixes a nil pointer reference when a cluster does not have a bastion configured.
Fixes #1230
**TODOs**:
/hold
=> :bug: Fix nil pointer reference during bastion deletion

OWNERS_ALIASES
Unfortunately, I haven't much time nowadays to contribute and participate in reviews. Hope to be back contributing again soon! But will remove myself as a default reviewer for now.
=> 🌱 Remove macaptain from cluster-api-openstack-reviewers

controllers/openstackcluster_controller_test.go, controllers/suite_test.go, go.mod, test/helpers/external/cluster.go
This adds some simple tests for the OpenStackCluster controller.
2. Note that there are 3 commit. I can make separate PRs for them or remove some of them if needed.
3. [This file](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1199/files#diff-9da8f7e78e11f549d7ff45cd4706d6946b664816033d9a29a518017b98a06a7a) was copied almost verbatim from CAPA. We could alternatively import the relevant package. What do you think would be better?
4. Please note the pending test. I'm not sure how to move forward with this and would appreciate any hints. If there are no obvious solutions I think maybe we …
=> 🏃 Add tests for cluster controller

api/v1alpha4/conversion.go, api/v1alpha4/conversion_test.go, api/v1alpha5/conversion.go
Adds `Hub()` methods to `v1alpha5` `OpenStackClusterTemplate` struct and implements `Convertible` interface in `v1alpha4`. API was only introduced in `v1alpha4`, so conversion to/from `v1alpha3` is not needed.
`conversion-gen` already generated the automatic conversion functions.
Fixes #1248
/hold
=> 🐛 implement conversion for OpenStackClusterTemplate CRD

api/v1alpha4/conversion_test.go, api/v1alpha4/zz_generated.conversion.go, api/v1alpha5/types.go, api/v1alpha5/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, hack/ci/cloud-init/controller.yaml.tpl, pkg/cloud/services/networking/port.go, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
With `OpenStackMachineTemplate` it is possible to specify security groups at both instance and port levels. However, both levels do not have same format, with the instance level having more options. This PR moves the port level format closer to that of the instance level, as shown below.
Specifying security groups at port level:
```
spec:
template:
spec:
ports:
- description: "Port 1 with security group in UUID format"
securityGroups: 
- "2f6584db-5138-453b-b47b-99696cb11f0f" 
```
Specifying security groups at port level:
```
spec:
template:
spec:
securityGroups:
- name: "capo-port-instance-level-sg"
uuid: ....
filter: .....
```
As can be seen above, the instance level setting has more options. This PR the `securityGroupsFilters` field. The original field `port.securityGroups` is kept for …
=> Passing security groups by specifying more options in addition to UUIDs on ports

controllers/openstackmachine_controller.go
The failure domain is an optional field for CAPI `Machine` objects. This patch makes sure that we can respect the case where a failure domain is not specified - currently this results in a failed machine.
This is implemented by omitting the availability zone from the server create if no failure domain is present on the CAPI machine. In this case, Nova will pick a suitable availability zone for the machine based on all other scheduling constraints.
This change was previously part of PR #1252.
1. Please confirm that if this PR changes any image versions, then …
=> 🐛 Make failure domain optional for OpenStackMachine

docs/book/src/clusteropenstack/configuration.md
Mention that the value of
`CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT` must be set in minutes.
In the user documentation, it was not clear that the value passed as `CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT` is interpreted as minutes (as opposed to seconds, for example).
Fixes #1266
**TODOs**:
/hold
=> 📖 Instance create timeout is in minutes

pkg/cloud/services/networking/floatingip.go
in reviewing https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1265
found we use event for the already associated FIP 
not remember whether this is valid as current understanding seems this should be log only as it might happen many times
```
7     112    3101
```
Fixes #
**TODOs**:
/hold
=> nit:make event to log for already associated FIP

docs/book/src/topics/external-cloud-provider.md
update doc for external cloud provider ...
Fixes #
**TODOs**:
/hold
=> update doc to reflect latest version, add helm link

api/v1alpha3/openstackcluster_types.go, api/v1alpha3/openstackmachine_types.go, api/v1alpha4/openstackcluster_types.go, api/v1alpha4/openstackmachine_types.go, api/v1alpha5/openstackcluster_types.go, api/v1alpha5/openstackmachine_types.go, api/v1alpha6/openstackcluster_types.go, api/v1alpha6/openstackmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml
Add the age column to openstackcluster and openstackmachine.
As openstackclustertemplate and opensackmachinetemplate don't have any custom `printcolumn` defined, per default only name of the object and Age will be printed - so we're already fine.
Signed-off-by: Mario Constanti <mario@constanti.de>
Fixes #
**TODOs**:
/hold
=> Add Age column for osc/osm

controllers/openstackcluster_controller.go, pkg/cloud/services/networking/port.go
=> 🐛 delete port left over by err openstackmachine

Makefile, hack/tools/Makefile
Since https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1271 the e2e templates are now generated, but test-conformance-fast was not generating them.
**TODOs**:
/hold
=> Fix generation of e2e-templates when running conformance tests

pkg/cloud/services/compute/instance_types.go, pkg/cloud/services/compute/instance_types_test.go
The logger does not use string formatting. Instead it is doing structured logging and expects key-value arguments, as seen [here](https://github.com/go-logr/logr#but-i-really-want-to-use-a-format-string).
This PR fixes the arguments so that they follow the expected format.
Fixes #1280
2. I have a sort of reproducer for the issue. It is possible to trigger the logger when running the unit tests and then see that it is complaining about the arguments. The …
=> 🐛 Fix logger arguments

go.mod, go.sum, main.go
Migrates our logging to `component-base/logs` and loads the json logger for `--logging-format=json`.
Migration was done by following the steps in the [CAPI v1.1 -> v1.2 migration guide](https://release-1-2.cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#other).
Related to #1282 
I am not sure if we want to enable `--logging-format=json` by default, other providers (including core CAPI) do not do this.
=> ✨ Enable JSON Logging

controllers/openstackmachine_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go
IMO we should check whether it is required (machine == control-plane) before
calling `loadbalancer.Service#ReconcileLoadBalancerMember`. The service
should not be concerned with the type of machine it is called on.
This also fixes one of the open bugs in PR #1288.
-
=> 🌱 only reconcile loadbalancer member if machine is control-plane

test/e2e/data/kubetest/conformance-fast.yaml, test/e2e/data/kubetest/conformance.yaml
According to the [discussion in Slack](https://kubernetes.slack.com/archives/C8TSNPY4T/p1657801896028979?thread_ts=1657801887.174059&cid=C8TSNPY4T) we should add the `ginkgo.timeout` parameter to our kubetest configs.
Fixes #
**TODOs**:
=> 🌱 Set ginkgo.timeout in our kubetest config

go.mod, kustomize/v1alpha5/default/cluster-template.yaml, kustomize/v1alpha6/default/cluster-template.yaml, test/e2e/data/kubetest/conformance-fast-ginkgo-v2.yaml, test/e2e/data/kubetest/conformance-ginkgo-v2.yaml, test/e2e/data/kubetest/conformance.yaml, test/e2e/suites/conformance/conformance_test.go
This PR fixes the conformance tests.
`Jul 19 15:46:21 cluster-conformance-t93zy8-control-plane-6wnvx cloud-init[612]: [2022-07-19 15:45:45]         [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725: output: time="2022-07-19T15:45:35Z" level=fatal msg="pulling image: rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725\": k8s.gcr.io/kube-apiserver:v1.25.0-alpha.2.398_3992eda8e61725: not found"
[...]`
xref: [cloud-final.log](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-openstack-conformance-test- …
=> 🐛 Fix conformance tests

api/v1alpha6/openstackcluster_webhook.go, api/v1alpha6/openstackcluster_webhook_test.go, controllers/openstackcluster_controller.go, docs/book/src/clusteropenstack/configuration.md, go.mod, pkg/cloud/services/compute/instance.go, pkg/utils/hash/hash.go
Signed-off-by: Tobias Giese <tobias.giese@mercedes-benz.com>
Thanks to @chrischdi for the discussion and hash annotation idea! 🙂
TODO:
Fixes #1298
**TODOs**:
/hold
<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> ✨ Add re-creation of bastion host on change

controllers/openstackmachine_controller.go, docs/book/src/clusteropenstack/configuration.md
=> not assign floating ip when there are multiple controller nodes

scripts/ci-conformance.sh, scripts/ci-e2e.sh
Signed-off-by: Tobias Giese <tobias.giese@mercedes-benz.com>
We have to ensure that `python` and `pip` are installed for our boskos resource management.
In https://github.com/kubernetes/test-infra/issues/26900#issuecomment-1195163041 we've learned that python is only an artifact of bazel in the `gcr.io/k8s-staging-test-infra/kubekins-e2e` image. Therefore, we have to ensure that it's installed.
We can think about rewriting our `boskos.py` in a go binary to not have the python dependency.
Fixes #
1. Please confirm that if this PR changes any image versions, …
=> 🌱 Ensure that python and pip is installed for e2e and conformance tests

pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go
This PR removes the used of a [deprecated API](https://docs.openstack.org/nova/latest/contributor/project-scope.html#no-more-api-proxies) by removing the setting of security groups directly on instances.
Fixes #1316 
**TODOs**:
/hold
=> :bug: Add security groups to ports only

api/v1alpha6/openstackcluster_types.go, api/v1alpha6/openstackmachine_types.go, api/v1alpha6/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
This commit adds merge strategy markers to our v1alpha6 API. This is required for Server-Side Apply (SSA) to work correctly. SSA is used in Cluster API v1.2, and not having these markers might cause issues when using ClusterClass patches.
This only adds a subset of markers, where it was possible. I skipped adding markers for two cases:
- We have many slices that do not have any proper map keys, as all fields are optional. This includes mostly "filter" structs, for example `NetworkParam` and `SecurityGroupParam`.
- The selected map key may not be optional (`omitempty`). If it is, it can not be used as the map key. This applied to structs `AddressPair` and `ExternalRouterIPParam`.
Further documentation:
- CAPI v1.2 provider migration: …
=> 🌱 add merge strategy markers

hack/ci/cloud-init/controller.yaml.tpl, hack/ci/create_devstack.sh
upgrade devstack to Yoga
NOTE:
I suspect this commit change the neutron plugin behavior of devstack so the service plugin trunk is not enabled by default (which leaves e2e fail) ,so I updated the conf file directly to include trunk plugin
```
commit f758b60a4b70261393242b932063d2b6d705594c
Author: Slawek Kaplonski <skaplons@redhat.com>
Date:   Wed Oct 6 12:02:22 2021 +0200
Rehome functions to enable Neutron's Trunk service plugin
Those functions were part of the neutron devstack plugin but we
discussed on the neutron team meeting [1] to move it to the Devstack
repo as it's mature enough now.
[1] https://meetings.opendev.org/meetings/networking/2021/networking.2021-10-05-14.00.log.html#l-156
Change-Id: I35446adad1d8a7fed142d834de20c48b611015a5
``` …
=> update devstack release

OWNERS_ALIASES
As I announced at the Office Hours a few weeks ago, tomorrow will be my last day at $CURRENT_JOB and I won't be involved with CAPO at $NEW_JOB. Because of this I step down from my reviewers position. Thanks for the great time :)
=> 🌱 remove apricote from reviewers

README.md, test/e2e/data/e2e_conf.yaml
=> update k8s to 1.25

pkg/cloud/services/loadbalancer/loadbalancer.go
If .status.network is empty (e.g. during clusterctl move) the reconciliation will fail due a nil pointer.
This commit skips the first reconciliation of
openStackCluster.Spec.APIServerLoadBalancer.AllowedCIDRs after a clusterctl move.
Signed-off-by: Mario Constanti <mario@constanti.de>
Fixes #1339
**TODOs**:
/hold
=> 🐛 fix nilpointer during clusterctl move

Makefile, common.mk
* Fixes link to Makefile best practice page
* Groups the Makefile targets based on existing comments
With this pr the `make` output is: 
```
Usage:
make <target>
Testing
test             Run tests
e2e-templates    Generate cluster templates for e2e tests
e2e-prerequisites  Build all artifacts required by e2e tests
test-e2e         Run e2e tests
test-conformance  Run clusterctl based conformance test on workload cluster (requires Docker).
test-conformance-fast  Run clusterctl based conformance test on workload cluster (requires Docker) using a subset of the conformance suite in parallel.
Binaries
binaries         Builds and installs all binaries
manager-openstack-infrastructure  Build manager binary.
Linting
lint             Lint codebase
lint-update …
```
=> 🌱 Group Makefile targets

hack/ci/create_devstack.sh
Works round an issue caused by an incompatible change to the importlib-metadata python library which breaks us on python 3.7.
Fixes: #1351 
/hold
=> ci: Pin to the yoga version of openstackclient

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go
DeleteInstance requires very little data from InstanceSpec. The 2 methods to create an InstanceSpec, bastionToInstanceSpec and machineToInstanceSpec, require more state than is required by DeleteInstance, and have failure modes which are not relevant to DeleteInstance.
Fixes #1264
/hold
=> 🐛 Don't require an InstanceSpec for DeleteInstance

scripts/ci-test.sh, templates/.gitignore, templates/cluster-template-external-cloud-provider.yaml, templates/cluster-template-without-lb.yaml, templates/cluster-template.yaml
These templates are now generated from kustomize, but can still be useful to have in the repo. For example, there are links pointing to them.
This also adds a test to make sure that the repo is clean after running make generate and make template so we don't miss any changes.
2. I'm wondering if we should actually include the templates in `make generate` (can still have the separate target of course).
**TODOs**:
/hold
=> 🌱 Add the cluster templates back

pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go, pkg/cloud/services/networking/floatingip_test.go, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/trunk_test.go
The `mock` import doesn't appear to conflict with anything. Remove the aliasing to `mock_clients` as it's unnecessary.
N/A
N/A
**TODOs**:
/hold
=> 🌱 Remove unnecessary mock import aliases

pkg/cloud/services/compute/instance.go
Seems like the code got moved around, while checking for a condition
haven't, this commit makes sure we error out when instance we're
creating has no AccessIPv4 address candidate.
```release-note
NONE
```
=> Fix accesIPv4 checking

docs/book/src/development/development.md
OpenStack prerequisites to run e2e test in locally are unsufficient, so we add more information in the development document.
We clarified prerequisites by reference to hack/ci scripts and trial and error.
I worked with @h1r0mu-nic to submit this PR.
Fixes #1356
**TODOs**:
/hold
=> :book: Add more infomation to run e2e test in locally

api/v1alpha6/openstackmachine_types.go, controllers/openstackmachine_controller.go, controllers/openstackmachine_controller_test.go
With this PR we set `failureReason` & `failureMessage` of the OpenStackMachine for the following three cases:
* Instance not found
* Instance in ERROR state
* as pointed out in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1116#issuecomment-1029792653, unsure if we should really stop reconciliation. However, keeping this to remain with the same behavior.
* json marshalling or unmarshalling error in the network status
Fixes #1116 
* Introduced separate functions for setting the `failureReason`& `failureMessage` to have a choice when …
=> 🐛 openstackmachine: do not set transient error message and reason

pkg/clients/loadbalancer.go, pkg/clients/mock/loadbalancer.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go
We were hitting the compute endpoint instead of the octavia endpoint when fetching octavia versions.
This is used to detect if Octavia supports allowed CIDRs, so presumably that feature is broken.
Fixes #1384
/hold
=>  🐛 Fix Octavia versions endpoint

pkg/cloud/services/networking/floatingip.go
The configured backoff was checking for floating IP status only every 30 seconds. This changes it to an exponential backoff starting at 1 second and doubling at each iteration to a maximum of 30 seconds.
/hold
=> 🐛 Decrease initial backoff for Floating IP operations

hack/ci/cloud-init/controller.yaml.tpl
We are currently using the ML2-OVS neutron, not ML2-OVN. It doesn't make sense to enable the router-ovn service and should actually result in an error [1]. Don't do it.
[1] https://bugs.launchpad.net/neutron/+bug/1997970
Fixes #1397
None.
**TODOs**:
N/A.
=> 🐛 Don't enable router-ovn service in CI deployments

hack/ci/create_devstack.sh
Hoping this might help us debug #1397 and similar future issues.
/hold
=> 🌱Ensure we capture early devstack logs

pkg/cloud/services/networking/securitygroups_rules.go
This PR adds a security group rule to allow UDP over nodeports.
Currently CAPO only allows TCP traffic to pass.
Fixes #1395
N/A
**TODOs**:
/hold
=> 🐛 Allow UDP traffic over nodeports

scripts/ci-conformance.sh, scripts/ci-e2e.sh
apt does not have stable CLI, and should not be used in scripts directly. Apt prints out warnings about it on each invocation. Replace apt with apt-get.
=> 🌱 scripts: replace apt with apt-get 

.gitignore, Makefile, scripts/ci-e2e.sh, test/e2e/data/e2e_conf.yaml, test/e2e/data/kustomize/default/kustomization.yaml, test/e2e/data/kustomize/upgrade-patches/ci-hack-kcp.yaml, test/e2e/data/kustomize/upgrade-patches/ci-hack-kct.yaml, test/e2e/data/kustomize/upgrade-patches/kustomization.yaml, test/e2e/data/kustomize/v1alpha5/kustomization.yaml, test/e2e/shared/defaults.go, test/e2e/suites/e2e/clusterctl_upgrade_test.go
This adds e2e clusterctl upgrade tests from the CAPI e2e framework. Having a clusterctl upgrade test is very important for verifying upgrades between API versions.
The CAPI [clusterctl upgrade test spec](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.2/test/e2e/clusterctl_upgrade.go) is a bit special since it creates not just a workload cluster, but a secondary management cluster also. The flow goes like this:
1. From the bootstrap cluster, create secondary management cluster with older CAPI/CAPO
2. From the secondary management cluster, create a workload cluster to check that the older versions are working correctly
3. Run clusterctl upgrade for the secondary management cluster (this requires a way to get the e2e image to the node …
=> 🌱 Add e2e clusterctl upgrade tests

test/e2e/suites/e2e/clusterctl_upgrade_test.go
The ClusterctlUpgradeSpec contains a BeforeEach block so it cannot be nested in an It block.
Fixes #
**TODOs**:
/hold
=> 🌱 Remove It block from clusterctl upgrade

test/e2e/shared/cluster.go, test/e2e/shared/common.go, test/e2e/shared/openstack.go, test/e2e/shared/suite.go, test/e2e/suites/e2e/clusterctl_upgrade_test.go, test/e2e/suites/e2e/e2e_test.go
Changes the e2e logging solution to avoid `By`, since `By` can only be used inside `It` blocks and similar.
Reverted the [workaround for clusterctl upgrade](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1412) also.
Fixes #1414
**TODOs**:
/hold
=> 🌱 e2e: Change logging to avoid use of By

test/e2e/shared/cluster.go, test/e2e/shared/common.go, test/e2e/shared/openstack.go, test/e2e/shared/suite.go, test/e2e/suites/e2e/clusterctl_upgrade_test.go, test/e2e/suites/e2e/e2e_test.go
This cherry picks #1412 and #1417 from main.
/hold
=>  🌱 Backport E2E test fixes 

pkg/utils/errors/errors.go
As [discussed here](https://github.com/gophercloud/gophercloud/issues/2279) gophercloud is not consistent in whether it returns `error` or `*error`. [IsNotFound](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/ba962696a8affa2fde65232ed4d28bf241b5ddab/pkg/utils/errors/errors.go#L35-L36) currently assumes that the error it has been given is not a pointer, and will incorrectly return false if it is a pointer.
Rather than audit CAPO to determine all the possible sources of errors we pass to IsNotFound and checking gophercloud to ensure they are not pointers, this change simply checks both.
/hold
/cc @pierreprinetti
=> 🌱Be more robust when checking gophercloud errors in IsNotFound

pkg/cloud/services/loadbalancer/loadbalancer.go
in the initial reconciliation loop, a nil-pointer occurs if the cluster is configured with a bastion host. In this initial run the status field is still empty.
Signed-off-by: Mario Constanti <mario@constanti.de>
Fixes #1438
As i don't have any access to an Openstack installation ATM i can't verify the PR on a running system.
**TODOs**:
/hold
=> 🐛 fix nil-pointer in initial reconciliation loop with empty status field

hack/ci/cloud-init/controller.yaml.tpl, kustomize/v1alpha5/external-cloud-provider/patch-ccm.yaml, kustomize/v1alpha6/external-cloud-provider/patch-ccm.yaml, templates/cluster-template-external-cloud-provider.yaml, test/e2e/data/e2e_conf.yaml, test/e2e/data/kustomize/common-patches/containerd-kcp.yaml, test/e2e/data/kustomize/common-patches/containerd-kct.yaml, test/e2e/data/kustomize/common-patches/kustomization.yaml, test/e2e/data/kustomize/external-cloud-provider/kustomization.yaml, test/e2e/data/kustomize/external-cloud-provider/patch-ccm-cloud-config.yaml, test/e2e/data/kustomize/external-cloud-provider/patch-ccm.yaml
This changes the image we use for e2e tests to a plain ubuntu cloud image. That way the cloud-init script that installs/upgrades kubeadm will not have any issues with pre-existing versions. The drawback is that we must always set `USE_CI_ARTIFACTS=true` for all tests sine there is no "default" kubernetes tools installed in the image to fall back on. However, we already do this in practice so there is no real change.
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6af7e0193c89a5617fd34e5761b24719a304d697/test/e2e/suites/e2e/e2e_test.go#L81
Fixes #1429 
**Special notes …
=> 🌱 E2e: Use plain ubuntu cloud image

test/e2e/data/kustomize/common-patches/containerd-kcp.yaml, test/e2e/data/kustomize/common-patches/containerd-kct.yaml
For some reason the kubeadm v1.25 package pulls in cri-tools v1.26. This is not compatible with containerd <v1.6. To work around this I use containerd from the docker repositories where v1.6 is available.
~~This should fix the e2e tests by installing a newer version of containerd.
I went with newer containerd instead of older cri-tools for two reasons.~~
1. ~~cri-tools are "not installed by us", i.e. they are installed by the script we get from CAPI~~
2. ~~we would anyway need the newer version as soon as we go to k8s v1.26.~~
The above did not work. Instead I went with installing the specific version of cri-tools that matches kubeadm.
Here is the documented change in v1.26: https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#c …
=> 🌱 Use newer containerd in e2e tests

config/manager/manager.yaml
Adding explicit securitycontext ensures the CAPO controller will run as non-root, without special capabilities. Those are often also the defaults but being explicit avoids reliance on fallback values, and enables further hardening by making it possible to apply strict Pod Security Standards for CAPO namespace etc.
In addition, adding seccompProfile of RuntimeDefault adds runtime specific syscall filtering (mostly off-limit by not having capability in the first place) but also couple other, non-namespaced syscalls. In general, very safe set to be filtered.
There is good discussion and reference links in similar CAPI PR at: https://github.com/kubernetes-sigs/cluster-api/pull/7831
Also, reindent the command block properly.
=> ✨ add explicit securitycontext to controller

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/clients/compute.go, pkg/clients/mock/compute.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go
check flavor and reject flavor with VCPUs < 2 to align with kubeadm checks 
Fixes #1450 
**TODOs**:
/hold
=> check flavor and reject CPUs less than 2

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackmachine_controller.go, main.go, pkg/clients/compute.go, pkg/clients/image.go, pkg/clients/loadbalancer.go, pkg/clients/networking.go, pkg/clients/volume.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go, pkg/cloud/services/loadbalancer/service.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/service.go, pkg/scope/mock.go, pkg/scope/provider.go, pkg/scope/scope.go, test/e2e/shared/openstack.go
The purpose of this PR is to be able to run envtests using mock clients instead of real ones. This PR achieves that by enhancing Scope to return service clients. We add a new scope Factory interface to generate Scopes. We provide 2 implementations of Factory:
ProviderScopeFactory generates 'real' Scopes which expect to be able to make API calls to a running OpenStack cloud.
MockScopeFactory uses mock clients.
Because Scopes now return clients, the scope package must import those clients. However, clients are currently in their service packages. Services use scopes and must therefore import the scope package. This is a circular dependency. To avoid this we move clients into a separate package.
With the exception of the new factory interface, all …
=> Envtest mocks

test/e2e/data/e2e_conf.yaml, test/e2e/suites/e2e/self_hosted_test.go
Adds e2e self hosted test. This is a test spec [implemented in CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/self_hosted.go) that checks the `clusterctl move` functionality, i.e. that the controllers can be moved from the bootstrap cluster to a workload cluster. It also checks that the controllers are functioning in the new cluster, and can handle node rotations, by doing a k8s upgrade.
Part of #1363
2. This would not be part of …
=> 🌱 Add e2e self hosted test

Makefile, test/e2e/data/e2e_conf.yaml, test/e2e/data/kustomize/kcp-remediation/kustomization.yaml, test/e2e/data/kustomize/kcp-remediation/mhc.yaml, test/e2e/data/kustomize/md-remediation/kustomization.yaml, test/e2e/data/kustomize/md-remediation/md.yaml, test/e2e/data/kustomize/md-remediation/mhc.yaml, test/e2e/shared/defaults.go, test/e2e/suites/e2e/mhc_remediations_test.go
This adds the CAPI e2e framework remediation tests. There are two tests, one for MachineDeployment and one for KubeadmControlPlane. They simply check that the MachineHealthcheck works as expected, i.e. when a Machine becomes unhealthy, it (and its underlying OpenstackMachine) is properly deleted and a new is created to take its place.
While this is mostly a CAPI feature, it can be good to check also in CAPO that it works as expected.
Part of #1363 
2. I …
=> Add e2e remediation tests

tilt-provider.json
Following https://github.com/kubernetes-sigs/cluster-api/pull/5217, tilt expects a label field in tilt-provider files
The documentation for reference: https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-provider-configuration
Fixes #
**TODOs**:
/hold
=> 🐛 Fix Tilt by adding CAPO label in tilt-provider.json

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go
This avoids an extremely surprising write-after-read consistency bug when later returning after making subsequent object changes.
The issue stems from the fact that we don't write to the same place we read from. We read from a cache: a shared informer which is populated from a watch running against the apiserver. However we write directly to the apiserver rather than writing through the cache.
If we patch the watched object without returning, while we continue to execute the change will be written to the api server and will propagate to our own shared informer. This change will result in a new reconcile being queued for this version of the object which now has a Finalizer but no other changes.
Taking the case of the machine controller we will then go on to create a server and we will …
=> 🐛 Return from reconciler after adding finalizer

docs/book/src/clusteropenstack/configuration.md
This PR is a follow up for: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1440 
It adds the documentation about the `--ca-cert` flag added in this PR. 
**Which issue(s) this PR fixes** *
Fixes: #1439
**TODOs**:
/hold
=> 📖 Add documentation about --ca-cert flag

go.mod, go.sum
This includes support for value_specs for Ports, that is needed for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1452.
Fixes #
**TODOs**:
/hold
=> 🌱 Bump gophercloud to v1.2.0

hack/boilerplate/boilerplate.py, hack/verify-boilerplate.sh
Fixes a bug introduced by #1470 which meant that the boilerplate linter was no longer checking anything.
/hold
=> Fix boilerplate linter

test/e2e/shared/common.go, test/e2e/shared/context.go, test/e2e/shared/openstack.go, test/e2e/shared/suite.go
The resource and machine tickers are responsible for fetching logs every 5 and 10 seconds respectively during a test run. Each fetch overwrites the previous one. These are problematic because they cause failure state to be overwritten by logs captured during deletion. That is, if a test ends in failure, we continue to capture these logs regularly during cleanup. This causes the test failure state to be overwritten by the state during cleanup.
We already capture these resources after each test regardless of success or failure, so regular capture during the test is redundant. This change simply removes the tickers. We still get the same logs when we execute DumpSpecResourcesAndCleanup() after each test.
Additionally, if there is an error during cleanup we optionally capture that state too, …
=> Remove the resource and machine tickers from e2e tests

test/e2e/shared/common.go, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
We see lots of instances of log messages in e2e logs of the form:
```
error getting internal ip for server cluster-e2e-l7xvyz-control-plane-hnj96: internal ip doesn't exist (yet)
```
These are because GetOpenStackServers(), which is called after every test completes, fetches *all* OpenStack servers, not just those for the current cluster. The above log message is displayed when it doesn't find an interface for the server on the current cluster's internal network.
This change cuts down the noise by passing in an explicit list of machine names to return. We still fetch all servers, but we filter them after fetching.
/hold
=> Fix "internal ip doesn't exist (yet)" in e2e logs

api/v1alpha6/openstackcluster_webhook.go, api/v1alpha6/openstackcluster_webhook_test.go, pkg/cloud/services/compute/availabilityzone.go
CAPO uses any ZA it finds, rather than checking whether the ZA is actually available, meaning you can get into a state where it's impossible to provision a cluster.  This allows clients to filter based on AZ availability before scheduling.
Fixes #1477
Discussion in #1477 
Fixes #
**TODOs**:
- [x ] squashed commits
/hold
=> :bug: Fix Provisioning to Unavailable AZs

pkg/cloud/services/networking/securitygroups_rules.go
This PR fixes a regression where we started using `ipip` instead of `4` for the security groups.  Inside Linux, the protocol `ipip` maps to protocol number `94` which is what Neutron uses when you use that, which meant that all Calico IPIP connectivity stopped working with this change
```
root@abb2f5652d8f:/# egrep '^(ipencap|ipip)' /etc/protocols
ipencap	4	IP-ENCAP	# IP encapsulated in IP (officially ``IP'')
ipip	94	IPIP		# IP-within-IP Encapsulation Protocol
```
Unfortunately, the Neutron API does not accept `ipencap` therefore we should go back to putting the digit to make things work again.
Related: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1290
Fixes #1484 
**Special notes for your …
=> 🐛 Switch to "4" instead of "ipip" for rules

pkg/cloud/services/networking/securitygroups.go
Fixes: #1475 
Fixes #
**TODOs**:
/hold
=> fix: fix typo of worker rules and controller rules

README.md, pkg/clients/compute.go
This bumps the minimum supported micro-version to one that would support mulit-attach, but also happens to be the most recent EOL release of OpenStack
Fixes #1496
**TODOs**:
/hold
=> 🐛 fix: allow using multiattach volume types

api/v1alpha6/conversion_test.go
As there are no API differences yet between v1alpha6 and v1alpha7, no special fuzzers are needed. The tests check hub-spoke-hub and spoke-hub-spoke conversions.
Related to #1508 
2. I started on this as part of #1291, but decided it makes more sense to add the tests in a separate PR. I'll update the tests in #1291 with the necessary changes when this is merged.
**TODOs**:
/hold
=> 🌱 Add fuzzy conversion tests for v1alpha6

api/v1alpha4/types.go, api/v1alpha4/zz_generated.conversion.go, api/v1alpha4/zz_generated.deepcopy.go, api/v1alpha5/types.go, api/v1alpha5/zz_generated.conversion.go, api/v1alpha5/zz_generated.deepcopy.go, api/v1alpha6/types.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha6/zz_generated.deepcopy.go, api/v1alpha7/types.go, api/v1alpha7/zz_generated.deepcopy.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
This changes `PortOpts.SecurityGroups` from `*[]string` to `[]string`. Note that this make no changes to the CRDs. As it only affects Go marshalling it's effectively an internal change.
We make the change to all historic API versions to simplify conversion. It isn't a change to those APIs because their CRDs remain unchanged.
/hold
=> 🌱 Un-pointer PortOpts.SecurityGroups

api/v1alpha6/conversion.go, api/v1alpha6/conversion_test.go
From v1alpha6 onwards we have the facility to losslessly preserve values during conversion which were added or removed in the new version, so we should never require the FuzzerFuncs argument to the fuzzer conversion tests.
/hold
=> Restore APIServerLoadBalancer.Provider on up-conversion

go.mod, go.sum
Bump docker/docker to close three public vulnerabilities.
- https://osv.dev/vulnerability/GHSA-232p-vwff-86mp
- https://osv.dev/vulnerability/GHSA-33pg-m6jh-5237
- https://osv.dev/vulnerability/GHSA-6wrf-mxfj-pf5p
=> 🌱 bump docker to 20.10.24+incompatible

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: This PR brings the [new Flatcar stable](https://www.flatcar.org/releases#stable-release) version in the CI - for now it runs from a non-official bucket, just for running the tests.
**Special notes for your reviewer**: Hello @tobiasgiese, any chance to upload the image on the dedicated bucket please?
**TODOs**:
/hold
=> :seedling: ci: bump flatcar to latest major stable

controllers/openstackcluster_controller.go, docs/book/src/clusteropenstack/configuration.md, go.mod, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/router.go
NetworkID is a required field when creating a neutron port. We previously passed on this requirement in the Ports API. However we didn't have this restriction in the Networks API and inferred the network from a subnet if one was defined. This change eases the transition from Networks to Ports by removing this restriction for Ports.
**TODOs**:
/hold
=> ✨Infer port network from subnet

api/v1alpha4/conversion_test.go, api/v1alpha4/zz_generated.conversion.go, api/v1alpha5/conversion.go, api/v1alpha5/zz_generated.conversion.go, api/v1alpha6/conversion.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/types.go, api/v1alpha7/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
This adds support for [propagate_uplink_status](https://docs.openstack.org/heat/zed/template_guide/openstack.html#OS::Neutron::Port-prop-propagate_uplink_status) on ports.
Fixes #1480 
**TODOs**:
/hold
=> ✨ Support propagate uplink status

templates/create_cloud_conf.sh, templates/env.rc
It fixes the following erroneous situations:
1. Scripts are run from macOS where base64 supports `--break` instead of `--wrap`
2. For security reasons OpenStack password is present in `OS_PASSWORD` environment variable rather than clouds.yaml
Fixes #
**TODOs**:
/hold
=> 🐛 Improve `env.rc` and `create_cloud_conf.sh` templates

pkg/cloud/services/loadbalancer/loadbalancer.go
`record.Infof()` and `record.Warnf()` both create an event, so there's no need to use both at the same time. This commit removes one such occurrence.
**TODOs**:
/hold
=> 🌱 Remove creation of 2 Events for the same event

OWNERS, OWNERS_ALIASES
For a long time, in addition to the CAPO maintainers we have also allowed approvals from:
- sig-cluster-lifecycle-leads
- cluster-api-admins
- cluster-api-maintainers
However, we have to maintain these lists manually and our record of doing this has not been good. In practise there is also significant overlap in these groups.
As far as I am aware this facility has never been used, but it is easy to imagine a circumstance where it might be useful, e.g. a centrally coordinated CVE affecting multiple providers urgently. Allowing commits from CAPI maintainers should cover this use case in practise, and removing the other 2 lists reduces the amount of copy/paste we need to maintain from other projects.
/hold
=> Update external approvers

go.mod, go.sum
Bump docker/distribution to 2.8.2+incompatible for https://osv.dev/vulnerability/GHSA-hqxw-f8mx-cpmw
=> :seedling: bump docker distribution to 2.8.2+incompatible

Makefile, test/e2e/data/e2e_conf.yaml, test/e2e/suites/e2e/clusterctl_upgrade_test.go
- Bump clusterctl upgrade v0.7 test to start from v0.7.2
- Sync and bump cert-manager version in Makefile and e2e_conf.yaml
- Sync CAPI container tags in Makefile and e2e_conf.yaml
Fixes #
**TODOs**:
/hold
=> 🌱 E2e: Bump clusterctl upgrade to start from v0.7.2

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, pkg/cloud/services/networking/network.go
Fixes a bug introduced in #1519: previously when fetching cluster subnets we filtered subnet by the cluster network id. #1519 broke that, which caused a failure due to matching too many subnets.
We additionally add an envtest which asserts the fix.
Fixes #1570
/hold
=> 🐛 Always filter cluster subnets by cluster network ID

api/v1alpha5/zz_generated.conversion.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, docs/book/src/topics/crd-changes/v1alpha6-to-v1alpha7.md, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
Setting this value requires admin privileges and serves no purpose in CAPO.
/hold
=> ⚠️ Remove ProjectID from PortOpts

controllers/openstackcluster_controller.go
There's a race where the infrastructure can be deleted before the machines, but the deletion of machines is dependent on the infrastruture, and we get stuck deleting forever (unless you manually delete the machines from Nova and remove the finalizer).  Simple fix is to defer deletion of infrastructure until the machines have been purged.
Fixes #1578 
**TODOs**:
/hold
=> 🐛 Fix deadlock

controllers/openstackcluster_controller.go
There's a race where the infrastructure can be deleted before the machines, but the deletion of machines is dependent on the infrastruture, and we get stuck deleting forever (unless you manually delete the machines from Nova and remove the finalizer).  Simple fix is to defer deletion of infrastructure until the machines have been purged.
Backport of #1579
Fixes #1578
**TODOs**:
/hold
=> 🐛 Fix Deletion Deadlock Part Deux

api/v1alpha7/openstackmachine_webhook.go, controllers/openstackcluster_controller.go, go.mod
The package [pkg/errors](https://github.com/pkg/errors) has served its purpose and its proposed changes have been incorporated into Go's standard library in Go v1.13.
This change removes it as a direct dependency, replacing its functionality with the corresponding features of `fmt` and `errors`.
The old `pkg/errors` defined the method `Cause() error`, whereas the stdlib incorporated its functionality with the method `Unwrap() error`. As such, if a consumer of CAPO directly called `errors.Cause(err)` to match the causing error, then their code would silently break because the underlying sentinel error wouldn't be identified.
This problem is susceptible to affect any code that uses CAPO as a library, that uses  a …
=> 🌱 Replace github.com/pkg/errors

pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/securitygroups_rules.go
=> :sparkles: Add additional sec group rule for additionalPorts of LB

scripts/ci-e2e.sh, test/e2e/shared/common.go, test/e2e/shared/suite.go
CAPI provides an interface LogCollector that the providers can implement to get provider specific logs from the CAPI test specs. This gives us logs from the clusterctl upgrade, self-hosted and remediation tests.
Moves the `capo-e2e-image.tar` out of the `_artifacts` since we do not need to save this with the logs. It just takes up space for no reason.
Fixes #
**TODOs**:
/hold
=> 🌱 E2e: Implement LogCollector interface

README.md, hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
This bumps the tested Kubernetes version to v1.27.2. It also adds v1.27 to the list of compatible versions and removes v1.21. This is just to keep the table from growing too much. The v1.21 is anyway out of support.
Fixes #
**TODOs**:
/hold
=> 🌱 E2e: Bump the tested Kubernetes versions

test/e2e/shared/common.go, test/e2e/shared/openstack.go, test/e2e/shared/suite.go, test/e2e/suites/e2e/e2e_test.go
This is a follow up to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1581.
This unifies the e2e log collection for machines so that it uses the LogCollector interface. It removes the instance.log which was just showing the ID of the openstack server and simplifies the code a bit.
Fixes #
**TODOs**:
/hold
=> 🌱 E2e: Unify machine log collection

metadata.yaml, test/e2e/data/e2e_conf.yaml, test/e2e/data/shared/v1beta1_provider/metadata.yaml
Adds/updates metadata which needs to exist before branching release-0.8
/hold
=> 🌱 Add metadata for release 0.8

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
Hey, there is new Flatcar stable release (https://github.com/flatcar/Flatcar/issues/1106) - it mainly brings Kernel security fixes. Bumped the Kubernetes version to 1.27.3 too. 
NOTE: Here's a small documentation for Flatcar / CAPO maintainers if someone wants to do it next time: https://gist.github.com/tormath1/acbae5c6cd12420bb8ea137e25655c99
**TODOs**:
/hold
=> :seedling: ci: bump flatcar to latest stable

pkg/scope/provider.go
As a public cloud operator it strikes me as odd that I have to supply a CA certificate for every cluster that's created.  This leads to a bunch of code that has to Dial the endpoint and extract the root CA (rather than hard coding it - ugh!).  The whole point of the distroless base container image is to distribute TLS root CAs, so allow the option to use what's already present.
As stated in the commit message.
None
**TODOs**:
/hold
=> :sparkles: Allow Use of Public CAs

api/v1alpha7/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Fixes #1608 
we made it subnets now , seems we can't get it if it's CRD 
https://github.com/kubernetes-sigs/controller-tools/issues/652
so remove seems better than show nothing ..
```
type NetworkStatusWithSubnets struct {
NetworkStatus `json:",inline"`
// Subnets is a list of subnets associated with the default cluster network. Machines which use the default cluster network will get an address from all of these subnets.
Subnets []Subnet `json:"subnets,omitempty"`
}
```
1. Please confirm that if this PR changes any image versions, then that's the sole change …
=> remove subnet from the output in `kubectl get`

api/v1alpha5/types.go, api/v1alpha5/zz_generated.deepcopy.go, api/v1alpha6/types.go, api/v1alpha6/zz_generated.deepcopy.go
These both have a type of pointer to slice, which is:
* Redundant in Go
* Is marshalled identically in the CRD to a slice with no pointer
To verify the latter, note that there are no changes to the CRD despite the type change.
Also note that the values are unused.
The reason for fixing these types is that Semantic.DeepEqual can't compare them correctly so they break the fuzzer tests.
/hold
=> 🌱 Simplify types of Instance.SecurityGroup and Instance.Networks

pkg/scope/provider.go
At the moment, we do not modify the user agent for all API requests we make which make it hard to identify if certain requests were done by CAPO or not.
This change prepends the CAPO version to the Gophercloud user agent which will give plenty of benefits.
Fixes #1611 
**TODOs**:
/hold
=> 🌱 chore: use capo cluster agent for API requests

pkg/cloud/services/compute/instance_types.go, pkg/cloud/services/compute/instance_types_test.go
Dual-stack clusters require that the Machine's status contains the
IPv6 address. This commit removed the check that would skip the addition
of IPv6 to the Machines. Also, it ensures the IPv4 addresses of each
Network remains being the first ones listed in the Machines given there are
operations that rely on the first address of each network.
=> ✨ Add support to IPv6 in Machine's status

main.go
Add a `--version` flag that, when used, will dump the version set on the binary. This provides a quick and easy way to check the version of the binary from the command line.
N/A
N/A
**TODOs**:
/hold
=> ✨ Add `--version` flag

controllers/openstackmachine_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go
**What this PR does / why we need it**: 
It fixes the format of the log messages and log parameters. Following the guidelines [here](https://main.cluster-api.sigs.k8s.io/developer/logging.html) and [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md). Part of the process to fix issue #1314.
=> :seedling: Migrating /pkg/cloud/services/loadbalancer/loadbalancer.go and /controllers/openstackmachine_controller.go to structured logging

controllers/openstackcluster_controller.go
Adjusted syntax of openstackcluster_controller.go logging messages to match the guidelines as outlined in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
/hold
=> 🌱Migrate controllers/openstackcluster_controller.go to structured logging

api/v1alpha6/conversion.go
APIServerLoadBalancer.Provider patch is backported to v1alpha6 in PR
#1529. We don't need up conversion for it anymore.
Fixes #
**TODOs**:
/hold
=> 🌱Remove APIServerLoadBalancer.Provider Up Conversion

templates/env.rc
This allows users to utilise authentication via application credentials again rather than expecting them to use passwords.
Specifically, users that use a cloud.conf with application credentials would run into an error such as:
```
$ source ./templates/env.rc ~/.config/openstack/clouds.yaml example
Error: Value for env variable 'PASSWORD' not provided in env()
```
with the resulting `CAPO_OPENSTACK_CLOUD_YAML_SELECTED_CLOUD_B64` environment variable containing content similar to:
```
clouds:
example:
```
This commit only includes the password if it does indeed have a value, to ensure that the cloud config file can be rendered correctly.
The erroneous behaviour was introduced in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/138 …
=> 🐛  Fix application credential support in env.rc

docs/book/src/clusteropenstack/configuration.md
This PR fix the documentation about "Use an existing Router". the book  say that the apiversion v1alpha6 support an existing router but that's not true : 
```bash
k explain --api-version=infrastructure.cluster.x-k8s.io/v1alpha6 openstackcluster.spec.router
GROUP:      infrastructure.cluster.x-k8s.io
KIND:       OpenStackCluster
VERSION:    v1alpha6
error: field "router" does not exist
```
The spec.router exists since the apiversion v1alpha7 : [Router in OpenStackCluster struct](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/api/v1alpha7/openstackcluster_types.go#L45l)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
=> 📖 Fix APIVersion to use existing router with OpenStackCluster

pkg/cloud/services/compute/instance.go
Checked and updated verbosity levels in cluster-api-provider-openstack/pkg/cloud/services/compute/instance.go to adhere to the guideline https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
**Which issue(s) this PR fixes** :
Fixes #<1> add `V(2)` to`s.scope.Logger().Info("using existing root volume %s", name)` 
This message should be important to system administrators or operators as it indicates a specific action taken by the system. However, it may not be critical for every developer or user to see this message, hence the choice of verbosity level 2.
Fixes #<2> add `V(4)` to `s.scope.Logger().Info("deleting dangling root volume %s(%s)", volume.Name, volume.ID)`
Since deleting such resources can …
=> 🌱 Update verbosity levels in instance.go

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
When an instance fails to come up, there's a bug where the port doesn't get cleaned up, and eventually you will exhaust your quota. The code does attempt to garbage collect, but I suspect at some point in the past ports were suffixed with an index, but the garbage collection code wasn't made aware of this, so lists nothing. Replace the APi "filtering" that doesn't work with a manual filter that does prefix matching.
Fixes #1404
**TODOs**: …
=> :bug: Fix Port Leaks

.golangci.yml, api/v1alpha6/conversion.go, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, hack/tools/Makefile, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/router.go, test/e2e/shared/defaults.go
Note that this disables depguard which we had previously explicitly enabled but we don't seem to have a config for. With this upgrade and with no config it complains about all imports. It looks potentially useful to avoid accidental problematic imports like Hashicorp, but we can look into that separately.
/hold
=> 🌱 Bump golangci-lint to 1.54.2

test/e2e/data/e2e_conf.yaml
=> 🐛Fix failing clusterctl upgrade test (second attempt)

controllers/openstackmachine_controller.go
=> 🐛 Fix panic on delete before cluster is initialised

pkg/cloud/services/compute/instance.go, pkg/cloud/services/networking/floatingip.go, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/service.go
What this PR does / why we need it:
Fix up the string formatting log messages so that they use structured logging as documented here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
=> 🌱Structured logging migration of instance.go, service.go, floatingip.go, and securitygroups.go

pkg/cloud/services/networking/trunk.go
this is from code read when doing other PR 
seems we have event https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/networking/trunk.go#L73 so no need duplicate event to confuse admin
Fixes #
**TODOs**:
/hold
=> avoid duplicate error event

api/v1alpha7/openstackcluster_webhook.go
…affic
It allows the change on `spec.allowAllInClusterTraffic` of `OpenstackCluster` CRs.
Fixes #1653
**TODOs**:
/hold
=> ✨Allow changing allowAllInClusterTraffic in a deployed cluster

api/v1alpha7/conditions_consts.go, controllers/openstackmachine_controller.go
Setting a failure message is permanent and requires user action to get
rid of. We cannot know if the error is permanent though. The idea with
this commit is that if the machine has a nodeRef, we know that the
instance was working at some point, so the error could well be
temporary. Therefore we do not set failure in this case.
On the other hand, if the machine does not have a nodeRef, we set
failure since it is more likely that there is some configuration error
that will not go away.
Fixes #1582 . For more details please read my comment on that issue.
**TODOs**:
/hold
=> Set failure only on instance error when no nodeRef

RELEASE.md
This clarifies the content of release notes for releases and pre-releases.
The change is motivated by the understanding that a significant number of users will only ever upgrade from one stable release to the next, without necessarily being aware of the changes in the interim pre-releases.
These users would have previously had to review not only the release notes of the release they are upgrading to, but also those of all interim pre-releases. A process that is at best arduous, and at worst would have led to them missing important information.
Another nice side-effect of this change is that community contributions are highlighted in a prominent place even if they had been included in a pre-release already.
See …
=> :book: Clarify release notes content for releases and pre-releases

controllers/openstackcluster_controller.go
Change https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1260 was added as a stop-gap to clean up after errors in the machine controller which left dangling ports in the cluster network. These dangling ports prevent the deletion of the network. It works by deleting all ports in the cluster network.
This makes sense when the cluster network is about to be deleted, but not when the cluster network is a BYO network with non-CAPO managed resources in it. We should not call this method on a BYO network.
Fixes #1679
/hold
=> 🐛 Only delete all ports when deleting cluster network

go.mod, go.sum
Update Gophercloud to the latest stable tag which was released today.
This will fix a few bugs and also add more capabilities that'll needed soon.
=> Update Gophercloud to 1.7.0

.gitignore
CAPO doesn't use vendoring, so let's ignore that directory from git.
That will prevent someone from committing it.
=> 🌱 gitignore: ignore vendor/ directory

hack/boilerplate/boilerplate.py
This allows `make verify-boilerplate` to pass when using vendoring.
=> 🌱 Ignore vendor directories in boilerplate check

pkg/clients/mock/doc.go
This allows mockgen to run when using vendoring.
=> 🌱 Add explicit dependency on github.com/golang/mock/mockgen/model

hack/ci/create_devstack.sh, hack/ci/gce-project.sh, hack/ensure-kubectl.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh
This PR contains several critical fixes, all of which are required for passing CI.
Firstly, fixes several issues which seem to stem from a bump in the base prow image.
Secondly, reverts the effect of #1716 by putting the devstack image back to Ubuntu 20.04. Devstack for OpenStack Yoga does not support Ubuntu 22.04.
Lastly, fixes a GCE provisioning issue which prevented #1716 from being tested properly. It looks like we could non-deterministically reuse an old disk image depending on which zone we landed in, meaning we were not necessarily testing the change in the PR under test.
Fixes: #1717 
/hold
=> 🌱 ci: Several CI fixes

main.go, pkg/scope/mock.go, pkg/scope/provider.go, pkg/scope/scope.go
=> ✨ Add cache on provider scope

.golangci.yml, Containerfile, Dockerfile, versions.mk
Bump Golang to 1.20.10, we'll need it for bumping other dependencies like CAPI.
=> ⚠️  Bump Go to 1.20.10

pkg/clients/compute.go, pkg/clients/image.go, pkg/clients/loadbalancer.go, pkg/clients/networking.go, pkg/clients/volume.go, pkg/scope/provider.go
Cloud configuration allows to set endpoint type option, however it leaves are out luck to be used in service configuration, this PR is going to fix this behaviour and pass endpoint type to all the clients.
Fix: #1747
Yes
About tests: I would probably like to add them, but there's no clean way for that because client constructors are impacted and there's no DI in use in that place.
**TODOs**:
/hold
=> 🐛Fix missing endpoint type in OpenStack endpoint clients configuration

test/e2e/data/e2e_conf.yaml, test/e2e/suites/e2e/e2e_suite_test.go
Fix misconfigured logger
Fixes #1698
**TODOs**:
/hold
=> 🐛  Update e2e testing image of CAPI version from 1.5.0 to 1.5.1 

docs/book/src/clusteropenstack/configuration.md, versions.mk
Update the docs to reflects changes introduced in API v1alpha7. While here we also fix some other issues with the docs and bump the version of mkdocs.
n/a
n/a
**TODOs**:
/hold
=> 📖 Fix network-related docs for API v1alpha7

pkg/scope/provider.go
If no certificate is set to `OPENSTACK_CLOUD_CACERT_B64` env variable, it defaults to an empty string encoded. This can cause failure to connect to OpenStack API when it uses a certificate bundle that is supplied by the OS, instead of a private certificate. This commit fixes the issue by checking if the certificate was parsed successfully and if not attempts to use the host's root CA.
Fixes #1771
/hold
=>  🐛 Verify success of parsing OpenStack cloud cacert

controllers/openstackmachine_controller.go, controllers/openstackmachine_controller_test.go
Currently, if a worker machine security group is specified but a control plane machine security group is not, the worker machine SG will be be applied to both worker *and* control plane machines. Correct this mistake.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
Fixes #1784
None.
**TODOs**:
/hold
=> 🐛 Don't apply worker SG to control plane machines

RELEASE.md
Some of the links were still pointing to the old k8s.gcr.io related config, instead of registry.k8s.io.
Fixes #
**TODOs**:
=> 🌱 Update links in release docs

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/suites/e2e/e2e_suite_test.go, test/e2e/suites/e2e/e2e_test.go
Fixes #1700 
**TODOs**:
- [ X] squashed commits
/hold
=> 🌱  Make it possible to use a pre-created volume type in e2e tests 

pkg/cloud/services/compute/instance.go
The `FailedCreateServer` event was mistakenly calling the `Name()` method on the createdInstance instance, that could very well be unitialized since creation failed. Instead, log the event using the named passed in the instance spec.
Fixes #1802
**TODOs**:
=> :bug: Fix potential panic during instance create

kustomize/v1alpha8/flatcar-sysext/kustomization.yaml, kustomize/v1alpha8/flatcar-sysext/patch-flatcar.yaml, templates/cluster-template-flatcar-sysext.yaml, test/e2e/data/kustomize/flatcar-sysext/kustomization.yaml
This was added via v1alpha7 but the latest api is v1alpha8 and to keep
our CI consistent we will move the manifests to v1alpha8.
=> 🐛 Move flatcar-sysext to v1alpha8

hack/ci/create_devstack.sh, hack/ensure-kubectl.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh
fix CI to avoid --short flag  for kubectl command
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1718/files
has a bigger fix but not sure whether it has side effect, so to unblock https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1808
try fix minimal place
Fixes #
**TODOs**:
/hold
=> fix --short flag is removed issue for CI

main.go
Our controller have built-in rate limits. It throttles itself if it hits this limit. So far it has not been possible to configure these limits. This commit adds flags to the controller for setting both the QPS and the burst for the rate limits. The default remains the same as before (20 QPS, 30 burst).
Copied from https://github.com/kubernetes-sigs/cluster-api/pull/8579
Fixes #
**TODOs**:
/hold
<sub>Tobias Giese …
=> ✨ Add flags for configuring rate limits

api/v1alpha7/openstackmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, controllers/openstackmachine_controller.go, pkg/scope/mock.go, pkg/scope/provider.go, pkg/scope/scope.go
The `identityRef` attribute is marked as optional but without it we have no ability to talk to the cloud. In a future API version, we may wish to make this a required attribute but for now, provide the ability to retrieve credentials from the cluster in the absence of the machine.
Fixes #1759
~I'm not sure if we can do this. As things stand, this will cause a change in behavior (you can create a Machine without specifying an `identityRef`) between two different CAPO deployments regardless of API version selected. It might be better to instead explode early …
=> 🐛 Fall back to cluster identityRef in absence of machine identityRef

controllers/openstackmachine_controller.go
**What this PR does / why we need it**:  When a previously existing(OpenstackMachine has instanceID ref) VM vanishes (cannot be fetched from Openstack) the reconcile loop attempts recreate and update the OpenstackMachine spec (the instanceID and providerID) which is immutable. This PR disables the attempt to recreate (consistent behaviour with other broken states [example](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/dc2d0baf7a53508d2fa5ec45d605868c9d927f09/controllers/openstackmachine_controller.go#L291))
Fixes #1787
**TODOs**:
=> :bug: Fix patching OpenstackMachine's immutable spec during reconcile

pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
This adds a condition in GarbageCollectErrorInstancesPort to avoid index outOfRange error when an instance has no port because of some reason (maybe the instance provisioning failed because of infra issue).
Fixes #1805
**TODOs**:
/hold
=> 🐛 fix: skip port deletion when instances have no port

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
Both flatcar and ubuntu images are updated
/hold
=> 🌱 Bump e2e node images to v1.28.5

api/v1alpha5/types.go, api/v1alpha6/types.go, api/v1alpha7/types.go, api/v1alpha8/types.go, controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackmachine_controller.go, controllers/suite_test.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/compute/instance_types.go
Under certain circumstances, when they are non-responsive cells, nova may return a partial result instead of an error.
(this is controlled by list_records_by_skipping_down_cells parameter that is true by default - no error will be thrown)
When it faces this issue, capo controller will try to create a new server for the machine, resulting in deleting ports of existing one.
In order avoid this issue, use GET instead of LIST to retrieve server using its uuid. For that purpose we must ensure that uuid is stored in machine spec as soon as the server is created, even if server is in error state.
Fixes: #1612 
Yes …
=> 🐛 Fix random instance port deletion

README.md, docs/book/src/development/ci.md, hack/ci/aws-project.sh, hack/ci/cloud-init/controller.yaml.tpl, hack/ci/cloud-init/worker.yaml.tpl, hack/ci/create_devstack.sh, hack/ci/gce-project.sh, hack/ci/openstack.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh
Update devstack configuration to deploy OpenStack Bobcat with OVN on Ubuntu 22.04.
=> ✨ Update CI to use OpenStack Bobcat

api/v1alpha8/openstackcluster_webhook.go, api/v1alpha8/openstackcluster_webhook_test.go
CAPI appears to make implicit CP scheduling decisions based on what it's told is available by CAPO on an "LRU" basis. It also assumes an infinite sized AZ, so problems begin when the "next" AZ cannot accommodate the VM. We could manually specify an AZ that aggregates all machines explcitly, however this is another mechanism that disables scheduling by CAPI altogether and allows Nova to do what it does, along with a soft-AA rule. However, switching from CAPI scheduling to Nova scheduling is impossible as the field is immutable, so allow this.  Testing shows existing scheduled clusters undergo no topology changes, which will be due to the KCPM not taking action, but you can force the changes with a rolling upgrade of some variety. Crucially, if a cluster with CAPI scheduling gets stuck, we …
=> ✨ Allow AZs to be Omitted at Runtime

pkg/cloud/services/loadbalancer/loadbalancer.go
If loadbalancer reconciliation failed at any time after the floating IP was created, we would lead the floating IP and create a new one on the next reconciliation.
Fixes #1827
/hold
=> 🐛 Persist API FloatingIP immediately on creation

api/v1alpha5/conversion.go, api/v1alpha5/conversion_test.go, api/v1alpha5/zz_generated.conversion.go, api/v1alpha6/conversion.go, api/v1alpha6/conversion_test.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/conversion.go, api/v1alpha7/conversion_test.go, api/v1alpha7/zz_generated.conversion.go, api/v1alpha8/openstackcluster_types.go, api/v1alpha8/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/network_test.go, pkg/utils/controllers/controllers.go, pkg/utils/controllers/controllers_test.go
This commit adds support to specify more than one existent subnet on the `OpenStackCluster`.
The existent `OpenStackClusterSpec.Subnet` field that would have the following format:
```yaml
subnet:
id: a532beb0-c73a-4b5d-af66-3ad05b73d063
```
is removed in favor of the following `OpenStackClusterSpec.Subnets`: 
```yaml
subnets:
- id: a532beb0-c73a-4b5d-af66-3ad05b73d063
```
conversion from v1 alpha8 clusters that use multiple subnets won't be allowed to older releases.
**TODOs**:
=> ✨ Support BYO dual-stack Network

test/e2e/data/kustomize/common-patches/ccm/kustomization.yaml, test/e2e/data/kustomize/common-patches/ccm/patch-allow-all-in-cluster-traffic.yaml
The default rules should be sufficient for Calico which is used by e2e
clusters; let's remove the allow-all-in-cluster-traffic patch which
should not be needed.
=> e2e: remove "allow-all-in-cluster-traffic" patch

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go
Since controller-runtime kubernetes-sigs/controller-runtime#2451, a warning will be logged if a controller returns an error and a non-zero result (i.e. a result with a RequeueAfter).
It adjusts the OpenStackCluster controller to return errors first, as an error itself will already trigger a reconciliation (with exponential backoff).
Fixes #1838
=> 🐛 controllers: do not return a RequeueAfter and an error at the same time

docs/book/src/development/development.md, templates/cluster-template-development.yaml, templates/clusterclass-dev-test.yaml
This PR introduces a ClusterClass template to enhance Tilt integration with CAPO, leveraging the existing CAPI setup. It simplifies cluster creation.
Fixes #1767
**TODOs**:
/hold
=> 🌱 Enhance Tilt integration with CAPO using a ClusterClass template

docs/book/src/development/development.md, templates/clusterclass-dev-test.yaml
This adds a patch to set the image automatically based on the kubernetes version. It also removes the requirement to have the CLUSTER_NAME variable set for the ClusterClass.
Finally, the docs are updated to reflect this and with a few additions.
Fixes #
**TODOs**:
=> 🌱 Update the dev-test ClusterClass

test/e2e/suites/e2e/e2e_test.go
The e2e tests are currently very unstable. I suspect lack of resources in the devstack to be the issue. In an attempt to solve this, the number of control-plane nodes are reduced in this commit. Now only the multi-az test will use 3 CP. The rest will have 1 CP only.
Fixes #
**TODOs**:
/hold
=> 🌱 Decrease number of machines in e2e tests

Dockerfile
We change to golang 1.21(.6) in the Dockerfile to match the go.mod of the root project.
This is a prereq for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1854
N/A
**TODOs**:
/hold
=> Migrate Dockerfile to use golang 1.21 to match go.mod in project

pkg/cloud/services/loadbalancer/loadbalancer.go
When a load balancer listener fails to be created an stacktrace apperas due to an error message trying to include the name of the listener that failed to be created.
Stacktrace:
```log
I0201 14:57:33.013415       1 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/hux-lab1" namespace="default" name="hux-lab1" reconcileID="d33d5039-62bd-4efe-a004-f939ad3ac7e2"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation …
```
=> 🐛Fix a stacktrace in LB logic by removing listener name from an error message when not set

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: Bump the Flatcar major version used by the regular `flatcar` template tests.
* Note that the `flatcar-sysext` template is already consuming the new image, we have nothing to do for this one. :D 
* As usual a CAPO maintainer will need to download the image from https://test-flatcar.s3.fr-par.scw.cloud/flatcar-stable-3760.2.0-kube-v1.28.5.img to the CAPO GCS bucket
**TODOs**:
/hold
=> :seedling: test: bump Flatcar version

api/v1alpha8/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
When a reconcile loop for the bastion is requeued, we have
this error:
```
OpenStackCluster.infrastructure.cluster.x-k8s.io \"cluster-e2e-rha0r3\" is invalid: ready: Required value"
```
The OpenStackMachine.Status is false by default now, so if the status
has not been set to anything, patching the object will not fail with the
previous error.
Fixes #1841
**TODOs**:
=> 🐛 api: openstackcluster.status default to false

controllers/openstackfloatingippool_controller.go
Checks kind index for IPAddresses in OpenStackFloatingIPPool controller
Fixes #1863 
/hold
=> 🐛 Adds Kind to ipaddress pool name index

main.go, main_test.go
Add `--tls-min-version`, `--tls-max-version` and `--tls-cipher-suites` configuration flags. Same flags can be found in k8s, CAPI, CAPM3 etc.
This enables configuring TLS 1.3 in high security environments, or limiting TLS to 1.2 for debugging purposes as 1.3 is considerably harder to debug.
No.
**TODOs**:
=> :sparkles: add TLS configuration flags

controllers/openstackfloatingippool_controller.go
Adds ip to claimedIPs after it's popped from availableIPs to make sure the same IP is not added from tagged IPs when processing multiple claims in the same reconcile. 
Another would be to go back to handling one claim per reconciliation and requeuing to so claimedIPs is always populated from IPAddresses before getIP is called.
Fixes: #1869 
**TODOs**:
/hold
=> OpenstackFloatingIPPool: Adds popped ip to claimedIPs #1869 

Dockerfile, pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/utils/strings/strings.go, pkg/utils/strings/strings_test.go
This PR makes sure that allowedCidrs isn't patched on a listener when comparing a list that is out of order.
I noticed this bug due to my second listener never being created when using multiple listeners together with allowedCidrs.
A part of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1687
I do not know if CompareLists is a good function name. If any other names are preferred just let me know.
**TODOs**:
/hold
=> 🐛Make sure that allowedCidrs lists are compared correctly to avoid patching LB listener when not needed

api/v1alpha8/openstackcluster_types.go, api/v1alpha8/openstackcluster_webhook.go, api/v1alpha8/openstackcluster_webhook_test.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, controllers/openstackcluster_controller.go, docs/book/src/clusteropenstack/configuration.md
We now have a webhook that checks that a bastion has been disabled if a
change has to be made (update or delete) in the bastion field.
We also document it better.
Also, we added some code to prevent that we don't have a nil pointer if
the Spec.Bastion or Status.Bastion are unset.
Fixes #1855
**TODOs**:
=> 🐛 Prevent the bastion to be removed before it's been disabled

Dockerfile, go.mod, hack/tools/go.mod
Bump Golang to 1.22.0 freshly released.
=> ✨ Bump Go to 1.22.0

pkg/scope/provider.go
Ignore `OS_` prefixed environment variables when building our clients.
Fixes #1991
None.
**TODOs**:
/hold
=> 🐛 Ignore 'OS_*' environment variables

api/v1alpha5/openstackcluster_types.go, api/v1alpha5/openstackclustertemplate_types.go, api/v1alpha5/openstackmachine_types.go, api/v1alpha5/openstackmachinetemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
With this change the apiserver will no longer recognise api version v1alpha5. Configurations using v1alpha5 will not work.
As a workaround, the CRD can be edited to temporarily re-enable v1alpha5 so that configurations can be upgraded to a more recent version, but this workaround will also be removed in the next release.
=> ⚠️ Stop serving v1alpha5

config/default/namespace.yaml
We should be able to run with the restricted policy and this will inprove our security.
This enforces the restricted pod security standards profile. It ensures that we do not run containers as root or privileged for example. In a way it can be seen as a validation that we actually configure CAPO according to security best practices.
Fixes #
2. I was a bit unsure what icon to use for this actually but went with :seedling: eventually. It could be seen as …
=> 🌱 Enforce restricted pod security standards

api/v1alpha1/conditions_consts.go, api/v1alpha1/openstackfloatingippool_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml, controllers/openstackfloatingippool_controller.go
Adds MaxIPs to OpenstackFloatingIPPool, after the pool has claimed that amount it will no longer create new floating IPs. 
Relates to #1750 and solves a use case we have where we're preallocating entire ipranges, and we don't want random IPs if the pool is depleted. Our usecase could probably be solved by using [cluster-api-ipam-provider-in-cluster](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster) for those clusters but we probably want to be able to control how many IPs a pool allocates anyways.
relates to #1750
/hold
=> ✨ Adds MaxIPs to OpenstackFloatingIPPool

pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go
`ControlPlaneEndpoint.Host` is not guaranteed to be an IP address, it
can also be an hostname.
Now we'll try to lookup the hostname if it's not an IP and set that for
the LB VipAddress.
Fixes #1714
Unit tests are tricky. We stub the call to net.LookupHost to avoid actual DNS lookups.
=> 🐛 loadbalancer: resolve ControlPlaneEndpoint.Host when needed

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, docs/book/src/topics/crd-changes/v1alpha7-to-v1alpha8.md, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/network_test.go
For the BYO scenario, when the `OpenStackCluster.Spec.Network`
is not specified the query to OpenStack will return all the
Networks available in the cloud and fail the reconciliation.
To avoid this, if any Subnets were specified under
`OpenStackCluster.Spec.Subnets` this can used to identify
which Network to use.
Note, this pattern to infer a field based on another field has already been used by the
`OpenStackCluster.Spec.Subnets` and also when no Network is defined in a Port.
**TODOs**:
/hold
=> ✨ Modify OpenStackCluster.Spec.Network API

api/v1alpha6/openstackcluster_types.go, api/v1alpha6/openstackclustertemplate_types.go, api/v1alpha6/openstackmachine_types.go, api/v1alpha6/openstackmachinetemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml
Mark v1alpha6 version deprecated in our Kubernetes CRDs.
Fixes #1886
=> 🌱 Deprecate v1alpha6

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml, test/e2e/shared/defaults.go, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
Deploying a bastion consumes resources so we now do it in its own test.
From now, the rest of the tests won't have a bastion node.
Fixes #1821
=> 🐛 e2e: bastion tests

Makefile
This PR includes 2 commits which each make a single change to how the Makefile does code generation.
The first adds the following 2 separate targets:
* generate-controller-gen
* generate-conversion-gen
These invoke `controller-gen` and `conversion-gen` respectively. These were previously invoked by the `generate-go` target, but that target is now reduced to simply executing `go generate ./...`.
The `generate` target continues to invoke all code generation.
The advantage of this is the ability to easily run only the generation you need during development.
The second commit changes the behaviour of `generate-conversion-gen`. This produces no change in output against the current codebase, but fixes an issue generating an incorrect package internal package name should conversion-gen want to …
=> 🌱 Enhancements to how controller-gen is invoked

pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go
This function had become genuinely too complex over time, to the point that even the linter was starting to complain about it when making almost any change.
This change refactors ReconcileLoadBalancer into several smaller logical functions which are much easier to read and reason about. It also revealed some trivial optimisations:
* Only fetch Octavia providers if we need them to create a new loadbalancer
* Only calculate allowed CIDRs once
* Don't re-fetch a loadbalancer to check it's active if it's already active
Apart from just the code cleanup, this has the benefit of not requiring these changes to be mixed into other PRs when the complexity exceeds the linter's threshold.
/hold
=> 🌱 Reduce cyclomatic complexity of ReconcileLoadBalancer

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackfloatingippool_controller.go, controllers/openstackmachine_controller.go, controllers/suite_test.go, pkg/cloud/services/compute/dependent_resources.go, pkg/cloud/services/compute/dependent_resources_test.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/compute/instance_types_test.go, pkg/cloud/services/compute/referenced_resources.go, pkg/cloud/services/compute/referenced_resources_test.go, pkg/cloud/services/compute/servergroup_test.go, pkg/cloud/services/compute/service.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go, pkg/cloud/services/loadbalancer/service.go, pkg/cloud/services/networking/network_test.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/securitygroups_test.go, pkg/cloud/services/networking/service.go, pkg/scope/mock.go, pkg/scope/provider.go, pkg/scope/scope.go
Scope encapsulates an initialised OpenStack client which can be safely shared between reconciles which share the same credentials. The logger is initialised with context specific to an individual reconcile, so it cannot be shared between reconciles.
To avoid code churn we preserve the previous interface of Scope with the creation of scope.WithLogger, which changes the initialisation to ensure that the returned logger always comes from the current reconcile even if the scope was cached.
While touching logging in tests, we also take the opportunity to replace uses of logr.Discard with GinkgoLogr or logr/testr as appropriate, so test logs are now captured.
Fixes #1840
/hold
=> 🐛 Remove logger from scope

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go
This change refactors reconcileNetworkComponents into several smaller logical functions which are easier to read and reason about.
It also makes the gocyclo linter happy when making new changes to this code.
/hold
=> 🌱 Reduce cyclomatic complexity of reconcileNetworkComponents

pkg/cloud/services/networking/securitygroups_rules.go
When providing additional ports to open on the control plane security
group, we'll only open TCP from now as it was initially documented.
Opening UDP by default might not be desired for security reasons.
Fixes #1704
/hold
=> 🐛 api/additionalPorts: don't create UDP rules

test/e2e/data/kustomize/k8s-upgrade/upgrade-from-template.yaml, test/e2e/data/kustomize/k8s-upgrade/upgrade-to-template.yaml
We missed these files when removing `cloudName` from CI configs.
=> 🐛 ci: fix upgrades by dropping cloudName

pkg/cloud/services/networking/securitygroups_rules.go
This PR makes sure that the logic for LB additional ports is dynamic to avoid unintended behaviour.
Fixes #1917
**TODOs**:
/hold
=> 🐛 Make LB additional ports security-group generation are dynamic

api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/openstackclustertemplate_conversion.go, api/v1alpha6/types_conversion.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/openstackmachine_conversion.go
This is a breaking change, although it should not have any negative effects in practise.
The v1alpha6 cluster restorer had become too complex with too many individual fields. This change reduces the number of fields to be consistent with the v1alpha7 restorer.
With this change, an object stored as v1alpha6 with previous v1beta1 annotations could have fields in its spec restored to a semantically equivalent but slightly different serialisation when converted to v1beta1. Differences in the bastion and status are not affected.
In practise this should not matter for 2 reasons:
* The storage version is v1beta1, so the annotation should have been freshly generated in the new format anyway.
* Even if it were not, and the v1alpha6 were under external control, the external controller would observe …
=> ⚠️ Simplify v1alpha6 cluster restorer

Makefile
When moving the webhooks in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1920 we didn't separate CRD generation from webhook generation, meaning controller-gen was looking for CRDs to generate in pkg/webhook. This resulted in CRDs not being generated.
=> Fix CRD generation

Makefile
This change creates separate targets for individual API targets when generating api documentation. The generate-api-docs target continues to execute all of them as before.
=> 🌱 Allow generating api-docs for individual versions

api/v1beta1/openstackcluster_types.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, docs/book/src/api/v1beta1/api.md, docs/book/src/clusteropenstack/configuration.md, docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
K8s API conventions require the acronyms in the field names to be uppercase if not being the first word in the name. We aren't following this in several places and this commit fixes these occurrences:
* `projectId` becomes `projectID`
* `gateway_ip` becomes `gatewayIP`
* `ipv6RaMode` becomes `ipv6RAMode`
* `networkMtu` becomes `networkMTU`
* `hostId` becomes `hostID`
* `allowedCidrs` becomes `allowedCIDRs`
Fixes #1933
**TODOs**:
/hold
=> ⚠️ Rename fields to correctly do uppercase acronyms

Makefile
Makes e2e output look like this:
=> ✨ Add junit output to e2e tests

api/v1alpha5/conversion.go
=> 🐛 v1alpha5: Fix panic in conversion when port has no binding profile

hack/ci/cloud-init/controller.yaml.tpl, kustomize/v1alpha7/flatcar-sysext/patch-flatcar.yaml, kustomize/v1alpha7/flatcar/patch-flatcar.yaml, kustomize/v1beta1/flatcar-sysext/patch-flatcar.yaml, kustomize/v1beta1/flatcar/patch-flatcar.yaml, templates/cluster-template-flatcar-sysext.yaml, templates/cluster-template-flatcar.yaml, test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: Bump the Flatcar major version used by the regular `flatcar` template tests.
* we released a new major stable quite quickly since the latest one to mitigate Docker CVEs and it ships interesting feature like `containerd` shipped as a systemd-sysext image
* this brings the Afterburn patch needed for: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1564
* As usual a CAPO maintainer will need to download the image from https://tormath1-bucket.s3.fr-par.scw.cloud/flatcar-stable-3815.2.0-kube-v1.28.5.img to the CAPO GCS bucket
/hold
Closes: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1564
=> test: bump Flatcar version

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go
We were ignoring any update which only touched the status. This code has been there an extremely long time, and was originally copied from CAPA. Unfortunately this introduces a race for recently added code which sets port status and exits the reconcile early for transactional safety.
Fixes: #1954
=> 🐛 Fix a race when updating status before reconcile completes

.gitattributes
Example: https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
A primary is to stop labelling relatively small commits as XXL just because they update some doctext which is referenced in several places in the CRDs.
This does what I intend in git:
```
> git check-attr linguist-generated ./config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml ./config/crd/kustomization.yaml
./config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml: linguist-generated: true
./config/crd/kustomization.yaml: linguist-generated: unspecified
```
However, I'm far from convinced the github integration is working. I originally included it in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1962, …
=> 🌱 Add .gitattributes to identify generated files to GitHub

api/v1beta1/openstackmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, docs/book/src/api/v1beta1/api.md, test/e2e/suites/apivalidations/openstackmachine_test.go
A typo meant we weren't actually validating server metadata value lengths. Fix that, and add an apivalidation test which would have caught it.
/hold
=> 🐛 Fix server metadata length validation

test/e2e/data/kustomize/v1alpha6/bastion.yaml, test/e2e/data/kustomize/v1alpha7/bastion.yaml
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1959 accidentally updated the bastion spec for the v1alpha6 and v1alpha7 tests, which breaks the upgrade test.
=> 🐛 Revert accidental update to previous API templates

api/v1alpha7/conversion_test.go, api/v1alpha7/openstackmachine_conversion.go
The v1alpha7 machine spec restorer was missing the exclusion for ProviderID and InstanceID was missing, and the test which was supposed to ensure it worked was broken. This fixes both.
Fixes #1986
/hold
=> 🐛 Fix v1alpha7 machine restorer and test

api/v1alpha6/conversion_test.go, api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/types_conversion.go, api/v1alpha7/conversion_test.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/types_conversion.go, test/helpers/fuzz_restorer.go
Panics in restore functions are a particular problem because `previous` is unvalidated user-provided input. It should have been generated by a previous conversion, but we have no way to enforce that. We don't need to preserve sensible behaviour given invalid input, but we should not crash.
This PR implements a generic function for fuzzing restore functions, adds v1alpha6 and v1alpha7 tests which calls the fuzzer against all restore functions, and fixes all the discovered panics.
/hold
=> 🐛 Fix multiple panics in restore functions

docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
Requires:
Fixes: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1975
/hold
=> 📖 Document changes to Filters

Makefile, api/v1alpha1/doc.go, docs/book/gen-crd-api-reference-docs/config.json, docs/book/src/SUMMARY.md, docs/book/src/api/v1alpha1/api.md, docs/book/src/api/v1alpha6/api.md, docs/book/src/api/v1alpha7/api.md, docs/book/src/api/v1beta1/api.md
This includes documentation for the Floating IP IPAM pool.
Also bumps the external CAPI link to our current dep: 1.6.0.
=> ✨ Add API docs for v1alpha1

api/v1alpha5/types.go, api/v1alpha6/types.go, api/v1alpha7/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml
Rules were removed from the security group status in v1beta1. If the status is modified then an up-converted v1alphaN object will not have its security group rules restored on down-conversion. As the CRD requires rules, this results in an API error.
Fixes #1999
/hold
=> 🐛 Rules are optional in security group rules before v1beta1

Makefile, test/e2e/suites/apivalidations/openstackcluster_test.go, test/e2e/suites/apivalidations/suite_test.go
This comprises 3 small cleanups:
* A makefile tidyup to how the KUBEBUILDER_ASSETS variable is set, which also allows it to be overridden
* Update the apivalidations to delete the objects it creates. Not really important, but might throw something up.
* Fix initialisation of the apivalidations envtest environment so that conversion webhooks work. Doesn't actually add any tests that use it, though.
/hold
=> 🌱 Minor improvements to api validation tests

pkg/cloud/services/networking/port.go
**What this PR does / why we need it**: Adds support in `GetPortForExternalNetwork` for more distributed/ha-routers
**Which issue(s) this PR fixes**: Fixes #1985 
I'm not 100% sure if we need all these device_owners or if we need some additional, I got them from https://github.com/openstack/neutron-lib/blob/master/neutron_lib/constants.py#L74 but didn't find any good documentation on them.
**TODOs**:
/hold
=> 🐛 Include more device_owners when looking for a port for floating ip

test/e2e/shared/openstack.go
Discovered by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2005
TODO:
/hold
=> 🌱 Cleanup security group created by e2e test

api/v1alpha6/openstackcluster_conversion.go, api/v1alpha7/openstackcluster_conversion.go, test/e2e/suites/apivalidations/filters_test.go, test/e2e/suites/apivalidations/openstackcluster_test.go, test/e2e/suites/apivalidations/suite_test.go
=> 🐛 Fix idempotent restore when setting ControlPlaneEndpoint

Makefile, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, pkg/cloud/services/compute/instance.go, test/e2e/data/kustomize/no-bastion/kustomization.yaml, test/e2e/data/kustomize/no-bastion/patch-no-bastion.yaml, test/e2e/shared/common.go, test/e2e/shared/defaults.go, test/e2e/suites/e2e/e2e_test.go
=> 🐛 Fix crash on delete with no bastion

test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_suite_test.go, test/e2e/suites/e2e/idmatcher_test.go
Fixes #1801 
**TODOs**:
- [x ] squashed commits
=> :seedling: Ensure E2E cleanup

test/e2e/data/kustomize/v1alpha7/kustomization.yaml
The v1alpha7 tests were previously testing v1alpha6.
=> 🐛 Fix v1alpha7 e2e tests

main.go, main_test.go
Our downstream security scan is confused by `GetTLSVersion` returning `0` as a value (even if coupled by a non-nil error), which could end up being assigned to the same identifier that (in a non-error context) would set the TLS version.
This patch makes security linting easier by never setting a TLS version outside v1.2 or v1.3, even in case of an unacceptable user input.
This is expected to be a pure refactoring. Please reject this patch if it introduces any change in behaviour.
**TODOs**:
/hold
Fixes: #2034
=> :seedling: Refactoring: never assign unacceptable TLS versions

api/v1alpha7/openstackcluster_types.go, api/v1alpha7/openstackclustertemplate_types.go, api/v1alpha7/openstackmachine_types.go, api/v1alpha7/openstackmachinetemplate_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, docs/book/src/api/v1alpha7/api.md, test/e2e/suites/apivalidations/openstackcluster_test.go
With the release of v0.10.0, v1alpha7 is deprecated.
/hold
=> ⚠️ Deprecate v1alpha7

docs/proposals/20230525-openstack-microversion-support.md
This is a proposal related to #1448 for how to support more microversions in CAPO.
This is just a proposal so it won't contain the actual implementation.
**TODOs**:
/hold
=> 📖 Proposal for microversion support

pkg/webhooks/fuzz_test.go, pkg/webhooks/openstackcluster_webhook.go
Also adds fuzz tests which would have caught this and any similar issues.
Fixes: #2042 
/hold
=> 🐛 Fix webhook panic when adding managed security groups

go.mod, go.sum
Bump Gophercloud to v1.11.0
Required to implement #1278 (use load balancer's flavors API).
1. This new version should be backward compatible with current version v1.7.0
**TODOs**:
=> :seedling: Bump Gophercloud to v1.11.0

pkg/cloud/services/networking/port.go
We were setting the default networks in 2 places, let's just keep it in `normalizePorts` for now.
=> 🐛 Remove a duplication for setting default port settings

api/v1alpha5/zz_generated.conversion.go, api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/zz_generated.conversion.go, api/v1beta1/types.go, test/e2e/suites/apivalidations/openstackcluster_test.go
This is a manual backport of #2052. An automated backport is not possible due to the removal of v1alpha5 and v1alpha6 tests on main.
TODO:
/hold
=> 🐛 [release-0.10] Fix enabling of disabled bastion on upgrade to v1beta1

README.md
Sometimes it's better not to have documentation than having outdated docs.
Otherwise people see the docs, think they are up-to-date and wait for updates.
1. See https://kubernetes.slack.com/archives/CFKJB65G9/p1714665937168969?thread_ts=1694426926.778949&cid=CFKJB65G9
/hold
=> chore(docs): remove stale supported version info

api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/zz_generated.conversion.go, api/v1beta1/types.go, test/e2e/suites/apivalidations/openstackcluster_test.go
=> 🐛 Fix enabling of disabled bastion on upgrade to v1beta1

main.go
=> 🐛 Fix panic executing manager without valid kube context

Makefile
=> 🐛 Fix empty version output in release builds

pkg/cloud/services/compute/referenced_resources.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go
It's some work we're preparing to build a new controller in charge of
creating servers and their dependencies (ports, etc). We don't want it
to depent on the OpenStack Machine object.
=> 🌱 port: no dependency on OpenStackMachine

config/manager/manager.yaml
This gives us a better chance of useful content in the Pod termination message if CAPO quits unexpectedly.
Fixes: #2069 
/hold
=> 🌱 Set FallbackToLogsOnError on CAPO manager

test/e2e/suites/apivalidations/openstackmachine_test.go
It extends tests for `openstackmachine_webhook`
Fixes: #1737
=> :bug:issue-1737: Add unit tests for openstackmachine_webhook

pkg/cloud/services/loadbalancer/loadbalancer.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go
If a loadbalancer is stuck in an non-active state it the reconciler eventually times out. The timeout error message included a nil pointer dereference.
**TODOs**:
/hold
=> 🐛 Fix loadbalancer timeout panic

docs/book/src/clusteropenstack/configuration.md, docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md, pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/securitygroups_test.go
This does the following:
Don't make `remoteManagedGroups` required, since a user can use `remoteIPPrefix` instead or even no remote parameter at all.
It's fine because Neutron will set it to an fully-open CIDR if no remote field is provided.
We made wrong assumptions when writing this and we're now relaxing it.
Fixes #2075
=> 🐛 allNodesSecurityGroupRules: relax remote fields

go.mod, go.sum, pkg/utils/conversion/restore.go, pkg/utils/hash/hash.go
This PR removes the k8s.io/kubernetes dependancy. The dependancy was only used for the [DeepHashObject](https://github.com/kubernetes/kubernetes/blob/v1.29.2/pkg/util/hash/hash.go#L26-L32) function, which is not taken in locally. It is not recommended to use k8s.io/kubernetes as a dependancy. 
Fixes #1891
=> 🐛 Remove k8s.io/kubernetes dependancy

OWNERS_ALIASES
Going forward I won't be able to contribute time to both CPO and CAPO, so this commit drops me from CAPO reviewers list.
=> 🌱 Drop dulek from reviewers

OWNERS_ALIASES
Prompted by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2082
=> [release-0.9] 🌱 Sync OWNERS_ALIASES with main

go.mod, go.sum
This PR bumps cluster-api go module to latest patch version v1.7.2
=> 🌱  Bump CAPI to v1.7.2

controllers/openstackmachine_controller.go
Errors returned by GetInstanceStatusByName were ignored up to now, which could lead controller to attempt to recreate a server under specific circumstances (for example if nova API always returns 404 errors - see detailled explanation in related issue)
These errors shouldn't be ignored, otherwise we may consider that server does not exists whereas nova api is misbehaving.
Fixes #2085
**TODOs**:
=> 🐛 Handle errors returned by GetInstanceStatusByName in machine controller

docs/book/src/clusteropenstack/configuration.md
Since v1beta1 fields for rootVolume got renamed : 
From :
```bash
kubectl explain --api-version=infrastructure.cluster.x-k8s.io/v1alpha7 openstackmachinetemplate.spec.template.spec.rootVolume
GROUP:      infrastructure.cluster.x-k8s.io
KIND:       OpenStackMachineTemplate
VERSION:    v1alpha7
FIELD: rootVolume <Object>
DESCRIPTION:
The volume metadata to boot from
FIELDS:
availabilityZone      <string>
<no description>
diskSize      <integer>
<no description>
volumeType    <string>
<no description>
```
To : 
```bash
kubectl explain --api-version=infrastructure.cluster.x-k8s.io/v1beta1 openstackmachinetemplate.spec.template.spec.rootVolume --recursive
GROUP:      infrastructure.cluster.x-k8s.io
KIND:       OpenStackMachineTemplate
VERSION:    v1beta1 …
```
=> :book: Fix rootVolume new fields name

test/e2e/data/e2e_conf.yaml, test/e2e/data/shared/v1beta1/metadata.yaml
This bumps CAPI, cert-manager, coredns and etcd versions used in the e2e tests.
Also cleans up unused CAPO/CAPI versions from the e2e config.
Fixes #
**TODOs**:
/hold
=> 🌱 E2E: Bump CAPI, cert-manager, coredns and etcd

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
Bumping the Kubernetes versions used in e2e tests.
Upgrades are now from v1.28.5 to v1.29.5
Fixes #
**TODOs**:
/hold
=> 🌱 E2E: Bump Kubernetes to v1.29.5

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
This is bumping the Kubernetes version used in e2e tests.
Upgrades are now from v1.29.5 to v1.30.1.
Fixes #
**TODOs**:
/hold
=> 🌱 E2E: Bump Kubernetes to v1.30.1

Makefile, scripts/ci-apidiff.sh
* Add target to Makefile to run `make apidiff`
* Add the script itself, copied from other platforms
Fixes #1860
=> 🌱 Add script for API diff check

controllers/openstackcluster_controller.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/networking/network.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/router.go, pkg/utils/errors/errors.go
* Move errors functions/vars into capoerrors, so they can easily be
re-used.
* Now we return an error if multiple instances with the same name were
found (and not just a warning). There is no safe course of action here.
Fixes #2088
=> ⚠️ More than one instance found is now an error

pkg/cloud/services/compute/instance.go
When creating a server, Nova can return an error immediately after the
call was made to create it or later (which would be seen when showing the server status with a different API call).
If it's returned immediately, we would like to restore the error event
that we used to have and that we actually test in our e2e when providing
a wrong availability zone.
Fixes #2111
=> 🐛 instance: re-add error event if server creationg returned an error

pkg/cloud/services/networking/securitygroups.go, pkg/cloud/services/networking/securitygroups_test.go, test/e2e/suites/e2e/e2e_test.go
We reconcile the security groups before the bastion, because the bastion
needs its security group to be created first when managed security groups are enabled.
When the bastion is disabled, we will try to delete the security group if it exists.
In the first attempt, the security group will still be in-use by the bastion instance
but then the bastion instance will be deleted in the next reconcile loop.
We do that here because we don't want to manage the bastion security group from
elsewhere, that could cause infinite loops between ReconcileSecurityGroups and ReconcileBastion.
Therefore we try to delete the bastion security group as a best effort here
and also when the cluster is deleted so we're sure it will be deleted at some point.
Also, we're …
=> 🐛 Remove bastion security group when disabling the bastion

controllers/openstackcluster_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go
f.e if the creds break, but the cluster was ready, the operator can fix it.
Use transient Error if the Openstackcluster was once ready.
Fixes #2097
/hold
=> :bug: if the openstackcluster was ready, we don't want to set a terminalError

docs/book/src/topics/crd-changes/v1alpha7-to-v1beta1.md
DNSNameservers is an array, not a string
**TODOs**:
/hold
=> :book: Fix dnsNameservers array in the v1beta1 changes docs

api/v1alpha1/openstackfloatingippool_types.go, api/v1beta1/identity_types.go, api/v1beta1/openstackcluster_types.go, api/v1beta1/openstackmachine_types.go, controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackfloatingippool_controller.go, controllers/openstackmachine_controller.go, docs/book/src/api/v1beta1/api.md, pkg/scope/mock.go, pkg/scope/provider.go, pkg/scope/scope.go
As we add more resource controllers the pattern of adding another
NewClientScopeFromFoo to ScopeFactory is becoming more cumbersome. This
allows them all to use a common interface.
Summary of changes
* Addition of `infrav1.IdentityRefProvider`
* Implementations of IdentityRefProvider for OpenStackMachine, OpenStackCluster, and OpenStackFloatingIPPool
* Replace `NewClientScopeFrom*` in `scope.Factory` with a single `NewClientScopeScopeFromObject` which takes a list of IdentityRefProvider
The reason it takes a list rather than a single object is so OpenStackMachine can continue to implement a fallback where it will use the IdentityRef from OpenStackCluster if it is not defined on the OpenStackMachine.
/hold
=> 🌱 IdentityRefProvider: DRY obtaining OpenStackIdentityRef

pkg/cloud/services/compute/instance.go
Currently, if cluster-api fails to find an image during machine creation it fails with the following, rather unhelpful error:
"Reconciler error" err="no images were found with the given image filter: {<nil> 0xc000558880}" ...
Improve our error messages so we get something slightly more useful.
"Reconciler error" err="no images were found with the given image filter: name=foo, tags=[]" ...
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
Fixes #
None.
**TODOs**:
/hold
=> 🌱 cloud: Better error message on image lookup failure

api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/openstackmachine_conversion.go, api/v1alpha6/types_conversion.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/types_conversion.go, test/e2e/suites/apivalidations/openstackcluster_test.go, test/e2e/suites/apivalidations/openstackmachine_test.go, test/e2e/suites/apivalidations/suite_test.go
We were not setting IdentityRef.Kind when down-converting an object with
no previous version annotation, which results in a validation error.
Fixes #2136
I developed this directly against the release-0.10 branch because main doesn't run v1alpha6 tests any more. However, we should merge it in main first.
TODO:
/hold
=> :bug: Fix down-conversion of IdentityRef

test/e2e/suites/e2e/e2e_suite_test.go
We were calling DumpOpenStack* in the 'all nodes' argument to SynchronizedBeforeSuite, but only running the checks in the 'node 1' argument to SynchronizedAfterSuite. This is inefficient if we run with more than 1 node, as only data dumped by node 1 will be checked.
This change moves the checks to a DeferCleanup() node called from the creation node, so the cleanup will only run where it was created.
We also refactor CheckResourceCleanup to return error so we can return its output directly to DeferCleanup.
/hold
=> 🐛 e2e: Only dump resources on node 1

design/proposed/2020-openstackserver-controller.md
Design proposal for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2020
/hold
=> 🌱 Add design doc for OpenStackServer

test/e2e/suites/e2e/e2e_test.go
This is a continuation of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2081. The idea is to have subports added to trunked port, so that we could verify that subports are deleted with the trunk.
=> :seedling: E2E: Add subports to trunked port to test subports deletion

hack/ci/cloud-init/controller.yaml.tpl, test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: When there is a new Flatcar Stable major release, we update the tested image on CAPO. (https://github.com/flatcar/Flatcar/issues/1509)
**Special notes for your reviewer**: 
* As usual, a CAPO maintainer will need to upload the image (https://wfwfg.s3.pl-waw.scw.cloud/flatcar-stable-3975.2.0-kube-v1.30.1.img) on CAPO GCS Bucket :ballot_box_with_check: 
* Image built with: `sudo podman run -it --privileged -v "${PWD}/docker-output:/output" -v /dev:/dev --net host --rm -e PACKER_LOG=1 -e OEM_ID=openstack -e PACKER_FLAGS="--var 'kubernetes_semver=v1.30.1' --var 'kubernetes_series=v1.30'" image-builder build-qemu-flatcar`
* `flatcar-sysext` test is already using the latest Flatcar version by default - no need to update. 
**TODOs**:
/hold
=> test: bump Flatcar Stable version

controllers/openstackmachine_controller.go
* `OpenStackMachine.Status.InstanceID` is always empty if even the server is running
* Copy the InstanceID from OpenStackServer to OpenStackMachine as soon as the server gets running
Fixes #
**TODOs**:
/hold
=> Copy InstanceID from OpenStackServer to OpenStackMachine

pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go, pkg/webhooks/openstackmachine_webhook.go, pkg/webhooks/openstackserver_webhook.go, test/e2e/suites/apivalidations/openstackmachine_test.go, test/e2e/suites/apivalidations/openstackserver_test.go
When port security is disabled on a port, don't add any security group
to the port options.
Skip the security groups when resolving the ports spec.
Report an error when a port tries to be created with both security
groups and disable port security to true.
Adds unit tests coverage for these scenarios.
Fixes #2158
=> 🐛 port: don't add any SGs when port security is disabled

hack/ci/create_devstack.sh, scripts/ci-conformance.sh, scripts/ci-e2e.sh
Update CI to use the latest stable version of OpenStack: Caracal.
=> CI: update OpenStack to 2024.1 (Caracal)

pkg/clients/mock/network.go, pkg/clients/networking.go, pkg/cloud/services/compute/instance_test.go, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/trunk.go, test/e2e/suites/e2e/e2e_test.go
This PR backports https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2081 and https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2141 into release-0.9
**TODOs**:
/hold
=> :seedling: Backport #2081 and #2141 to release-0.9

controllers/openstackmachine_controller_test.go, pkg/clients/mock/network.go, pkg/clients/networking.go, pkg/cloud/services/networking/trunk.go, test/e2e/suites/e2e/e2e_test.go
This PR backports https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2081 and https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2141 into release-0.10
**TODOs**:
- [x ] squashed commits
/hold
=> :seedling: Backport #2081 and #2141 to release-0.10

controllers/openstackcluster_controller.go, controllers/openstackserver_controller.go
To handle cluster move, we now do two things:
* Re-populate OpenStackServer.Status fields before a server is deleted, otherwise the Status is empty and we don't know what resources need cleanup (server ID, port ID, etc).
* Mark the Cluster as Ready as early as possible, even before the bastion is not ready yet. The bastion isn't a CAPI-managed type of resource, so it's ok to mark the cluster ready when the bastion is not. We have a reconciler to make sure the bastion exists (or not) right after. This helps when a cluster is moved.
Fixes #2155
/hold
=> openstackserver: create before delete if adoption fields are empty

docs/book/src/clusteropenstack/configuration.md
**What this PR does / why we need it**: it now uses a filter to get the security group by name
**TODOs**:
/hold
=> :book: docs/configuration: fix security groups example

Makefile
This change adds separate `test-orc` and `test-capo` make targets which run exclusively capo and orc tests respectively. The `test` target continues to run both.
=> 🌱 Allow running CAPO and ORC tests separately

internal/controllers/image/reconcile.go
When an image is to be adopted, the controller would still attempt to upload content when it observed the image in the queued state after having been created externally. This didn't result in incorrect behaviour because API validation ensures that images for adoption don't specify a source. This meant that no upload could be attempted, but it did result in a spurious error message reported both to the user and in the logs.
/hold
=> 🐛 Image controller: don't attempt upload when adopting

internal/controllers/image/reconcile.go, internal/controllers/image/status.go
This fixes a race during image delete where we can get a second reconcile on a deleted object and accidentally create a new object when we only intended to remove the finalizer from the old object. With this change, the second patch will throw an error instead.
/hold
=> 🐛 Ensure SSA patch can't accidentally create a new object

api/v1alpha6/openstackcluster_conversion.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/openstackcluster_conversion.go, api/v1alpha7/zz_generated.conversion.go, api/v1beta1/openstackcluster_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, docs/book/src/api/v1beta1/api.md, hack/codegen/openapi/zz_generated.openapi.go, pkg/generated/applyconfiguration/api/v1beta1/openstackclusterspec.go, pkg/utils/optional/conversion.go, pkg/utils/optional/types.go, pkg/webhooks/openstackcluster_webhook_test.go, test/e2e/suites/apivalidations/openstackcluster_test.go
This problem was highlighted by the updated gosec linter brought in by https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2173, which pointed out the unsafe conversion from int to int32. CAPI's control plane endpoint port is an int32. We were using int, which can be larger. We also weren't validating it.
APIServerPort is a TCP port, which is an unsigned 16 bit integer. We were
previously allowing it to be any integer.
This is a breaking change, but as any working configuration would have
to have a value which passes the new validation it should not break any
working configuration.
=> ⚠️ Convert APIServerPort to uint16

controllers/openstackmachine_controller.go, pkg/scope/provider.go
This patch fixes a regression where the last `IdentityRef` from a given list where used instead of the first one that was found valid.
In the case of the OpenStackMachine, we pass two refs, one for the Machine and one for the Cluster. Now the provider will return the ref from the Machine if it exists.
Fixes #2190
=> 🐛 Re-allow `OpenStackMachine` to use their own `IdentityRef`

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, controllers/openstackserver_controller.go, pkg/cloud/services/networking/securitygroups.go
We want to reduce the times we reconcile the OpenStackMachine and
OpenStackCluster by only watching the following events for an OpenStackServer object:
* The server is status.Ready
* The server failed to be created (and no further action will be taken
by the server controller)
Fixes #2184
=> Reduce reconciles and logs

api/v1alpha6/conversion_test.go, api/v1alpha6/zz_generated.conversion.go, api/v1alpha7/conversion_test.go, api/v1alpha7/zz_generated.conversion.go, api/v1beta1/identity_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackfloatingippools.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackservers.yaml, controllers/openstackmachine_controller.go, docs/book/src/api/v1beta1/api.md, hack/codegen/openapi/zz_generated.openapi.go, pkg/generated/applyconfiguration/api/v1beta1/openstackidentityreference.go, pkg/generated/applyconfiguration/internal/internal.go, pkg/scope/provider.go, test/e2e/shared/openstack.go, test/e2e/suites/apivalidations/openstackmachine_test.go
To made CAPO compatible with OCCM multi-cloud deployment we need to manage providerID format with region code as introduced [here](https://github.com/kubernetes/cloud-provider-openstack/issues/1900) (`openstack://region/instance_uuid`). Use annotation from OpenstackMachine to define region in providerID field.
An empty or undefined annotation permit to be fully backward compatible. Moreover use annotation permit to manage some cluster with new OCCM provider-id string and other cluster with old format by same CAPO instance.
Fixes #2183
- As discussed in issue #2183 I first try to implement k8s secret call to get region name from config [here](https://github.com/MatthieuFin/cluster-api-provider-openstack/commit/04a4 …
=> feat(manager): :sparkles: add region to openStackMachineSpec.ProviderID field from crd identityRef

internal/controllers/image/reconcile.go
This PR refactors the four resource-fetching strategies in the Image controller:
* the resource is known by ORC (it has status.ID)
* the resource is imported by ID
* the resource is imported by filter
* the resource must be (spec-fetched or) created
This PR could be one of the following:
* me disentangling four code paths for readability and increased maintainability; OR
* me inadvertently changing the behaviour of the reconciler and introducing bugs; OR
* me perfecting a refactoring that doesn't bring any clarity, and possibly makes the code worse.
Finding out which of these really is the exercise for the reader.
**TODOs**:
=> 🌱 refactoring: Untangle four image-fetching strategies

pkg/cloud/services/compute/instance.go, pkg/scope/hash.go, pkg/scope/provider.go, pkg/utils/conversion/restore.go
This package was hosting 2 exported functions that weren't sharing any code and each had only a single consumer. We instead move the methods to their respective points of use.
Also entirely removes the exported function HashInstanceSpec, which had no consumers.
=> 🌱 Remove pkg/utils/hash

controllers/openstackcluster_controller.go
- Fixed issue where spec.bastion.spec.serverMetadata was not set in bastion.
- Updated bastionToInstanceSpec to apply serverMetadata in InstanceSpec.
Fixes an issue where `spec.bastion.spec.serverMetadata` in `OpenStackCluster` was not applied as `metadata` to OpenStack instances. This change ensures that server metadata is set during bastion creation.
Fixes #2177 
1. Please check if any other parts of the repository require updates to serverMetadata outside of this change.
**TODOs**:
/hold
=> 🐛  Fix ServerMetadata Not Applied to Bastion in OpenStackCluster

.github/dependabot.yml, .github/workflows/pr-dependabot.yaml
Maintaining our go.mod (we have 3 of them) up to date is a bit of work
and other cluster-api providers use dependabot to take care of it.
I took a look at the vsphere and azure providers and pretty much copy
pasted (with adjustments).
=> 🌱 Use Dependabot for go.mod & GH workflows

.github/dependabot.yml
* Add blocks for main and for release-0.11
* Fix the prefix for commit messages
* Separate changes from CAPI and k8s dependencies
* Don't ignore github.com/prometheus/* bumps
=> dependabot: config changes

config/crd/patches/webhook_in_openstackclusters.yaml, config/crd/patches/webhook_in_openstackclustertemplates.yaml, config/crd/patches/webhook_in_openstackfloatingippools.yaml, config/crd/patches/webhook_in_openstackmachines.yaml, config/crd/patches/webhook_in_openstackmachinetemplates.yaml
**What this PR does / why we need it:**
Starting with Kubernetes 1.31 it won't be possible anymore to continuously apply CRDs that are setting caBundle to an invalid value (in our case Cg==). The solution is to simply drop the caBundle field (it was never actually required by kube-apiserver).
For more details see: https://kubernetes.slack.com/archives/C0EG7JC6T/p1722441161968339
Let me know if you have any questions.
We'll want to backport this into all supported releases. It's never great to set the caBundle to an invalid value, even before Kubernetes 1.31.
This is an effort driven by CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/10972
=> 🐛 Drop caBundle from CRDs to support Kubernetes 1.31

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/data/e2e_conf.yaml
The latest stable version on November 5th 2024.
=> 🌱 Bump CAPI to v1.8.5

go.mod, go.sum, hack/codegen/go.mod, hack/codegen/go.sum, hack/tools/go.mod, hack/tools/go.sum, test/e2e/data/e2e_conf.yaml
The latest stable version on November 5th 2024.
=> 🌱 [manual-backport-0.11] Bump CAPI to v1.8.5

test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: This PR bumps Flatcar tested version to latest Stable
* With the new orc approach, I can't update the image here for testing, so one maintainer needs to upload this image to the CAPO GCS: https://wfwfg.s3.pl-waw.scw.cloud/flatcar-stable-4081.2.0-kube-v1.30.1.img
* We need to think about "deprecating" the current `flatcar` template in favor of `flatcar-sysext` to have only one Flatcar template that does not need images from the image-builder
**TODOs**:
/hold
=> :seedling: test/e2e: bump Flatcar image to latest Stable

hack/ci/create_devstack.sh, hack/ci/libvirt.sh
This makes it possible to set up a local devstack on libvirt. It is probably not useful for running the full e2e suite (unless you have a very beefy PC), but it is enough for development with Tilt.
My plan is to add more docs and scripts/manifests around this so that it can easily be used with the dev ClusterClass.
Fixes #
**TODOs**:
/hold
=> 🌱 Add libvirt resource type for create_devstack.sh

api/v1beta1/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, docs/book/src/clusteropenstack/configuration.md, pkg/cloud/services/networking/floatingip.go, test/e2e/suites/apivalidations/openstackcluster_test.go
When a floating is created, we need to make sure that
`OpenStackCluster.Spec.DisableExternalNetwork` is not set to `True`.
Otherwise, we'll have a nil pointer error.
* Add a check in `reconcileBastion` to check that external network is
not disabled before creating the floating IP for the bastion.
* Add a check in `reconcileControlPlaneEndpoint` and
`reconcileAPIServerLoadBalancer` to check that external
network is not disabled (alongside the DisableAPIServerFloatingIP
check) before creating the floating IP for the API server endpoint.
* Add a safeguard in `GetOrCreateFloatingIP` to return a proper error
(instead of a nil pointer error) when
`openStackCluster.Status.ExternalNetwork` is nil.
* Add API CEL to check that when DisableExternalNetwork is …
=> 🐛 Better checks before creating Floating IPs

api/v1beta1/openstackcluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_openstackclustertemplates.yaml, controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, docs/book/src/clusteropenstack/configuration.md, pkg/cloud/services/networking/floatingip.go, test/e2e/suites/apivalidations/openstackcluster_test.go
This is an manual cherry-pick of #2261 with a little conflict in the tests.
=> [release-0.10] 🐛 Better checks before creating Floating IPs

pkg/clients/compute.go, pkg/clients/mock/compute.go, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/instance_test.go, pkg/utils/openstack/microversion.go, pkg/utils/openstack/microversion_test.go, test/e2e/shared/openstack.go
This is related to the proposal in #1565. 
Use a list of supported versions instead of a single hard coded one. The list can be filtered based on specific feature requirements (e.g. usage of server tags). The version to use is then picked from the intersection of this list and what the server supports.
Fixes #1448
**TODOs**:
/hold
=> ✨ Flexible Nova microversions

Makefile, test/e2e/data/e2e_conf.yaml
Use CAPI production images instead of from GCR.
Don't pre-pull cert-manager. We always let these images get out of sync, causing us to pull double instead of saving anything. We end up with different tags in e2e_conf.yaml and in the Makefile. Additionally, CAPI may change what version is installed by clusterctl by default, causing us to pull *two* wrong versions and then install a third if we don't remember to check when bumping CAPI.
Fixes #
**TODOs**:
- …
=> 🌱 E2E: Use CAPI production images and skip cert-manager pre-pull

controllers/openstackcluster_controller.go
If the bastion image is missing or ambiguous, we do not have a bastion. In that case, we must continue with the deletion or be permanently stuck.
This is a direct PR for release-0.10 since the issue doesn't exist on main.
Fixes #2266
**TODOs**:
/hold
=> 🐛 Fix deletion of cluster when bastion image missing

hack/ci/cloud-init/controller.yaml.tpl, hack/ci/cloud-init/worker.yaml.tpl
Configuring the following in devstack:
```
ENABLE_SYSCTL_MEM_TUNING="True"
ENABLE_SYSCTL_NET_TUNING="True"
ENABLE_ZSWAP="True"
```
That tuning is what is done in the `devstack-platform-ubuntu-noble`
job.
Example:
https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_d17/936669/2/check/devstack-platform-ubuntu-noble/d178dad/controller/logs/local_conf.txt
=> 🐛 ci/devstack: host tuning

hack/ci/gce-project.sh
This is an attempt to see if disk performance is what makes our CI unstable.
Fixes #
**TODOs**:
/hold
=> 🌱 CI: Increase IOPS for the devstack disks

hack/ci/cloud-init/controller.yaml.tpl, hack/ci/cloud-init/worker.yaml.tpl
In this PR we'll control the version of OVN to align with the upstream
devstack jobs building OVN and OVS from LTS versions.
This is largely a workaround to address some timeout issues that we
recently have and that with a controlled version of OVN we hope to
reduce.
issue #2320
=> 🌱 devstack: build OVN from source

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum
as a preemptive measure against [CVE-2024-45338](GHSA-w32m-9786-jp63).
=> :seedling: Update golang.org/x/net to v0.33.0

controllers/openstackserver_controller.go
When an IPAddressClaim is created and the openstackserver has a cluster name label, the capo controller panics because the Labels map is nil by default.
This PR creates an empty Lables map on new IPAddressClaim ObjectMeta.
**TODOs**:
/hold
=> :bug: New IPAddressClaim.ObjectMeta.Labels nil map assign panic

controllers/openstackcluster_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go
The load balancer should be created in the specified lb network if it is defined and it exists. This does not work, see issue #2149.
This PR tries to fix this by writing the read info for the lb network to the status.
I did lots of debugging and found out that the network and subnet info is read in every reconcile loop, written to the local variables but is not saved in the openStackCluster.Status.apiServerLoadBalancer.loadBalancerNetwork field. I tried to fix this by adding the needed line(s).
I also added some more info for the lb subnet to the status to look equal to the normal cluster subnet status.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
=> 🐛 fix: create lbaas in specified subnet

test/e2e/data/e2e_conf.yaml, test/e2e/shared/images.go
Let's bump k8s release to v1.31.2 to align with other platforms
and the k8s version of CAPI & CAPO.
=> 🌱 e2e: bump to ubuntu-2404-kube-v1.31.2

Dockerfile, Makefile
This PR uses the specified GO_VERSION from the makefile to build the docker image. Currently the hardcoded patch release .0 is used, but I think using the specified version from the Makefile and not an old version that is missing some patches is a good idea.
none
**TODOs**:
=> ✨ feat: use specified go version for docker build

controllers/openstackcluster_controller.go, pkg/cloud/services/loadbalancer/loadbalancer.go
This is a manual backport of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2339
The linter was not happy on the release-0.10 branch because of an older go version used.
It was hitting
```
G601: Implicit memory aliasing in for loop.
```
Fixes #
**TODOs**:
/hold
=> [release-0.10] 🐛 fix: create lbaas in specified subnet

OWNERS_ALIASES
We were giving some time but it doesn't sound like jichenjc
is involved anymore, so let's update OWNERS_ALIASES and move him
to cluster-api-openstack-emeritus-maintainers.
=> 🌱 Update OWNERS_ALIASES

.golangci.yml, Dockerfile, Makefile, go.mod, hack/tools/go.mod, netlify.toml
This PR updates the Go version to 1.23.4 (current latest) for consistency.
=> 🌱 Use the same version of Go everywhere (latest: 1.23.4)

.github/dependabot.yml
* Delete `orc/` directory in main, it doesn't exist anymore.
* Skip new major and minor releases for code-generator, it requires k8s
api v1.31 and beyond which we don't want in release-0.11.
=> 🌱 dependabot: skip code-generator updates on 0.11

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, pkg/cloud/services/networking/router.go
Currently only pre existing networks and subnets are reconciled and not a pre existing router.
I think it is a good idea to also reconcile pre-existing routers and put them in the status. This is useful for debugging, reading info from the status (e.g. outgoing router ip of the cluster) and if the router ip is written to the status, it can be used for the lb allowlist.
none
**TODOs**:
=> ✨ feat: reconcile pre-existing router

docs/book/src/development/development.md, templates/cluster-template-development.yaml, templates/clusterclass-dev-test.yaml, templates/images-template.yaml
This adds a template for ORC managed Images. The template is meant as a simple way for developers to get a bastion and node image loaded into their openstack environment. Docs are also updated to reflect this.
The ClusterClass template is also updated to make it more useful. Most notably, this adds variables for identityRef and for specifying the image name. It is possible to choose between the traditional image including kubernetes components, or using e.g. flatcar with a sysext overlay. The sysext overlay patch is only for ignition for now.
Fixes #
1. …
=> 📖 Add Image templates, improve dev-test clusterclass and update dev docs

controllers/openstackserver_controller.go, controllers/openstackserver_controller_test.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/service.go, test/e2e/data/e2e_conf.yaml
When a port is created, it is tagged and explicitly checked if it needs a trunk, but if the port already exists for some reason, it is taken without any of those checking. This PR fixes that by adding a similar check for the existing ports, similar to the check in new ports.
Fixes #
**TODOs**:
/hold
=> :bug: Ensure that existing ports also have correct tags and trunks

controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackmachine_controller.go, pkg/cloud/services/networking/port.go, pkg/cloud/services/networking/port_test.go, pkg/cloud/services/networking/service.go, test/e2e/data/e2e_conf.yaml
If port creation fails in the middle, and cleanup also fails, then we may end up with ports with missing tags or trunks. This could happen when hitting rate-limits for example or if there is a network outage. This commit addresses the issue by going through existing ports and ensuring that they have correct tags and trunks.
This is a manual backport of #2256
Fixes #
**TODOs**:
/hold
=> 🐛 Ensure that existing ports also have correct tags and trunks

.github/dependabot.yml
dependabot tries to bump CAPI to the latest tag but right now we use an
unreleased commit.
=> 🌱 dependabot: ignore CAPI tag changes

test/e2e/data/e2e_conf.yaml
**What this PR does / why we need it**: This PR bumps Flatcar tested version to latest Stable
* With the new orc approach, I can't update the image here for testing, so one maintainer needs to upload this image to the CAPO GCS: https://wfwfg.s3.pl-waw.scw.cloud/flatcar-stable-4152.2.0-kube-v1.31.2.img
**TODOs**:
/hold
=> :seedling: data: use latest Flatcar stable from image-builder

go.mod, hack/tools/go.mod
Specifying the patch version is not needed and can causes problems on systems which haven't updated yet to the 1.23.4.
=> 🌱 go.mod: stick to 1.23.0

.github/workflows/update-golangci-lint.yaml
Add a new GH action to periodically bump the golangci-lint when a new tag is available.
=> 🌱 ci: add GH workflow to automate golangci-lint bumps

.github/dependabot.yml
New versions of crypto require a new version of Go (1.23) and we don't want to bump go in release-0.11.
=> 🌱(deps): pin crypto for stable 0.11

.github/dependabot.yml
Latest envsubst requires go 1.24 and we are not ready for it yet.
=> 🌱(deps): pin envsubst

pkg/webhooks/openstackcluster_webhook.go, pkg/webhooks/openstackcluster_webhook_test.go
controlplane and worker security groups weren't allowed to be changed, this PR changes that.
**TODOs**:
/hold
=> fix: allow modification of all ManagedSecurityGroups

controllers/openstackmachine_controller.go
In the OpenStack machine controller make sure that the message field of a condition update (status=unknown in this case) isn't changed constantly which retriggers a reconcile loop.
Fixes #2463
**TODOs**:
/hold
=> :bug: fix: dereference the instance state in machine state reconcile calls

.github/dependabot.yml
https://github.com/onsi/ginkgo/commit/37a511b5bca15e628309b421c20e834b7f67dad4
This commit now requires golang >= 1.23 which we don't have in 0.11 so
we now skip new versions of ginkgo on release-0.11 branch.
=> 🌱 deps: skip github.com/onsi/ginkgo/v2 on release-0.11

api/v1beta1/conditions_consts.go, controllers/openstackmachine_controller.go, controllers/openstackserver_controller.go, controllers/openstackserver_controller_test.go, test/e2e/data/e2e_conf.yaml, test/e2e/shared/openstack.go, test/e2e/suites/e2e/e2e_test.go
The panic happened because we did not correctly handle that GetInstanceStatus returns a nil server if the server does not exist, rather than a 404 error.
We had the same oversight in the OpenStackServer controller. It looks like this would have resulted in recreating the server.
Fixes: #2474
/hold
=> Fix panic when OpenStack server is deleted by an external agent

controllers/openstackmachine_controller.go, test/e2e/suites/e2e/e2e_test.go
With this change, an OpenStackMachine will not be marked Ready until it has been completely initialised, including setting its Addresses and adding it to the APIServer loadbalancer if required.
Also fix a missing early return when the instance has been unexpectedly deleted.
/hold
=> Don't set OSMachine Ready until all config is complete

Makefile, hack/ci/common.sh, hack/ci/create_devstack.sh, scripts/ci-e2e.sh
With this change we build the prerequisites of the e2e tests in parallel with the devstack build. We also upload the e2e image to devstack while devstack is still building, as soon as SSH is available.
This seems to result in an approximately 10 minute speed-up.
/hold
=> ci: build e2e prerequisites in parallel

controllers/openstackserver_controller.go
This fixes a bad error message format, wtih "%s" appearing in the log message ("OpenStackServer %s/%s linked to..."):
```
I0317 13:20:19.512088  1 openstackserver_controller.go:109] 
"OpenStackServer %s/%s linked to a Cluster that is paused. Won't reconcile" 
controllerGroup="infrastructure.cluster.x-k8s.io" 
controllerKind="OpenStackServer" 
OpenStackServer="sylva-system/management-cluster-cp-f7843e31d7-rbv5c" 
namespace="sylva-system" 
name="management-cluster-cp-f7843e31d7-rbv5c" 
reconcileID="a0e2f500-ae75-47af-bc3b-85bb9ae4b59b" 
sylva-system="management-cluster-cp-f7843e31d7-rbv5c"
```
We in fact don't need the "%s/%s" and also the additional parameters aren't needed because the logger is derived from "scope" and already logging the server name and namespace.
=> OpenStackServer controller: minor log message fix

controllers/openstackcluster_controller.go
This PR makes it so that if an floatingIP is set in the `openstackcluster.spec.bastion.floatingIP`, and it is the same as set in the `status` of the `openstackcluster` resource, it will not be deleted when deleting the cluster.
Fixes #2157 
My issue got stale so I am creating this PR so that hopefully this feature does not get forgotten.
**TODOs**:
/hold
=> Do not delete bastion floating ip if set in spec

controllers/openstackserver_controller.go
OpenstackServer controller does not use concurrency option. This PR sets the options for concurrency.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2501
**TODOs**:
/hold
=> 🐛 fix openstackserver controller concurrency

cloudbuild.yaml
I noticed that the cloud-build was showing errors while doing the releases. It is due to the image used. It did not have go1.23, which is required since release-0.12 in CAPO. Container image builds still worked because those are built inside a build container.
The cloud-build has been failing with errors like this:
```
make -C hack/tools bin/kustomize
make[4]: Entering directory '/workspace/hack/tools'
mkdir -p bin
CGO_ENABLED=0 go build -tags=tools -o bin/kustomize sigs.k8s.io/kustomize/kustomize/v5
go: go.mod requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local)
make[4]: *** [Makefile:115: bin/kustomize] Error 1
make[4]: Leaving directory '/workspace/hack/tools'
make[3]: Leaving directory '/workspace'
make[3]: *** [common.mk:49: …
```
=> 🌱 Bump cloud-build image to support go 1.23

.github/workflows/security-scan.yaml, Makefile, hack/ensure-trivy.sh, hack/verify-container-images.sh
This adds a github workflow that runs the govulncheck and trivy.
It is all copied and adapted from CAPI (hence the existing licenses at the top).
We may want to think about how to notify maintainers of this.
Fixes #
**TODOs**:
/hold
=> 🌱 Add weekly security scan using govulncheck and Trivy

.github/workflows/security-scan.yaml, CONTRIBUTING.md
We are not supporting release-0.10 any more so running security scans there doesn't make much sense for anything other than seeing how fast things deteriorate.
Fixes #
**TODOs**:
=> 🌱 Disable security scanning for release-0.10

Makefile
I was mistaken in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2557 when I said that it fixed GO-2025-3563. It only looked that way because I had a go version with the fix locally when I ran the scan.
In the [scan job with correct go version](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/actions/runs/15109209113/job/42654556860) it still shows up as affected.
This bumps the go version that we use for building the binaries to 1.23.8 without touching the required version. I.e. it is still possible to build everything using go 1.22, but we are using go 1.23.8 to avoid vulnerabilities.
I am fairly certain that this should be ok and I have double checked with CAPI, to see how they are handling this.
In …
=> 🌱 Build with go1.23.8

Makefile, test/e2e/data/e2e_conf.yaml, test/e2e/data/kustomize/common-patches/images-without-ref/images.yaml, test/e2e/data/kustomize/common-patches/images-without-ref/kustomization.yaml, test/e2e/data/kustomize/without-orc/kustomization.yaml, test/e2e/shared/defaults.go, test/e2e/suites/e2e/clusterctl_upgrade_test.go
This is an attempt to fix the clusterctl-upgrade test that is currently failing on this branch. Starting from v0.9 is probably part of the issue since this is so old an unsupported now.
Fixes #
**TODOs**:
/hold
=> 🌱 E2E: clusterctl-upgrade from v0.10

controllers/openstackserver_controller.go
Add watch of IPAddressClaims in the OpenstackServer controller
**Which issue(s) this PR fixes** :
Fixes #2389
**TODOs**:
/hold
=> 🐛 fix: watch ipaddressclaim in openstackserver controller

controllers/openstackmachine_controller.go, controllers/openstackmachine_controller_test.go
FlavorID can be used in stead of Flavor when specifying machine and server is then created succesfully as well. Additional unit tests testing Flavor and FlavorID conversion from machine to server.
Fixes #2550
**TODOs**:
/hold
=> :bug: Add FlavorID to be set by openStackMachineSpecToOpenStackServerSpec

test/e2e/data/e2e_conf.yaml, test/e2e/data/shared/openstack-resource-controller/metadata.yaml, test/e2e/shared/openstack.go, test/infrastructure/openstack-resource-controller/config/default/kustomization.yaml
Bump ORC in e2e tests. We already bumped to go module.
Fixes #
**TODOs**:
/hold
=> 🌱 E2E: Bump ORC to v2.2.0

controllers/openstackserver_controller_test.go, pkg/cloud/services/networking/port.go
When port ID is available we should just search by the ID and not combine name and network of the port.
When we have Port ID available we should just search using the Port ID. This is more efficient and avoids issues when port are renamed.
Fixes #2576 
**TODOs**:
/hold
=> 🐛 Search by either port ID or name/network

Makefile, netlify.toml
Manual backport of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2593
This addresses three vulnerabilities in the standard library:
- GO-2025-3751
- GO-2025-3750
- GO-2025-3749
Fixes #
**TODOs**:
=> 🌱 Bump go to 1.23.10

kustomize/v1beta1/default/cluster-template.yaml, templates/cluster-template-flatcar-sysext.yaml, templates/cluster-template-flatcar.yaml, templates/cluster-template-without-lb.yaml, templates/cluster-template.yaml, templates/clusterclass-dev-test.yaml
This is a partial backport of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2600 with only the template changes. The e2e config is left as-is.
Templates needed to be updated for v1.32 as the API server has dropped the cloud-provider flag.
Note: Sysext-bakery URLs also need updates for newer releases, but we need to keep the older URL for the versions we
test in the E2E suite.
Fixes #
**TODOs**:
/hold
=> 🌱 Update templates

Makefile
Make it possible to specify extra arguments for govulncheck by setting GOVULNCHECK_ARGS. This is useful for finding vulnerabilities that govulncheck determines are irrelevant. Use GOVULNCHECK_ARGS="-show verbose" to see them.
Fixes #
**TODOs**:
=> 🌱 Makefile: Add arguments for govulncheck

go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum
This addresses CVE-2025-22868, which is showing up in our [security scan](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/actions/runs/16565239170/job/46843657087).
See https://pkg.go.dev/vuln/GO-2025-3488
Fixes #
**TODOs**:
=> 🌱 Bump oauth2

docs/proposals/20250722-openstackclusteridentity.md
This PR adds a proposal doc to work on the issue described in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2386
=> proposal: add new CRD OpenStackClusterIdentity

test/e2e/data/cni/calico.yaml
This updates Calico that we use in the e2e tests.
Fixes #2566
**TODOs**:
=> 🌱 E2E: Update Calico to v3.30.2

.golangci.yml, api/v1alpha1/openstackfloatingippool_types.go, api/v1alpha1/openstackserver_types.go, api/v1beta1/conditions_consts.go, api/v1beta1/openstackcluster_types.go, api/v1beta1/openstackmachine_types.go, controllers/openstackcluster_controller.go, controllers/openstackcluster_controller_test.go, controllers/openstackfloatingippool_controller.go, controllers/openstackmachine_controller.go, controllers/openstackserver_controller.go, controllers/openstackserver_controller_test.go, pkg/cloud/services/loadbalancer/loadbalancer_test.go, test/e2e/shared/defaults.go, test/e2e/suites/apivalidations/openstackcluster_test.go, test/e2e/suites/e2e/e2e_test.go
This will make it easier to make changes in the future, when we continue taking in more of the v1beta2.
Fixes #
**TODOs**:
=> 🌱 Unify and enforce CAPI import aliases

.golangci.yml, Makefile, controllers/openstackfloatingippool_controller.go, controllers/openstackmachine_controller.go, controllers/openstackserver_controller.go, hack/tools/Makefile, pkg/cloud/services/compute/instance.go, pkg/cloud/services/compute/referenced_resources.go, test/e2e/shared/common.go
Per $subject.
(none)
(none)
/hold
=> 🌱 Bump golangci-lint to v2

controllers/openstackcluster_controller.go, controllers/openstackmachine_controller.go, controllers/openstackmachine_controller_test.go, docs/book/src/SUMMARY.md, docs/book/src/topics/hosted-control-plane.md
Fixes a nil pointer panic in OpenStackMachineReconciler when OpenStackCluster.Status.Network is nil, which occurs in Hosted Control Plane scenarios. The controller now gracefully handles missing cluster network by checking for nil before access and returning a terminal error instead of panicking. Also adds comprehensive HCP E2E test suite.
Fixes #2380 
**TODOs**:
/hold
=> 🐛 Fix panic when OpenStackCluster.Status.Network is nil in HCP scenarios

.github/ISSUE_TEMPLATE/new_release.md, .github/dependabot.yml
Adding entry of new release branch to depandabot config. Also removing some dependency on main and release-0.13 config which are no longer needed here because of k8s and go uplift on these branch.
Fixes #2686
=> 🌱Add entry of new release branch to depandabot

Makefile
Uplifting go version to 1.24.6 to address security [issues](https://groups.google.com/g/golang-announce/c/x5MKroML2yM) here. It will address 
CVE-2025-47906 with Go [issue](https://go.dev/issue/74466)
CVE-2025-47907 with Go [issue](https://go.dev/issue/74831)
=>  🌱Uplift go 1.24.6 to address security issue

Makefile
Uplifting go version to 1.23.12 to address security [issues](https://groups.google.com/g/golang-announce/c/x5MKroML2yM) here. It will address
CVE-2025-47906 with Go [issue](https://go.dev/issue/74466)
https://github.com/advisories/GHSA-j5pm-7495-qmr3 with Go [issue](https://go.dev/issue/74831)
=> 🌱Uplift go 1.23.12 to address security issue in release-0.12

Makefile
Fixes an uncalled CVE for net/http (CVE-2025-47910)
=> 🌱Bump go version to 1.24.7

.github/workflows/update-golangci-lint.yaml
This workflow needs more permissions. There is an example in the docs: https://github.com/peter-evans/create-pull-request
We were missing `contents: write`.
Fixes #2747
**TODOs**:
=> 🌱 Fix update-golangci-lint permissions

Dockerfile, Makefile
Uplift go 1.24.8 to address the security vulnerabilities. These minor releases include PRIVATE security fixes to the standard library, covering the following CVEs: [announcement](https://groups.google.com/g/golang-announce/c/ask65OnfzGU)
CVE-2025-61724
CVE-2025-61725
CVE-2025-58187
CVE-2025-61723
CVE-2025-47912
CVE-2025-58185
CVE-2025-58186
CVE-2025-58188
CVE-2025-58183
=> 🐛 Uplift go 1.24.8 to address security issue
